// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
  upgrade_url?: string | null;
}

export interface GetAudioReelsParams {
  /** The audio id from an audio page URL, instagram.com/reels/audio/<audio_id>/. */
  audio_id: string;
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: string | null;
}

export interface GetBasicProfileParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: "1d" | "3d" | "7d" | "14d" | "30d" | null;
  /** Numeric Instagram user id. */
  userId: string;
}

export interface GetEmbedParams {
  /** Instagram handle, with or without a leading @. */
  handle: string;
}

export interface GetHighlightDetailParams {
  /** The highlight id from `/v1/instagram/user/highlights`, with or without the `highlight:` prefix. */
  id: string;
}

export type GetHighlightsParams = {
  /** Instagram handle, with or without a leading @. Send this or `user_id`. */
  handle?: string | null;
  /** Numeric Instagram user id. Send this or `handle`; when both are sent, `user_id` wins. */
  user_id?: string | null;
} & ({ handle: string; } | { user_id: string; });

export interface GetPostCommentsParams {
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: string | null;
  /** Accepted for Scrape Creators compatibility only as false: Instagram does not show replies to logged-out visitors. */
  include_replies?: false | null;
  /** Instagram post or reel URL: https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/, /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or instagr.am. Query strings are allowed. */
  url: string;
}

export interface GetPostCountParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: Tapline always answers the exact count. */
  allow_estimated?: boolean | null;
  /** Instagram handle, with or without a leading @. */
  handle: string;
}

export interface GetPostParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: "1d" | "3d" | "7d" | "14d" | "30d" | null;
  /** Accepted for Scrape Creators compatibility only as false: Tapline does not re-host media. */
  download_media?: false | null;
  /** Set to false to omit `video_play_count` and skip the extra lookup it needs. Defaults to true. Only videos carry a play count. */
  include_play_count?: boolean;
  /** Two-letter country code for the exit the request leaves from. Defaults to US, where Instagram shows licensed music. */
  region?: string | null;
  /** Set to true for Scrape Creators' trimmed answer: fewer fields per item, same values. */
  trim?: boolean;
  /** Instagram post or reel URL: https://www.instagram.com/p/<shortcode>/, /reel/<shortcode>/, /reels/<shortcode>/ or /tv/<shortcode>/, on instagram.com or instagr.am. Query strings are allowed. */
  url: string;
}

export interface GetProfileParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: "1d" | "3d" | "7d" | "14d" | "30d" | null;
  /** Instagram handle, with or without a leading @. */
  handle: string;
  /** Set to true for Scrape Creators' trimmed answer: fewer fields per item, same values. */
  trim?: boolean;
}

export interface GetUserPostsParams {
  /** Instagram handle, with or without a leading @. */
  handle: string;
  /** The `next_max_id` from the previous page, or the `end_cursor` of `/v1/instagram/profile`'s timeline. Omit it for the first page. */
  next_max_id?: string | null;
  /** Set to true for Scrape Creators' trimmed answer: fewer fields per item, same values. */
  trim?: boolean;
}

export type GetUserReelsParams = {
  /** Instagram handle, with or without a leading @. Send this or `user_id`. */
  handle?: string | null;
  /** The `paging_info.max_id` (or trimmed `max_id`) from the previous page. Omit it for the first page. It is base64, so percent-encode `+` and `/` in a hand-built URL. */
  max_id?: string | null;
  /** Set to true for Scrape Creators' trimmed answer: fewer fields per item, same values. */
  trim?: boolean;
  /** Numeric Instagram user id. Send this or `handle`; when both are sent, `user_id` wins. */
  user_id?: string | null;
} & ({ handle: string; } | { user_id: string; });

export interface InstagramAchievementsInfo {
  num_earned_achievements?: unknown | null;
  show_achievements?: boolean | null;
}

export interface InstagramAdditionalAudioInfo {
  additional_audio_username?: unknown | null;
  audio_reattribution_info?: InstagramAudioReattributionInfo | null;
}

export interface InstagramAudioMutingInfo {
  allow_audio_editing?: boolean | null;
  mute_audio?: boolean | null;
  mute_reason_str?: string | null;
  show_muted_audio_toast?: boolean | null;
}

export interface InstagramAudioRankingInfo {
  best_audio_cluster_id?: string | null;
}

export interface InstagramAudioReattributionInfo {
  should_allow_restore?: boolean | null;
}

export interface InstagramAudioReelsPageReel {
  ai_label_info?: InstagramReelAILabelInfo | null;
  are_remixes_crosspostable?: boolean | null;
  basel_encoding_timeout?: number | null;
  boost_unavailable_identifier?: unknown | null;
  boost_unavailable_reason?: unknown | null;
  boost_unavailable_reason_v2?: unknown[] | null;
  can_see_insights_as_brand?: boolean | null;
  can_view_more_preview_comments?: boolean | null;
  can_viewer_reshare?: boolean | null;
  can_viewer_save?: boolean | null;
  caption?: InstagramReelCaption | null;
  caption_is_edited?: boolean | null;
  client_cache_key?: string | null;
  clips_metadata?: InstagramAudioReelsPageReelClipsMetadata | null;
  clips_tab_pinned_user_ids?: unknown[] | null;
  coauthor_producer_can_see_organic_insights?: boolean | null;
  coauthor_producers?: InstagramUserPostsPageItemCoauthorProducer[] | null;
  code?: string | null;
  collaborator_edit_eligibility?: boolean | null;
  comment_count?: number | null;
  comment_inform_treatment?: InstagramCommentInformTreatment | null;
  commenting_disabled_for_viewer?: boolean | null;
  commerce_integrity_review_decision?: string | null;
  creative_config?: InstagramReelCreativeConfig | null;
  cutout_sticker_info?: unknown[] | null;
  deleted_reason?: number | null;
  device_timestamp?: number | null;
  eligible_insights_entrypoints?: string | null;
  enable_media_notes_production?: boolean | null;
  fb_play_count?: number | null;
  fb_user_tags?: InstagramFbUserTags | null;
  fbid?: number | string | null;
  filter_type?: number | null;
  gen_ai_detection_method?: InstagramGenAIDetectionMethod | null;
  has_audio?: boolean | null;
  has_delayed_metadata?: boolean | null;
  has_liked?: boolean | null;
  has_privately_liked?: boolean | null;
  has_shared_to_fb?: number | null;
  has_tagged_users?: boolean | null;
  has_views_fetching?: boolean | null;
  hidden_likes_string_variant?: number | null;
  hide_view_all_comment_entrypoint?: boolean | null;
  id?: number | string | null;
  ig_media_sharing_disabled?: boolean | null;
  ig_play_count?: number | null;
  igbio_product?: unknown | null;
  image_versions2?: InstagramAudioReelsPageReelImageVersions2 | null;
  integrity_review_decision?: string | null;
  invited_coauthor_producers?: unknown[] | null;
  is_awaiting_distribution?: boolean | null;
  is_comments_gif_composer_enabled?: boolean | null;
  is_cutout_sticker_allowed?: boolean | null;
  is_dash_eligible?: number | null;
  is_eligible_content_for_post_roll_ad?: boolean | null;
  is_eligible_for_poe?: boolean | null;
  is_in_profile_grid?: boolean | null;
  is_open_to_public_submission?: boolean | null;
  is_organic_product_tagging_eligible?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_photo_comments_composer_enabled_for_author?: boolean | null;
  is_post_live_clips_media?: boolean | null;
  is_quiet_post?: boolean | null;
  is_reshare_of_text_post_app_media_in_ig?: boolean | null;
  is_reuse_allowed?: boolean | null;
  is_social_ufi_disabled?: boolean | null;
  is_tagged_media_shared_to_viewer_profile_grid?: boolean | null;
  is_third_party_downloads_eligible?: boolean | null;
  is_unified_video?: boolean | null;
  is_visual_reply_commenter_notice_enabled?: boolean | null;
  lat?: number | null;
  like_and_view_counts_disabled?: boolean | null;
  like_count?: number | null;
  lng?: number | null;
  location?: InstagramReelLocation | null;
  locations?: unknown[] | null;
  media_attributions_data?: unknown[] | null;
  media_cropping_info?: InstagramMediaCroppingInfo | null;
  media_overlay_info?: unknown | null;
  media_reposter_bottomsheet_enabled?: boolean | null;
  media_type?: number | null;
  media_ui_attributions_data?: unknown[] | null;
  media_ui_attributions_data_v2?: unknown[] | null;
  meta_ai_suggested_prompts?: unknown[] | null;
  mezql_token?: string | null;
  music_metadata?: unknown | null;
  number_of_qualities?: number | null;
  organic_tracking_token?: string | null;
  original_height?: number | null;
  original_lang_for_translations?: string | null;
  original_width?: number | null;
  photo_of_you?: boolean | null;
  pk?: number | string | null;
  play_count?: number | null;
  product_type?: string | null;
  profile_grid_control_enabled?: boolean | null;
  related_ads_pivots_media_info?: string | null;
  share_count_disabled?: boolean | null;
  sharing_friction_info?: InstagramSharingFrictionInfo | null;
  should_request_ads?: boolean | null;
  should_show_author_pog_for_tagged_media_shared_to_profile_grid?: boolean | null;
  strong_id__?: string | null;
  subscribe_cta_visible?: boolean | null;
  subtype_name_for_REST__?: string | null;
  taken_at?: number | null;
  timeline_pinned_user_ids?: (number | string)[] | null;
  translated_langs_for_autodub?: unknown[] | null;
  user?: InstagramAudioReelsPageReelUser | null;
  usertags?: InstagramReelUsertags | null;
  video_dash_manifest?: string | null;
  video_duration?: number | null;
  video_sticker_locales?: string[] | null;
  video_versions?: InstagramCarouselMediaVideoVersion[] | null;
  view_state_item_type?: number | null;
}

export interface InstagramAudioReelsPageReelClipsMetadata {
  achievements_info?: InstagramAchievementsInfo | null;
  additional_audio_info?: InstagramAdditionalAudioInfo | null;
  asset_recommendation_info?: unknown | null;
  audio_ranking_info?: InstagramAudioRankingInfo | null;
  audio_type?: string | null;
  branded_content_tag_info?: InstagramBrandedContentTagInfo | null;
  clips_creation_entry_point?: string | null;
  content_appreciation_info?: InstagramAudioReelsPageReelClipsMetadataContentAppreciationInfo | null;
  contextual_highlight_info?: unknown | null;
  cutout_sticker_info?: unknown[] | null;
  disable_use_in_clips_client_cache?: boolean | null;
  featured_label?: unknown | null;
  is_fan_club_promo_video?: unknown | null;
  is_public_chat_welcome_video?: boolean | null;
  is_shared_to_fb?: boolean | null;
  mashup_info?: InstagramAudioReelsPageReelClipsMetadataMashupInfo | null;
  music_canonical_id?: number | string | null;
  music_info?: InstagramAudioReelsPageReelClipsMetadataMusicInfo | null;
  nux_info?: unknown | null;
  original_sound_info?: InstagramAudioReelsPageReelClipsMetadataOriginalSoundInfo | null;
  originality_info?: unknown | null;
  professional_clips_upsell_type?: number | null;
  reels_on_the_rise_info?: unknown | null;
  reusable_text_attribute_string?: unknown | null;
  reusable_text_info?: unknown | null;
  shopping_info?: unknown | null;
  show_achievements?: boolean | null;
  template_info?: unknown | null;
  viewer_interaction_settings?: unknown | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataContentAppreciationInfo {
  enabled?: boolean | null;
  entry_point_container?: InstagramEntryPointContainer | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataMashupInfo {
  can_toggle_mashups_allowed?: boolean | null;
  formatted_mashups_count?: unknown | null;
  has_been_mashed_up?: boolean | null;
  has_nonmimicable_additional_audio?: boolean | null;
  is_creator_requesting_mashup?: boolean | null;
  is_light_weight_check?: boolean | null;
  is_light_weight_reuse_allowed_check?: boolean | null;
  is_pivot_page_available?: boolean | null;
  is_reuse_allowed?: boolean | null;
  mashup_type?: unknown | null;
  mashups_allowed?: boolean | null;
  non_privacy_filtered_mashups_media_count?: number | null;
  original_media?: unknown | null;
  privacy_filtered_mashups_media_count?: unknown | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataMusicInfo {
  music_asset_info?: InstagramAudioReelsPageReelClipsMetadataMusicInfoMusicAssetInfo | null;
  music_consumption_info?: InstagramAudioReelsPageReelClipsMetadataMusicInfoMusicConsumptionInfo | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataMusicInfoMusicAssetInfo {
  allows_saving?: boolean | null;
  artist_id?: string | null;
  audio_asset_id?: number | string | null;
  audio_cluster_id?: string | null;
  cover_artwork_thumbnail_uri?: string | null;
  cover_artwork_uri?: string | null;
  dark_message?: unknown | null;
  dash_manifest?: string | null;
  display_artist?: string | null;
  duration_in_ms?: number | null;
  fast_start_progressive_download_url?: string | null;
  has_lyrics?: boolean | null;
  highlight_start_times_in_ms?: number[] | null;
  id?: number | string | null;
  ig_username?: string | null;
  is_eligible_for_audio_effects?: boolean | null;
  is_eligible_for_vinyl_sticker?: boolean | null;
  is_explicit?: boolean | null;
  licensed_music_subtype?: string | null;
  lyrics?: unknown | null;
  progressive_download_url?: string | null;
  reactive_audio_download_url?: unknown | null;
  sanitized_title?: unknown | null;
  song_monetization_info?: unknown | null;
  spotify_track_metadata?: InstagramSpotifyTrackMetadata | null;
  subtitle?: string | null;
  title?: string | null;
  web_30s_preview_download_url?: unknown | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataMusicInfoMusicConsumptionInfo {
  allow_media_creation_with_music?: boolean | null;
  audio_asset_start_time_in_ms?: number | null;
  audio_filter_infos?: unknown[] | null;
  audio_muting_info?: InstagramAudioMutingInfo | null;
  contains_lyrics?: unknown | null;
  derived_content_id?: unknown | null;
  derived_content_start_time_in_composition_in_ms?: number | null;
  display_labels?: string[] | null;
  ig_artist?: InstagramUserPostsPageItemCoauthorProducer | null;
  is_bookmarked?: boolean | null;
  is_trending_in_clips?: boolean | null;
  overlap_duration_in_ms?: number | null;
  placeholder_profile_pic_url?: string | null;
  previous_trend_rank?: unknown | null;
  should_allow_music_editing?: boolean | null;
  should_mute_audio?: boolean | null;
  should_mute_audio_reason?: string | null;
  should_render_soundwave?: boolean | null;
  trend_rank?: unknown | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataOriginalSoundInfo {
  allow_creator_to_rename?: boolean | null;
  audio_asset_id?: number | string | null;
  audio_asset_start_time_in_ms?: number | null;
  audio_filter_infos?: unknown | null;
  audio_parts?: unknown[] | null;
  audio_parts_by_filter?: unknown[] | null;
  can_remix_be_shared_to_fb?: boolean | null;
  can_remix_be_shared_to_fb_expansion?: boolean | null;
  consumption_info?: InstagramAudioReelsPageReelClipsMetadataOriginalSoundInfoConsumptionInfo | null;
  dash_manifest?: string | null;
  derived_content_start_time_in_composition_in_ms?: number | null;
  duration_in_ms?: number | null;
  fb_downstream_use_xpost_metadata?: InstagramFbDownstreamUseXpostMetadata | null;
  hide_remixing?: boolean | null;
  ig_artist?: InstagramUserPostsPageItemCoauthorProducer | null;
  is_audio_automatically_attributed?: boolean | null;
  is_eligible_for_audio_effects?: boolean | null;
  is_eligible_for_vinyl_sticker?: boolean | null;
  is_explicit?: boolean | null;
  is_original_audio_download_eligible?: boolean | null;
  is_reuse_disabled?: boolean | null;
  is_xpost_from_fb?: boolean | null;
  music_canonical_id?: number | string | null;
  oa_owner_is_music_artist?: boolean | null;
  original_audio_subtype?: string | null;
  original_audio_title?: string | null;
  original_media_id?: number | string | null;
  overlap_duration_in_ms?: number | null;
  progressive_download_url?: string | null;
  should_mute_audio?: boolean | null;
  time_created?: number | null;
  trend_rank?: unknown | null;
  xpost_fb_creator_info?: unknown | null;
}

export interface InstagramAudioReelsPageReelClipsMetadataOriginalSoundInfoConsumptionInfo {
  display_labels?: string[] | null;
  display_media_id?: unknown | null;
  is_bookmarked?: boolean | null;
  is_trending_in_clips?: boolean | null;
  should_mute_audio_reason?: string | null;
}

export interface InstagramAudioReelsPageReelImageVersions2 {
  additional_candidates?: InstagramAudioReelsPageReelImageVersions2AdditionalCandidate | null;
  candidates?: InstagramAudioReelsPageReelImageVersions2Candidate[] | null;
  scrubber_spritesheet_info_candidates?: InstagramScrubberSpritesheetInfoCandidates | null;
  smart_thumbnail_enabled?: unknown | null;
}

export interface InstagramAudioReelsPageReelImageVersions2AdditionalCandidate {
  first_frame?: InstagramAudioReelsPageReelImageVersions2Candidate | null;
  igtv_first_frame?: InstagramAudioReelsPageReelImageVersions2Candidate | null;
  smart_frame?: unknown | null;
}

export interface InstagramAudioReelsPageReelImageVersions2Candidate {
  estimated_scans_sizes?: number[] | null;
  height?: number | null;
  scans_profile?: string | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramAudioReelsPageReelUser {
  account_badges?: unknown[] | null;
  account_type?: number | null;
  eligible_for_text_app_activation_badge?: boolean | null;
  fan_club_info?: InstagramAudioReelsPageReelUserFanClubInfo | null;
  fbid_v2?: number | string | null;
  feed_post_reshare_disabled?: boolean | null;
  full_name?: string | null;
  has_anonymous_profile_picture?: boolean | null;
  id?: number | string | null;
  interop_messaging_user_fbid?: number | string | null;
  is_embeds_disabled?: boolean | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  show_account_transparency_details?: boolean | null;
  strong_id__?: string | null;
  third_party_downloads_enabled?: number | null;
  transparency_product_enabled?: boolean | null;
  username?: string | null;
}

export interface InstagramAudioReelsPageReelUserFanClubInfo {
  autosave_to_exclusive_highlight?: boolean | null;
  connected_member_count?: number | null;
  fan_club_id?: string | null;
  fan_club_name?: string | null;
  fan_consideration_page_revamp_eligiblity?: InstagramFanConsiderationPageRevampEligiblity | null;
  has_created_ssc?: unknown | null;
  has_enough_subscribers_for_ssc?: unknown | null;
  is_fan_club_gifting_eligible?: boolean | null;
  is_fan_club_referral_eligible?: boolean | null;
  is_free_trial_eligible?: boolean | null;
  largest_public_bc_id?: unknown | null;
  should_show_playlists_in_profile_tab?: unknown | null;
  subscriber_count?: number | null;
}

export interface InstagramAudioReelsResponse {
  cursor: string | null;
  has_more: boolean | null;
  reels: InstagramAudioReelsPageReel[] | null;
}

export interface InstagramBasicProfileResponse {
  account_badges?: unknown[] | null;
  account_type?: number | null;
  address_street?: unknown | null;
  ai_agent_type?: unknown | null;
  aigm_account_label_info?: unknown | null;
  bio_links?: InstagramUpstreamProfilePageUserBioLink[] | null;
  biography?: string | null;
  biography_with_entities?: InstagramUpstreamBiographyWithEntities | null;
  category?: string | null;
  city_name?: unknown | null;
  external_lynx_url?: string | null;
  external_url?: string | null;
  fbid_v2?: number | string | null;
  follower_count?: number | null;
  following_count?: number | null;
  friendship_status?: unknown | null;
  full_name?: string | null;
  gating?: unknown | null;
  has_chaining?: unknown | null;
  has_longform_media?: boolean | null;
  has_profile_pic?: unknown | null;
  has_story_archive?: unknown | null;
  hd_profile_pic_url_info?: InstagramProfilePageUserHdProfilePicUrlInfo | null;
  hide_creator_marketplace_badge?: boolean | null;
  id?: number | string | null;
  is_business?: boolean | null;
  is_cannes?: boolean | null;
  is_coppa_enforced?: unknown | null;
  is_embeds_disabled?: boolean | null;
  is_memorialized?: boolean | null;
  is_private?: boolean | null;
  is_professional_account?: unknown | null;
  is_regulated_c18?: boolean | null;
  is_ring_creator?: unknown | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  latest_besties_reel_media?: unknown | null;
  latest_reel_media?: unknown | null;
  linked_fb_info?: unknown | null;
  live_broadcast_id?: unknown | null;
  live_broadcast_visibility?: unknown | null;
  media_count?: unknown | null;
  meta_verified_benefits_info?: InstagramUpstreamMetaVerifiedBenefitsInfo | null;
  mutual_followers_count?: unknown | null;
  pk: number | string | null;
  profile_context_facepile_users?: unknown | null;
  profile_context_links_with_user_ids?: unknown | null;
  profile_pic_genai_tool_info?: unknown[] | null;
  profile_pic_url?: string | null;
  pronouns?: unknown[] | null;
  reel_media_seen_timestamp?: unknown | null;
  regulated_news_in_locations?: unknown[] | null;
  remove_message_entrypoint?: unknown | null;
  ring_creator_metadata?: unknown | null;
  should_show_category?: boolean | null;
  show_account_transparency_details?: boolean | null;
  show_ring_award?: unknown | null;
  show_text_post_app_badge?: boolean | null;
  supervision_info?: unknown | null;
  text_post_app_badge_label?: string | null;
  total_clips_count?: number | null;
  transparency_label?: unknown | null;
  transparency_product?: unknown | null;
  username: string | null;
  zip?: unknown | null;
}

export interface InstagramBioLink {
  creation_source?: string | null;
  image_url?: string | null;
  is_pinned?: boolean | null;
  link_id?: string | null;
  link_type?: string | null;
  lynx_url?: string | null;
  media_accent_color_hex?: string | null;
  media_type?: string | null;
  title?: string | null;
  url?: string | null;
}

export interface InstagramBiographyWithEntities {
  entities?: unknown[] | null;
}

export interface InstagramBrandedContentTagInfo {
  can_add_tag?: boolean | null;
}

export interface InstagramBusinessAddressJSON {
}

export interface InstagramCarouselMedia {
  accessibility_caption?: string | null;
  caption?: InstagramReelCaption | null;
  carousel_parent_id?: string | null;
  commerciality_status?: string | null;
  creative_config?: unknown | null;
  display_uri?: string | null;
  explore_pivot_grid?: boolean | null;
  fb_user_tags?: InstagramFbUserTags | null;
  featured_products?: unknown[] | null;
  has_audio?: boolean | null;
  id?: number | string | null;
  image_versions2?: InstagramCarouselMediaImageVersions2 | null;
  is_dash_eligible?: number | null;
  media_overlay_info?: unknown | null;
  media_type?: number | null;
  number_of_qualities?: number | null;
  original_height?: number | null;
  original_width?: number | null;
  pk?: number | string | null;
  product_suggestions?: unknown[] | null;
  product_type?: string | null;
  sharing_friction_info?: InstagramSharingFrictionInfo | null;
  shop_routing_user_id?: unknown | null;
  strong_id__?: string | null;
  taken_at?: number | null;
  tappable_elements?: unknown[] | null;
  usertags?: InstagramCarouselMediaUsertags | null;
  video_codec?: string | null;
  video_dash_manifest?: string | null;
  video_duration?: number | null;
  video_versions?: InstagramCarouselMediaVideoVersion[] | null;
}

export interface InstagramCarouselMediaImageVersions2 {
  candidates?: InstagramUserPostsPageItemImageVersions2Candidate[] | null;
  scrubber_spritesheet_info_candidates?: InstagramScrubberSpritesheetInfoCandidates | null;
}

export interface InstagramCarouselMediaUsertags {
  in?: InstagramCarouselMediaUsertagsIn[] | null;
}

export interface InstagramCarouselMediaUsertagsIn {
  categories?: string[] | null;
  position?: number[] | null;
  show_category_of_user?: boolean | null;
  user?: InstagramCarouselMediaUsertagsInUser | null;
}

export interface InstagramCarouselMediaUsertagsInUser {
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramCarouselMediaVideoVersion {
  bandwidth?: number | null;
  fallback?: unknown | null;
  height?: number | null;
  id?: number | string | null;
  progressive_identifier?: string | null;
  type?: number | null;
  url?: string | null;
  url_expiration_timestamp_us?: unknown | null;
  width?: number | null;
}

export interface InstagramClipsDemotionControl {
  confirmation_body?: string | null;
  confirmation_icon?: string | null;
  confirmation_style?: string | null;
  confirmation_title?: string | null;
  confirmation_title_style?: string | null;
  enable_word_wrapping?: boolean | null;
  followup_options?: InstagramFollowupOption[] | null;
  title?: string | null;
  title_style?: string | null;
  undo_style?: string | null;
}

export interface InstagramClipsMusicAttributionInfo {
  artist_name?: string | null;
  audio_id?: string | null;
  should_mute_audio?: boolean | null;
  should_mute_audio_reason?: string | null;
  song_name?: string | null;
  uses_original_audio?: boolean | null;
}

export interface InstagramCommentInformTreatment {
  action_type?: unknown | null;
  should_have_inform_treatment?: boolean | null;
  text?: string | null;
  url?: unknown | null;
}

export interface InstagramCommentUser {
  id?: number | string | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export interface InstagramCommentsPageComment {
  child_comment_count?: unknown | null;
  comment_like_count?: number | null;
  created_at?: string | null;
  id?: number | string | null;
  text?: string | null;
  user?: InstagramCommentUser | null;
}

export interface InstagramCommentsResponse {
  comments: InstagramCommentsPageComment[] | null;
  cursor: string | null;
}

export interface InstagramCoverMedia {
  thumbnail_src?: string | null;
}

export interface InstagramCoverMediaCroppedThumbnail {
  url?: string | null;
}

export interface InstagramCtaRenderingConfig {
  eligible_ctas?: string[] | null;
  enable_primary_swap_for_cdd?: boolean | null;
  enable_secondary_swap_for_cdd?: boolean | null;
  primary_cta?: InstagramPrimaryCta | null;
  primary_cta_type?: string | null;
}

export interface InstagramDefault {
  file_size_kb?: number | null;
  max_thumbnails_per_sprite?: number | null;
  rendered_width?: number | null;
  sprite_height?: number | null;
  sprite_urls?: string[] | null;
  sprite_width?: number | null;
  thumbnail_duration?: number | null;
  thumbnail_height?: number | null;
  thumbnail_width?: number | null;
  thumbnails_per_row?: number | null;
  total_thumbnail_num_per_sprite?: number | null;
  video_length?: number | null;
}

export interface InstagramDemotionControl {
  confirmation_body?: string | null;
  confirmation_icon?: string | null;
  confirmation_style?: string | null;
  confirmation_title?: string | null;
  undo_style?: string | null;
}

export interface InstagramDescription {
  linked_terms?: unknown[] | null;
  plain_text?: string | null;
  source_uris?: string[] | null;
}

export interface InstagramDimensions {
  height?: number | null;
  width?: number | null;
}

export interface InstagramEdgeFelixVideoTimelinePageInfo {
  end_cursor?: unknown | null;
  has_next_page?: boolean | null;
}

export interface InstagramEdgeM {
  count?: number | null;
  edges?: unknown[] | null;
}

export interface InstagramEdgeMediaComment {
  count?: number | null;
  edges?: InstagramEdgeMediaPreviewCommentEdge[] | null;
}

export interface InstagramEdgeMediaPreviewCommentEdge {
  node?: InstagramEdgeMediaPreviewCommentEdgeNode | null;
}

export interface InstagramEdgeMediaPreviewCommentEdgeNode {
  created_at?: number | null;
  edge_liked_by?: InstagramProfilePageDataUserEdgeFollowedBy | null;
  id?: number | string | null;
  owner?: InstagramXdtShortcodeMediaOwner | null;
  text?: string | null;
}

export interface InstagramEdgeMediaToCaption {
  edges?: InstagramEdgeMediaToCaptionEdge[] | null;
}

export interface InstagramEdgeMediaToCaptionEdge {
  node?: InstagramEdgeMediaToCaptionEdgeNode | null;
}

export interface InstagramEdgeMediaToCaptionEdgeNode {
  created_at?: string | null;
  id?: number | string | null;
  text?: string | null;
}

export interface InstagramEdgeOwnerToTimelineMedia {
  count?: number | null;
  edges?: InstagramEdgeOwnerToTimelineMediaEdge[] | null;
  page_info?: InstagramEdgeOwnerToTimelineMediaPageInfo | null;
}

export interface InstagramEdgeOwnerToTimelineMediaEdge {
  node?: InstagramEdgeOwnerToTimelineMediaEdgeNode | null;
}

export interface InstagramEdgeOwnerToTimelineMediaEdgeNode {
  __isXDTGraphMediaInterface?: string | null;
  __typename?: string | null;
  clips_metadata?: InstagramNodeClipsMetadata | null;
  clips_music_attribution_info?: InstagramClipsMusicAttributionInfo | null;
  coauthor_producers?: InstagramUserPostsPageItemCoauthorProducer[] | null;
  comment_count?: number | null;
  comments_disabled?: boolean | null;
  created_at?: string | null;
  dimensions?: InstagramDimensions | null;
  display_resources?: InstagramResource[] | null;
  display_url?: string | null;
  edge_media_preview_comment?: InstagramEdgeM | null;
  edge_media_preview_like?: InstagramEdgeM | null;
  edge_media_to_caption?: InstagramEdgeMediaToCaption | null;
  edge_media_to_comment?: InstagramProfilePageDataUserEdgeFelixVideoTimeline | null;
  edge_media_to_parent_comment?: InstagramEdgeM | null;
  edge_media_to_tagged_user?: InstagramNodeEdgeMediaToTaggedUser | null;
  edge_sidecar_to_children?: InstagramNodeEdgeSidecarToChildren | null;
  has_audio?: boolean | null;
  id?: number | string | null;
  is_ad?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_video?: boolean | null;
  like_and_view_counts_disabled?: boolean | null;
  location?: InstagramReelLocation | null;
  owner?: InstagramEdgeOwnerToTimelineMediaEdgeNodeOwner | null;
  product_type?: string | null;
  shortcode?: string | null;
  taken_at_timestamp?: number | null;
  thumbnail_resources?: InstagramResource[] | null;
  thumbnail_src?: string | null;
  url?: string | null;
  video_duration?: number | null;
  video_play_count?: number | null;
  video_url?: string | null;
}

export interface InstagramEdgeOwnerToTimelineMediaEdgeNodeOwner {
  full_name?: string | null;
  id?: number | string | null;
  is_verified?: boolean | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export interface InstagramEdgeOwnerToTimelineMediaPageInfo {
  end_cursor?: string | null;
  has_next_page?: boolean | null;
}

export interface InstagramEdgeRelatedProfiles {
  edges?: unknown[] | null;
}

export interface InstagramEmbedResponse {
  html: string;
}

export interface InstagramEntryPointContainer {
  comment?: InstagramEntryPointContainerComment | null;
  overflow?: unknown | null;
  pill?: InstagramPill | null;
}

export interface InstagramEntryPointContainerComment {
  action_type?: string | null;
}

export interface InstagramExtensions {
  is_final?: boolean | null;
}

export interface InstagramFanConsiderationPageRevampEligiblity {
  should_show_content_preview?: boolean | null;
  should_show_social_context?: boolean | null;
}

export interface InstagramFbDownstreamUseXpostMetadata {
  downstream_use_xpost_deny_reason?: string | null;
}

export interface InstagramFbUserTags {
  in?: InstagramReelUsertagsIn[] | null;
}

export interface InstagramFollowupOption {
  data?: string | null;
  demotion_control?: InstagramDemotionControl | null;
  id?: number | string | null;
  show_icon?: boolean | null;
  style?: unknown | null;
  subtitle?: unknown | null;
  text?: string | null;
}

export interface InstagramFourByThreeCrop {
  crop_bottom?: number | null;
  crop_left?: number | null;
  crop_right?: number | null;
  crop_top?: number | null;
}

export interface InstagramFundraiserTag {
  has_standalone_fundraiser?: boolean | null;
}

export interface InstagramGenAIDetectionMethod {
  detection_method?: string | null;
}

export interface InstagramHighlight {
  __typename?: string | null;
  cover_media?: InstagramCoverMedia | null;
  cover_media_cropped_thumbnail?: InstagramCoverMediaCroppedThumbnail | null;
  id?: number | string | null;
  owner?: InstagramHighlightOwner | null;
  title?: string | null;
}

export interface InstagramHighlightDetailResponse {
  ad_expiry_timestamp_in_millis?: unknown | null;
  can_gif_quick_reply?: boolean | null;
  can_react_with_avatar?: boolean | null;
  can_reply?: boolean | null;
  can_reshare?: boolean | null;
  cover_media?: InstagramUpstreamCoverMedia | null;
  created_at?: number | null;
  disabled_reply_types?: string[] | null;
  highlight_reel_type?: string | null;
  id: string | null;
  is_added_to_main_grid?: boolean | null;
  is_archived?: boolean | null;
  is_cacheable?: boolean | null;
  is_converted_to_clips?: boolean | null;
  is_cta_sticker_available?: unknown | null;
  is_fit_green?: boolean | null;
  is_nux?: boolean | null;
  is_pinned_highlight?: boolean | null;
  items: InstagramUpstreamHighlightReelItem[] | null;
  latest_reel_media?: number | null;
  media_count?: number | null;
  media_ids?: string[] | null;
  pool_refresh_ttl_in_sec?: unknown | null;
  prefetch_count?: number | null;
  reel_type?: string | null;
  seen?: unknown | null;
  should_treat_link_sticker_as_cta?: unknown | null;
  show_expiration_tray_signal?: boolean | null;
  strong_id__?: string | null;
  title?: string | null;
  user?: InstagramUpstreamHighlightReelUser | null;
}

export interface InstagramHighlightOwner {
  __typename?: string | null;
  id?: number | string | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export interface InstagramHighlightsResponse {
  highlights: InstagramHighlight[] | null;
}

export interface InstagramIgArtist {
  id?: number | string | null;
  username?: string | null;
}

export interface InstagramItemAILabelInfo {
  attribution_label_text?: unknown | null;
  can_edit_self_disclosure?: boolean | null;
  content_sheet_sections?: unknown[] | null;
  gen_ai_detection_method?: string | null;
  is_self_disclosed?: boolean | null;
  should_read_attribution_label?: boolean | null;
  subtitle_text?: string | null;
}

export interface InstagramItemLocation {
  address?: string | null;
  city?: string | null;
  external_source?: string | null;
  facebook_places_id?: number | string | null;
  has_viewer_saved?: boolean | null;
  lat?: number | null;
  lng?: number | null;
  name?: string | null;
  pk?: number | string | null;
  short_name?: string | null;
}

export interface InstagramItemMashupInfo {
  can_toggle_mashups_allowed?: boolean | null;
  formatted_mashups_count?: unknown | null;
  has_been_mashed_up?: boolean | null;
  has_nonmimicable_additional_audio?: boolean | null;
  is_creator_requesting_mashup?: boolean | null;
  is_light_weight_check?: boolean | null;
  is_light_weight_reuse_allowed_check?: boolean | null;
  is_pivot_page_available?: boolean | null;
  is_reuse_allowed?: boolean | null;
  mashup_type?: unknown | null;
  mashups_allowed?: boolean | null;
  mashups_allowed_for_carousel?: boolean | null;
  non_privacy_filtered_mashups_media_count?: number | null;
  original_media?: unknown | null;
  privacy_filtered_mashups_media_count?: unknown | null;
}

export interface InstagramItemMedia {
  are_remixes_crosspostable?: boolean | null;
  basel_encoding_timeout?: number | null;
  boost_unavailable_identifier?: unknown | null;
  boost_unavailable_reason?: unknown | null;
  boost_unavailable_reason_v2?: unknown[] | null;
  can_see_insights_as_brand?: boolean | null;
  can_viewer_reshare?: boolean | null;
  can_viewer_save?: boolean | null;
  caption?: InstagramMediaCaption | null;
  caption_is_edited?: boolean | null;
  client_cache_key?: string | null;
  clips_demotion_control?: InstagramClipsDemotionControl | null;
  clips_metadata?: InstagramMediaClipsMetadata | null;
  clips_tab_pinned_user_ids?: unknown[] | null;
  coauthor_producer_can_see_organic_insights?: boolean | null;
  coauthor_producers?: InstagramUserPostsPageItemCoauthorProducer[] | null;
  code?: string | null;
  collaborator_edit_eligibility?: boolean | null;
  comment_count?: number | null;
  comment_inform_treatment?: InstagramCommentInformTreatment | null;
  commerce_integrity_review_decision?: string | null;
  created_at?: string | null;
  creative_config?: InstagramMediaCreativeConfig | null;
  creator_is_in_premium_reactions_alpha?: unknown | null;
  cta_rendering_config?: InstagramCtaRenderingConfig | null;
  cutout_sticker_info?: unknown[] | null;
  deleted_reason?: number | null;
  device_timestamp?: number | null;
  disable_caption_and_comment?: boolean | null;
  display_uri?: string | null;
  eligible_insights_entrypoints?: string | null;
  enable_media_notes_production?: boolean | null;
  fb_user_tags?: InstagramFbUserTags | null;
  fbid?: number | string | null;
  featured_products?: unknown[] | null;
  filter_type?: number | null;
  fundraiser_tag?: InstagramFundraiserTag | null;
  gen_ai_detection_method?: InstagramGenAIDetectionMethod | null;
  has_audio?: boolean | null;
  has_delayed_metadata?: boolean | null;
  has_liked?: boolean | null;
  has_privately_liked?: boolean | null;
  has_shared_to_fb?: number | null;
  has_tagged_users?: boolean | null;
  has_views_fetching?: boolean | null;
  hidden_likes_string_variant?: number | null;
  hide_stickers_for_original_language?: boolean | null;
  hide_view_all_comment_entrypoint?: boolean | null;
  id?: number | string | null;
  ig_media_sharing_disabled?: boolean | null;
  ig_play_count?: number | null;
  igbio_product?: unknown | null;
  image_versions2?: InstagramMediaImageVersions2 | null;
  integrity_review_decision?: string | null;
  invited_coauthor_producers?: unknown[] | null;
  is_affiliate_commission_eligible?: boolean | null;
  is_awaiting_distribution?: boolean | null;
  is_comments_gif_composer_enabled?: boolean | null;
  is_cutout_sticker_allowed?: boolean | null;
  is_dash_eligible?: number | null;
  is_educational?: unknown | null;
  is_eligible_content_for_post_roll_ad?: boolean | null;
  is_eligible_for_autodub?: boolean | null;
  is_eligible_for_autodub_upsell?: boolean | null;
  is_eligible_for_organic_eager_refresh?: boolean | null;
  is_eligible_for_poe?: boolean | null;
  is_eligible_for_poe_premium?: boolean | null;
  is_eligible_for_rta?: boolean | null;
  is_in_profile_grid?: boolean | null;
  is_meta_ai_invocation_blocked_by_author?: boolean | null;
  is_open_to_public_submission?: boolean | null;
  is_organic_product_tagging_eligible?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_photo_comments_composer_enabled_for_author?: boolean | null;
  is_post_live_clips_media?: boolean | null;
  is_quiet_post?: boolean | null;
  is_reshare_of_text_post_app_media_in_ig?: boolean | null;
  is_reuse_allowed?: boolean | null;
  is_shared_from_basel?: boolean | null;
  is_short_drama?: boolean | null;
  is_social_ufi_disabled?: boolean | null;
  is_third_party_downloads_eligible?: boolean | null;
  is_visual_reply_commenter_notice_enabled?: boolean | null;
  lat?: number | null;
  like_and_view_counts_disabled?: boolean | null;
  like_count?: number | null;
  linked_media_data?: InstagramLinkedMediaData | null;
  lng?: number | null;
  location?: InstagramReelLocation | null;
  locations?: unknown[] | null;
  logging_info_token?: string | null;
  media_attributions_data?: unknown[] | null;
  media_cropping_info?: InstagramMediaCroppingInfo | null;
  media_overlay_info?: unknown | null;
  media_reposter_bottomsheet_enabled?: boolean | null;
  media_type?: number | null;
  media_ui_attributions_data?: unknown[] | null;
  media_ui_attributions_data_v2?: unknown[] | null;
  meta_ai_suggested_prompts?: unknown[] | null;
  mezql_token?: string | null;
  music_metadata?: unknown | null;
  number_of_qualities?: number | null;
  organic_tracking_token?: string | null;
  original_height?: number | null;
  original_lang_for_translations?: string | null;
  original_media_has_visual_reply_media?: boolean | null;
  original_width?: number | null;
  photo_of_you?: boolean | null;
  pk?: number | string | null;
  play_count?: number | null;
  premium_reaction_count?: number | null;
  product_type?: string | null;
  profile_grid_control_enabled?: boolean | null;
  related_ads_pivots_media_info?: string | null;
  share_count_disabled?: boolean | null;
  sharing_friction_info?: InstagramSharingFrictionInfo | null;
  shop_routing_user_id?: unknown | null;
  should_request_ads?: boolean | null;
  should_show_author_pog_for_tagged_media_shared_to_profile_grid?: boolean | null;
  snippets_overlays?: InstagramSnippetsOverlay[] | null;
  strong_id__?: string | null;
  subscribe_cta_visible?: boolean | null;
  subtype_name_for_REST__?: string | null;
  taken_at?: number | null;
  tappable_elements?: unknown[] | null;
  teen_project_info?: unknown | null;
  timeline_pinned_user_ids?: (number | string)[] | null;
  translated_langs_for_autodub?: unknown[] | null;
  tya_media_related_topics?: unknown[] | null;
  url?: string | null;
  user?: InstagramMediaUser | null;
  usertags?: InstagramMediaUsertags | null;
  video_codec?: string | null;
  video_dash_manifest?: string | null;
  video_duration?: number | null;
  video_sticker_locales?: string[] | null;
  video_versions?: InstagramCarouselMediaVideoVersion[] | null;
  view_state_item_type?: number | null;
  viewer_premium_reaction_asset_id?: unknown | null;
}

export interface InstagramItemOwner {
  account_badges?: unknown[] | null;
  account_type?: number | null;
  can_see_quiet_post_attribution?: boolean | null;
  eligible_for_text_app_activation_badge?: boolean | null;
  fan_club_info?: InstagramOwnerFanClubInfo | null;
  fbid_v2?: number | string | null;
  feed_post_reshare_disabled?: boolean | null;
  full_name?: string | null;
  has_anonymous_profile_picture?: boolean | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  show_account_transparency_details?: boolean | null;
  strong_id__?: string | null;
  third_party_downloads_enabled?: number | null;
  transparency_product_enabled?: boolean | null;
  username?: string | null;
}

export interface InstagramLinkedMediaData {
  link_name?: string | null;
  media?: InstagramLinkedMediaDataMedia | null;
}

export interface InstagramLinkedMediaDataMedia {
  id?: number | string | null;
  strong_id__?: string | null;
}

export interface InstagramMediaCaption {
  bit_flags?: number | null;
  content_type?: string | null;
  created_at?: number | null;
  created_at_utc?: number | null;
  did_report_as_spam?: boolean | null;
  is_covered?: boolean | null;
  is_ranked_comment?: boolean | null;
  media_id?: number | string | null;
  pk?: number | string | null;
  private_reply_status?: number | null;
  share_enabled?: boolean | null;
  status?: string | null;
  strong_id__?: string | null;
  text?: string | null;
  text_translation?: string | null;
  type?: number | null;
  user?: InstagramMediaCaptionUser | null;
  user_id?: number | string | null;
}

export interface InstagramMediaCaptionUser {
  fbid_v2?: number | string | null;
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramMediaClipsMetadata {
  achievements_info?: InstagramAchievementsInfo | null;
  additional_audio_info?: InstagramAdditionalAudioInfo | null;
  asset_recommendation_info?: unknown | null;
  audio_ranking_info?: InstagramAudioRankingInfo | null;
  audio_type?: string | null;
  basel_template_info_for_ig_app?: InstagramMediaClipsMetadataBaselTemplateInfoForIgApp | null;
  branded_content_tag_info?: InstagramBrandedContentTagInfo | null;
  breaking_content_info?: unknown | null;
  breaking_creator_info?: unknown | null;
  challenge_info?: unknown | null;
  clips_creation_entry_point?: string | null;
  content_appreciation_info?: InstagramNodeClipsMetadataContentAppreciationInfo | null;
  contextual_highlight_info?: unknown | null;
  cutout_sticker_info?: unknown[] | null;
  disable_use_in_clips_client_cache?: boolean | null;
  external_media_info?: unknown | null;
  featured_label?: unknown | null;
  is_fan_club_promo_video?: unknown | null;
  is_public_chat_welcome_video?: boolean | null;
  is_shared_to_fb?: boolean | null;
  mashup_info?: InstagramItemMashupInfo | null;
  may_have_template_info?: unknown | null;
  merchandising_pill_info?: unknown | null;
  music_canonical_id?: number | string | null;
  music_info?: InstagramMediaClipsMetadataMusicInfo | null;
  nux_info?: unknown | null;
  original_sound_info?: InstagramMediaClipsMetadataOriginalSoundInfo | null;
  originality_info?: unknown | null;
  professional_clips_upsell_type?: number | null;
  reels_on_the_rise_info?: unknown | null;
  reusable_text_attribute_string?: unknown | null;
  reusable_text_info?: unknown | null;
  shopping_info?: unknown | null;
  show_achievements?: boolean | null;
  show_tips?: unknown | null;
  template_info?: unknown | null;
  viewer_interaction_settings?: unknown | null;
}

export interface InstagramMediaClipsMetadataBaselTemplateInfoForIgApp {
  is_basel_template?: unknown | null;
  original_template_media_id?: number | string | null;
  should_show_reuse_setting_for_owner?: boolean | null;
  use_template_deeplink?: unknown | null;
}

export interface InstagramMediaClipsMetadataMusicInfo {
  music_asset_info?: InstagramMediaClipsMetadataMusicInfoMusicAssetInfo | null;
  music_canonical_id?: number | string | null;
  music_consumption_info?: InstagramMediaClipsMetadataMusicInfoMusicConsumptionInfo | null;
}

export interface InstagramMediaClipsMetadataMusicInfoMusicAssetInfo {
  allows_saving?: boolean | null;
  artist_id?: string | null;
  audio_asset_id?: number | string | null;
  audio_cluster_id?: string | null;
  caption?: unknown | null;
  cover_artwork_thumbnail_uri?: string | null;
  cover_artwork_uri?: string | null;
  dark_message?: unknown | null;
  dash_manifest?: string | null;
  display_artist?: string | null;
  duration_in_ms?: number | null;
  fast_start_progressive_download_url?: string | null;
  has_lyrics?: boolean | null;
  highlight_start_times_in_ms?: number[] | null;
  id?: number | string | null;
  ig_username?: string | null;
  is_eligible_for_audio_effects?: boolean | null;
  is_eligible_for_vinyl_sticker?: boolean | null;
  is_explicit?: boolean | null;
  licensed_music_subtype?: string | null;
  lyrics?: unknown | null;
  progressive_download_url?: string | null;
  reactive_audio_download_url?: unknown | null;
  related_audios?: unknown | null;
  sanitized_title?: unknown | null;
  song_monetization_info?: unknown | null;
  spotify_track_metadata?: unknown | null;
  subtitle?: string | null;
  title?: string | null;
  web_30s_preview_download_url?: string | null;
}

export interface InstagramMediaClipsMetadataMusicInfoMusicConsumptionInfo {
  allow_media_creation_with_music?: boolean | null;
  audio_asset_start_time_in_ms?: number | null;
  audio_filter_infos?: unknown[] | null;
  audio_muting_info?: InstagramAudioMutingInfo | null;
  contains_lyrics?: unknown | null;
  derived_content_id?: unknown | null;
  derived_content_start_time_in_composition_in_ms?: unknown | null;
  display_labels?: unknown | null;
  display_labels_with_translations?: unknown | null;
  formatted_clips_media_count?: unknown | null;
  ig_artist?: InstagramUserPostsPageItemCoauthorProducer | null;
  is_bookmarked?: boolean | null;
  is_trending_in_clips?: boolean | null;
  music_creation_restriction_reason?: unknown | null;
  overlap_duration_in_ms?: number | null;
  placeholder_profile_pic_url?: string | null;
  previous_trend_rank?: unknown | null;
  related_audios?: unknown | null;
  should_allow_music_editing?: boolean | null;
  should_mute_audio?: boolean | null;
  should_mute_audio_reason?: string | null;
  should_mute_audio_reason_type?: unknown | null;
  should_render_soundwave?: boolean | null;
  trend_rank?: unknown | null;
  user_notes?: unknown | null;
}

export interface InstagramMediaClipsMetadataOriginalSoundInfo {
  allow_creator_to_rename?: boolean | null;
  attributed_custom_audio_asset_id?: unknown | null;
  audio_asset_id?: number | string | null;
  audio_asset_start_time_in_ms?: unknown | null;
  audio_filter_infos?: unknown[] | null;
  audio_parts?: unknown[] | null;
  audio_parts_by_filter?: unknown[] | null;
  can_remix_be_shared_to_fb?: boolean | null;
  can_remix_be_shared_to_fb_expansion?: boolean | null;
  consumption_info?: InstagramNodeClipsMetadataOriginalSoundInfoConsumptionInfo | null;
  dash_manifest?: string | null;
  derived_content_start_time_in_composition_in_ms?: unknown | null;
  duration_in_ms?: number | null;
  fb_downstream_use_xpost_metadata?: InstagramFbDownstreamUseXpostMetadata | null;
  formatted_clips_media_count?: unknown | null;
  hide_remixing?: boolean | null;
  ig_artist?: InstagramUserPostsPageItemCoauthorProducer | null;
  is_audio_automatically_attributed?: boolean | null;
  is_eligible_for_audio_effects?: boolean | null;
  is_eligible_for_vinyl_sticker?: boolean | null;
  is_explicit?: boolean | null;
  is_original_audio_download_eligible?: boolean | null;
  is_reuse_disabled?: boolean | null;
  is_xpost_from_fb?: boolean | null;
  music_canonical_id?: number | string | null;
  oa_owner_is_music_artist?: boolean | null;
  original_audio_subtype?: string | null;
  original_audio_title?: string | null;
  original_media_id?: number | string | null;
  overlap_duration_in_ms?: unknown | null;
  previous_trend_rank?: unknown | null;
  progressive_download_url?: string | null;
  should_mute_audio?: boolean | null;
  time_created?: number | null;
  trend_rank?: unknown | null;
  xpost_fb_creator_info?: unknown | null;
}

export interface InstagramMediaCreativeConfig {
  attribution_user?: unknown | null;
  capture_type?: string | null;
  creation_tool_info?: InstagramMediaCreativeConfigCreationToolInfo[] | null;
  effect_configs?: unknown | null;
  effect_preview?: unknown | null;
  face_effect_id?: unknown | null;
  failure_reason?: unknown | null;
  gen_ai_tool_info?: unknown | null;
}

export interface InstagramMediaCreativeConfigCreationToolInfo {
  appearance_effect?: number | null;
  camera_tool?: number | null;
  color_filters?: string | null;
  duration_selector_seconds?: number | null;
  effect_filter_name?: string | null;
  magic_cut_end_time?: number | null;
  magic_cut_start_time?: number | null;
  speed_selector?: number | null;
  timer_selector_seconds?: number | null;
}

export interface InstagramMediaCroppingInfo {
  four_by_three_crop?: InstagramFourByThreeCrop | null;
}

export interface InstagramMediaImageVersions2 {
  additional_candidates?: InstagramUserPostsPageItemImageVersions2AdditionalCandidate | null;
  candidates?: InstagramMediaImageVersions2Candidate[] | null;
  scrubber_spritesheet_info_candidates?: InstagramScrubberSpritesheetInfoCandidates | null;
}

export interface InstagramMediaImageVersions2Candidate {
  estimated_scans_sizes?: number[] | null;
  height?: number | null;
  is_spatial_image?: boolean | null;
  scans_profile?: string | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramMediaUser {
  account_badges?: unknown[] | null;
  account_type?: number | null;
  eligible_for_text_app_activation_badge?: boolean | null;
  fan_club_info?: InstagramOwnerFanClubInfo | null;
  fbid_v2?: number | string | null;
  feed_post_reshare_disabled?: boolean | null;
  full_name?: string | null;
  has_anonymous_profile_picture?: boolean | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  show_account_transparency_details?: boolean | null;
  strong_id__?: string | null;
  third_party_downloads_enabled?: number | null;
  transparency_product_enabled?: boolean | null;
  username?: string | null;
}

export interface InstagramMediaUsertags {
  in?: InstagramMediaUsertagsIn[] | null;
}

export interface InstagramMediaUsertagsIn {
  categories?: string[] | null;
  position?: number[] | null;
  show_category_of_user?: boolean | null;
  user?: InstagramUserPostsPageItemCoauthorProducer | null;
}

export interface InstagramNodeClipsMetadata {
  achievements_info?: unknown | null;
  additional_audio_info?: InstagramAdditionalAudioInfo | null;
  asset_recommendation_info?: unknown | null;
  audio_ranking_info?: InstagramAudioRankingInfo | null;
  audio_type?: string | null;
  basel_template_info_for_ig_app?: InstagramNodeClipsMetadataBaselTemplateInfoForIgApp | null;
  branded_content_tag_info?: InstagramBrandedContentTagInfo | null;
  breaking_content_info?: unknown | null;
  breaking_creator_info?: unknown | null;
  challenge_info?: unknown | null;
  clips_creation_entry_point?: string | null;
  content_appreciation_info?: InstagramNodeClipsMetadataContentAppreciationInfo | null;
  contextual_highlight_info?: unknown | null;
  cutout_sticker_info?: unknown[] | null;
  disable_use_in_clips_client_cache?: unknown | null;
  external_media_info?: unknown | null;
  featured_label?: unknown | null;
  is_fan_club_promo_video?: unknown | null;
  is_public_chat_welcome_video?: boolean | null;
  is_shared_to_fb?: boolean | null;
  mashup_info?: unknown | null;
  may_have_template_info?: unknown | null;
  merchandising_pill_info?: unknown | null;
  music_canonical_id?: number | string | null;
  music_info?: unknown | null;
  nux_info?: unknown | null;
  original_sound_info?: InstagramNodeClipsMetadataOriginalSoundInfo | null;
  originality_info?: unknown | null;
  professional_clips_upsell_type?: number | null;
  reels_on_the_rise_info?: unknown | null;
  reusable_text_attribute_string?: unknown | null;
  reusable_text_info?: unknown | null;
  shopping_info?: unknown | null;
  show_achievements?: unknown | null;
  show_tips?: unknown | null;
  template_info?: unknown | null;
  viewer_interaction_settings?: unknown | null;
}

export interface InstagramNodeClipsMetadataBaselTemplateInfoForIgApp {
  is_basel_template?: unknown | null;
  original_template_media_id?: number | string | null;
  should_show_reuse_setting_for_owner?: boolean | null;
  use_template_deeplink?: unknown | null;
}

export interface InstagramNodeClipsMetadataContentAppreciationInfo {
  enabled?: boolean | null;
  entry_point_container?: unknown | null;
}

export interface InstagramNodeClipsMetadataOriginalSoundInfo {
  allow_creator_to_rename?: boolean | null;
  attributed_custom_audio_asset_id?: unknown | null;
  audio_asset_id?: number | string | null;
  audio_asset_start_time_in_ms?: unknown | null;
  audio_filter_infos?: unknown[] | null;
  audio_parts?: unknown[] | null;
  audio_parts_by_filter?: unknown[] | null;
  can_remix_be_shared_to_fb?: boolean | null;
  can_remix_be_shared_to_fb_expansion?: boolean | null;
  consumption_info?: InstagramNodeClipsMetadataOriginalSoundInfoConsumptionInfo | null;
  dash_manifest?: string | null;
  derived_content_start_time_in_composition_in_ms?: unknown | null;
  duration_in_ms?: number | null;
  fb_downstream_use_xpost_metadata?: InstagramFbDownstreamUseXpostMetadata | null;
  formatted_clips_media_count?: unknown | null;
  hide_remixing?: boolean | null;
  ig_artist?: InstagramUserPostsPageItemCoauthorProducer | null;
  is_audio_automatically_attributed?: boolean | null;
  is_eligible_for_audio_effects?: boolean | null;
  is_eligible_for_vinyl_sticker?: boolean | null;
  is_explicit?: boolean | null;
  is_original_audio_download_eligible?: boolean | null;
  is_reuse_disabled?: boolean | null;
  is_xpost_from_fb?: boolean | null;
  music_canonical_id?: number | string | null;
  oa_owner_is_music_artist?: boolean | null;
  original_audio_subtype?: string | null;
  original_audio_title?: string | null;
  original_media_id?: number | string | null;
  overlap_duration_in_ms?: unknown | null;
  previous_trend_rank?: unknown | null;
  progressive_download_url?: string | null;
  should_mute_audio?: boolean | null;
  time_created?: number | null;
  trend_rank?: unknown | null;
  xpost_fb_creator_info?: unknown | null;
}

export interface InstagramNodeClipsMetadataOriginalSoundInfoConsumptionInfo {
  display_labels?: unknown | null;
  display_labels_with_translations?: unknown | null;
  display_media_id?: unknown | null;
  inline_audio_label?: unknown | null;
  is_bookmarked?: boolean | null;
  is_trending_in_clips?: boolean | null;
  should_mute_audio_reason?: string | null;
  should_mute_audio_reason_type?: unknown | null;
  user_notes?: unknown | null;
}

export interface InstagramNodeEdgeMediaToTaggedUser {
  edges?: InstagramNodeEdgeMediaToTaggedUserEdge[] | null;
}

export interface InstagramNodeEdgeMediaToTaggedUserEdge {
  node?: InstagramNodeEdgeMediaToTaggedUserEdgeNode | null;
}

export interface InstagramNodeEdgeMediaToTaggedUserEdgeNode {
  id?: number | string | null;
  user?: InstagramEdgeOwnerToTimelineMediaEdgeNodeOwner | null;
  x?: number | null;
  y?: number | null;
}

export interface InstagramNodeEdgeSidecarToChildren {
  edges?: InstagramNodeEdgeSidecarToChildrenEdge[] | null;
}

export interface InstagramNodeEdgeSidecarToChildrenEdge {
  node?: InstagramNodeEdgeSidecarToChildrenEdgeNode | null;
}

export interface InstagramNodeEdgeSidecarToChildrenEdgeNode {
  __typename?: string | null;
  dimensions?: InstagramDimensions | null;
  display_url?: string | null;
  id?: number | string | null;
  is_video?: boolean | null;
  shortcode?: unknown | null;
  video_url?: string | null;
}

export interface InstagramOwnerFanClubInfo {
  autosave_to_exclusive_highlight?: unknown | null;
  connected_member_count?: unknown | null;
  fan_club_id?: unknown | null;
  fan_club_name?: unknown | null;
  fan_consideration_page_revamp_eligiblity?: unknown | null;
  has_created_ssc?: unknown | null;
  has_enough_subscribers_for_ssc?: unknown | null;
  is_fan_club_gifting_eligible?: unknown | null;
  is_fan_club_referral_eligible?: unknown | null;
  is_free_trial_eligible?: unknown | null;
  largest_public_bc_id?: unknown | null;
  should_show_playlists_in_profile_tab?: unknown | null;
  subscriber_count?: unknown | null;
}

export interface InstagramPagingInfo {
  max_id?: string | null;
  more_available?: boolean | null;
}

export interface InstagramPill {
  action_type?: string | null;
  priority?: number | null;
}

export interface InstagramPopularSearchResponse {
  cursor: string | null;
  description?: InstagramDescription | null;
  has_more: boolean | null;
  posts: InstagramPost[] | null;
  query: string | null;
  suggested_terms?: string[] | null;
  title?: string | null;
  total_media_count?: number | null;
}

export interface InstagramPost {
  caption?: string | null;
  display_url?: string | null;
  id?: number | string | null;
  owner?: InstagramPostOwner | null;
  play_count?: number | null;
  shortcode?: string | null;
  type?: string | null;
  url?: string | null;
  video_url?: string | null;
}

export interface InstagramPostCountResponse {
  handle: string;
  is_estimated: boolean;
  media_count: number;
}

export interface InstagramPostFullResponse {
  data: InstagramPostPageData | null;
  extensions: InstagramExtensions | null;
  status: string | null;
  xdt_shortcode_media?: InstagramPostPageXdtShortcodeMedia | null;
}

export interface InstagramPostOwner {
  id?: number | string | null;
  is_verified?: boolean | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export interface InstagramPostPageData {
  xdt_shortcode_media?: InstagramPostPageDataXdtShortcodeMedia | null;
}

export interface InstagramPostPageDataXdtShortcodeMedia {
  __isXDTGraphMediaInterface?: string | null;
  __typename?: string | null;
  clips_metadata?: InstagramXdtShortcodeMediaClipsMetadata | null;
  clips_music_attribution_info?: InstagramClipsMusicAttributionInfo | null;
  coauthor_producers?: InstagramXdtShortcodeMediaCoauthorProducer[] | null;
  comment_count?: number | null;
  created_at?: string | null;
  display_url?: string | null;
  edge_media_preview_comment?: InstagramEdgeMediaComment | null;
  edge_media_preview_like?: InstagramEdgeM | null;
  edge_media_to_caption?: InstagramEdgeMediaToCaption | null;
  edge_media_to_parent_comment?: InstagramEdgeMediaComment | null;
  edge_media_to_tagged_user?: InstagramXdtShortcodeMediaEdgeMediaToTaggedUser | null;
  edge_sidecar_to_children?: InstagramXdtShortcodeMediaEdgeSidecarToChildren | null;
  has_audio?: boolean | null;
  id?: number | string | null;
  is_ad?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_video?: boolean | null;
  like_and_view_counts_disabled?: boolean | null;
  location?: InstagramXdtShortcodeMediaLocation | null;
  owner?: InstagramXdtShortcodeMediaOwner | null;
  product_type?: string | null;
  shortcode?: string | null;
  taken_at_timestamp?: number | null;
  thumbnail_src?: string | null;
  video_duration?: number | null;
  video_play_count?: number | null;
  video_url?: string | null;
}

export interface InstagramPostPageXdtShortcodeMedia {
  __typename?: string | null;
  clips_music_attribution_info?: InstagramClipsMusicAttributionInfo | null;
  display_url?: string | null;
  edge_media_preview_comment?: InstagramEdgeMediaComment | null;
  edge_media_preview_like?: InstagramEdgeM | null;
  edge_media_to_caption?: InstagramEdgeMediaToCaption | null;
  edge_media_to_parent_comment?: InstagramEdgeMediaComment | null;
  edge_sidecar_to_children?: InstagramXdtShortcodeMediaEdgeSidecarToChildren | null;
  has_audio?: boolean | null;
  id?: number | string | null;
  is_ad?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_video?: boolean | null;
  location?: InstagramXdtShortcodeMediaLocation | null;
  owner?: InstagramXdtShortcodeMediaOwner | null;
  product_type?: string | null;
  shortcode?: string | null;
  taken_at_timestamp?: number | null;
  thumbnail_src?: string | null;
  video_duration?: number | null;
  video_play_count?: number | null;
  video_url?: string | null;
}

export type InstagramPostResponse = InstagramPostFullResponse | InstagramPostTrimResponse;

export interface InstagramPostTrimResponse {
  data?: InstagramPostPageData | null;
  extensions?: InstagramExtensions | null;
  status?: string | null;
  xdt_shortcode_media: InstagramPostPageXdtShortcodeMedia | null;
}

export interface InstagramPrimaryCta {
  cta_type?: string | null;
  cta_type_category?: string | null;
  enable_swap_for_cdd?: boolean | null;
  enable_swap_for_rap?: boolean | null;
}

export interface InstagramProfilePageData {
  user?: InstagramProfilePageDataUser | null;
}

export interface InstagramProfilePageDataUser {
  ai_agent_owner_username?: unknown | null;
  ai_agent_type?: unknown | null;
  bio_links?: InstagramBioLink[] | null;
  biography?: string | null;
  biography_with_entities?: InstagramBiographyWithEntities | null;
  blocked_by_viewer?: boolean | null;
  business_address_json?: InstagramBusinessAddressJSON | null;
  business_category_name?: unknown | null;
  business_contact_method?: string | null;
  business_email?: unknown | null;
  business_phone_number?: unknown | null;
  category_enum?: unknown | null;
  category_name?: unknown | null;
  country_block?: boolean | null;
  edge_felix_video_timeline?: InstagramProfilePageDataUserEdgeFelixVideoTimeline | null;
  edge_follow?: InstagramProfilePageDataUserEdgeFollowedBy | null;
  edge_followed_by?: InstagramProfilePageDataUserEdgeFollowedBy | null;
  edge_media_collections?: InstagramProfilePageDataUserEdgeFelixVideoTimeline | null;
  edge_mutual_followed_by?: InstagramEdgeM | null;
  edge_owner_to_timeline_media?: InstagramEdgeOwnerToTimelineMedia | null;
  edge_related_profiles?: InstagramEdgeRelatedProfiles | null;
  edge_saved_media?: InstagramProfilePageDataUserEdgeFelixVideoTimeline | null;
  eimu_id?: unknown | null;
  external_url?: string | null;
  external_url_linkshimmed?: string | null;
  fb_profile_biolink?: unknown | null;
  fbid?: number | string | null;
  followed_by_viewer?: boolean | null;
  follows_viewer?: boolean | null;
  full_name?: string | null;
  group_metadata?: unknown | null;
  guardian_id?: unknown | null;
  has_ar_effects?: boolean | null;
  has_blocked_viewer?: boolean | null;
  has_channel?: boolean | null;
  has_clips?: boolean | null;
  has_guides?: boolean | null;
  has_onboarded_to_text_post_app?: boolean | null;
  has_requested_viewer?: boolean | null;
  hide_like_and_view_counts?: boolean | null;
  highlight_reel_count?: number | null;
  id?: number | string | null;
  is_business_account?: boolean | null;
  is_embeds_disabled?: boolean | null;
  is_guardian_of_viewer?: boolean | null;
  is_joined_recently?: boolean | null;
  is_private?: boolean | null;
  is_professional_account?: boolean | null;
  is_regulated_c18?: boolean | null;
  is_supervised_by_viewer?: boolean | null;
  is_supervised_user?: boolean | null;
  is_supervision_enabled?: boolean | null;
  is_verified?: boolean | null;
  is_verified_by_mv4b?: boolean | null;
  overall_category_name?: unknown | null;
  pinned_channels_list_count?: number | null;
  profile_pic_url?: string | null;
  profile_pic_url_hd?: string | null;
  pronouns?: unknown[] | null;
  remove_message_entrypoint?: boolean | null;
  requested_by_viewer?: boolean | null;
  restricted_by_viewer?: unknown | null;
  should_show_category?: boolean | null;
  should_show_public_contacts?: boolean | null;
  show_account_transparency_details?: boolean | null;
  show_text_post_app_badge?: boolean | null;
  transparency_label?: unknown | null;
  transparency_product?: unknown | null;
  username?: string | null;
}

export interface InstagramProfilePageDataUserEdgeFelixVideoTimeline {
  count?: number | null;
  edges?: unknown[] | null;
  page_info?: InstagramEdgeFelixVideoTimelinePageInfo | null;
}

export interface InstagramProfilePageDataUserEdgeFollowedBy {
  count?: number | null;
}

export interface InstagramProfilePageUserHdProfilePicUrlInfo {
  url?: string | null;
}

export interface InstagramProfileResponse {
  data: InstagramProfilePageData | null;
  status?: string | null;
}

export interface InstagramReelAILabelInfo {
  attribution_label_text?: unknown | null;
  content_sheet_sections?: unknown[] | null;
  gen_ai_detection_method?: string | null;
  should_read_attribution_label?: boolean | null;
  subtitle_text?: string | null;
}

export interface InstagramReelCaption {
  bit_flags?: number | null;
  content_type?: string | null;
  created_at?: number | null;
  created_at_utc?: number | null;
  did_report_as_spam?: boolean | null;
  is_covered?: boolean | null;
  is_ranked_comment?: boolean | null;
  media_id?: number | string | null;
  pk?: number | string | null;
  private_reply_status?: number | null;
  share_enabled?: boolean | null;
  status?: string | null;
  strong_id__?: string | null;
  text?: string | null;
  type?: number | null;
  user?: InstagramReelCaptionUser | null;
  user_id?: number | string | null;
}

export interface InstagramReelCaptionUser {
  fbid_v2?: number | string | null;
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramReelCreativeConfig {
  attribution_user?: unknown | null;
  capture_type?: string | null;
  creation_tool_info?: InstagramReelCreativeConfigCreationToolInfo[] | null;
  effect_configs?: unknown | null;
  effect_preview?: unknown | null;
  face_effect_id?: unknown | null;
  gen_ai_tool_info?: unknown | null;
}

export interface InstagramReelCreativeConfigCreationToolInfo {
  appearance_effect?: number | null;
  camera_tool?: number | null;
  color_filters?: string | null;
  duration_selector_seconds?: number | null;
  magic_cut_end_time?: number | null;
  magic_cut_start_time?: number | null;
  speed_selector?: number | null;
  timer_selector_seconds?: number | null;
}

export interface InstagramReelLocation {
  address?: string | null;
  city?: string | null;
  external_source?: string | null;
  facebook_places_id?: number | string | null;
  has_viewer_saved?: boolean | null;
  lat?: number | null;
  lng?: number | null;
  name?: string | null;
  pk?: number | string | null;
  short_name?: string | null;
}

export interface InstagramReelUsertags {
  in?: InstagramReelUsertagsIn[] | null;
}

export interface InstagramReelUsertagsIn {
  position?: number[] | null;
  show_category_of_user?: boolean | null;
  user?: InstagramReelUsertagsInUser | null;
}

export interface InstagramReelUsertagsInUser {
  full_name?: string | null;
  has_onboarded_to_text_post_app?: unknown | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramResource {
  config_height?: number | null;
  config_width?: number | null;
  src?: string | null;
}

export interface InstagramScrubberSpritesheetInfoCandidates {
  default?: InstagramDefault | null;
}

export interface InstagramSharingFrictionInfo {
  bloks_app_url?: unknown | null;
  sharing_friction_payload?: unknown | null;
  should_have_sharing_friction?: boolean | null;
}

export interface InstagramSnippetsOverlay {
  element?: InstagramSnippetsOverlayElement | null;
  end_time_ms?: number | null;
  height?: number | null;
  rotation?: number | null;
  start_time_ms?: number | null;
  width?: number | null;
  x?: number | null;
  y?: number | null;
  z?: number | null;
}

export interface InstagramSnippetsOverlayElement {
  element_id?: number | string | null;
  element_type?: string | null;
}

export interface InstagramSponsor {
  follower_count?: number | null;
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramSponsorTag {
  is_pending?: boolean | null;
  permission?: boolean | null;
  sponsor?: InstagramSponsor | null;
  sponsor_id?: unknown | null;
  username?: unknown | null;
}

export interface InstagramSpotifyTrackMetadata {
  spotify_listen_uri?: string | null;
  spotify_track_id?: string | null;
}

export interface InstagramUpstreamBiographyWithEntities {
  entities?: unknown[] | null;
}

export interface InstagramUpstreamCoverMedia {
  crop_rect?: unknown | null;
  cropped_image_version?: InstagramUpstreamCroppedImageVersion | null;
  full_image_version?: unknown | null;
  media_id?: number | string | null;
  upload_id?: unknown | null;
}

export interface InstagramUpstreamCroppedImageVersion {
  height?: number | null;
  scans_profile?: string | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramUpstreamHighlightReelItem {
  archive_story_deletion_ts?: number | null;
  boost_unavailable_identifier?: unknown | null;
  boost_unavailable_reason?: unknown | null;
  boost_unavailable_reason_v2?: unknown[] | null;
  can_extend_expiration?: unknown | null;
  can_mention_back?: boolean | null;
  can_play_spotify_audio?: boolean | null;
  can_reply?: boolean | null;
  can_reshare?: boolean | null;
  can_see_insights_as_brand?: boolean | null;
  can_send_prompt?: boolean | null;
  can_viewer_save?: boolean | null;
  caption?: unknown | null;
  caption_is_edited?: boolean | null;
  client_cache_key?: string | null;
  coauthor_producers?: InstagramUpstreamUserFeedItemCoauthorProducer[] | null;
  code?: string | null;
  creative_config?: unknown | null;
  cutout_sticker_info?: unknown[] | null;
  deleted_reason?: number | null;
  device_timestamp?: number | null;
  fbid?: number | string | null;
  filter_type?: number | null;
  has_audio?: boolean | null;
  has_privately_liked?: boolean | null;
  has_translation?: boolean | null;
  hide_view_all_comment_entrypoint?: boolean | null;
  id?: number | string | null;
  ig_media_sharing_disabled?: boolean | null;
  image_versions2?: InstagramUpstreamHighlightReelItemImageVersions2 | null;
  integrity_review_decision?: string | null;
  is_affiliate_commission_eligible?: boolean | null;
  is_arirang_prize?: boolean | null;
  is_dash_eligible?: number | null;
  is_first_take?: boolean | null;
  is_from_ayt_clips_inspiration?: boolean | null;
  is_from_discovery_surface?: boolean | null;
  is_music_collection_story?: boolean | null;
  is_open_to_public_submission?: boolean | null;
  is_organic_product_tagging_eligible?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_photo_mash_story?: boolean | null;
  is_quicksnap_recap?: boolean | null;
  is_reel_media?: boolean | null;
  is_reshare_of_text_post_app_media_in_ig?: boolean | null;
  is_rollcall_v2?: boolean | null;
  is_story_edited?: boolean | null;
  is_story_image_with_music?: boolean | null;
  is_superlative?: boolean | null;
  is_tagged_media_shared_to_viewer_profile_grid?: boolean | null;
  is_terminal_video_segment?: boolean | null;
  is_visual_reply_commenter_notice_enabled?: boolean | null;
  media_attributions_data?: unknown[] | null;
  media_overlay_info?: unknown | null;
  media_type?: number | null;
  media_ui_attributions_data_v2?: unknown[] | null;
  mezql_token?: string | null;
  music_metadata?: unknown | null;
  number_of_qualities?: number | null;
  organic_tracking_token?: string | null;
  original_height?: number | null;
  original_media_type?: number | null;
  original_width?: number | null;
  owner?: InstagramUpstreamOwner | null;
  pk?: number | string | null;
  product_type?: string | null;
  reel_mentions?: InstagramUpstreamReelMention[] | null;
  sharing_friction_info?: InstagramUpstreamSharingFrictionInfo | null;
  shop_routing_user_id?: unknown | null;
  should_request_ads?: boolean | null;
  should_show_author_pog_for_tagged_media_shared_to_profile_grid?: boolean | null;
  show_one_tap_fb_share_tooltip?: boolean | null;
  story_highlight_reshare_stickers?: unknown[] | null;
  strong_id__?: string | null;
  subscribe_cta_visible?: boolean | null;
  supports_reel_reactions?: boolean | null;
  taken_at?: number | null;
  trending_content_info?: unknown[] | null;
  user?: InstagramUpstreamOwner | null;
  video_dash_manifest?: string | null;
  video_duration?: number | null;
  video_versions?: InstagramUpstreamMediaVideoVersion[] | null;
  voice_replies_enabled?: boolean | null;
  wearable_shared_media_resolutions?: unknown[] | null;
  wearables_creator_tools_info?: unknown[] | null;
}

export interface InstagramUpstreamHighlightReelItemImageVersions2 {
  candidates?: InstagramUpstreamHighlightReelItemImageVersions2Candidate[] | null;
}

export interface InstagramUpstreamHighlightReelItemImageVersions2Candidate {
  estimated_scans_sizes?: number[] | null;
  height?: number | null;
  is_spatial_image?: boolean | null;
  scans_profile?: unknown | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramUpstreamHighlightReelUser {
  account_badges?: unknown[] | null;
  full_name?: string | null;
  id?: number | string | null;
  interop_messaging_user_fbid?: number | string | null;
  is_private?: boolean | null;
  is_screenshot_blocking_enabled?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  transparency_product_enabled?: boolean | null;
  username?: string | null;
}

export interface InstagramUpstreamIfNotGatedLoggedOutImageVersions2Candidate {
  height?: number | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramUpstreamMediaVideoVersion {
  bandwidth?: number | null;
  fallback?: unknown | null;
  height?: number | null;
  id?: number | string | null;
  progressive_identifier?: string | null;
  type?: number | null;
  url?: string | null;
  url_expiration_timestamp_us?: unknown | null;
  width?: number | null;
}

export interface InstagramUpstreamMetaVerifiedBenefitsInfo {
  active_meta_verified_benefits?: unknown[] | null;
}

export interface InstagramUpstreamOwner {
  account_badges?: unknown[] | null;
  account_type?: number | null;
  eligible_for_text_app_activation_badge?: boolean | null;
  fbid_v2?: number | string | null;
  full_name?: string | null;
  hd_profile_pic_url_info?: InstagramUpstreamIfNotGatedLoggedOutImageVersions2Candidate | null;
  hd_profile_pic_versions?: InstagramUpstreamIfNotGatedLoggedOutImageVersions2Candidate[] | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUpstreamProfilePageUserBioLink {
  creation_source?: string | null;
  image_url?: string | null;
  is_pinned?: boolean | null;
  link_id?: string | null;
  link_type?: string | null;
  lynx_url?: string | null;
  media_accent_color_hex?: string | null;
  media_type?: string | null;
  title?: string | null;
  url?: string | null;
}

export interface InstagramUpstreamReelMention {
  custom_text_color?: unknown | null;
  display_type?: string | null;
  end_time_ms?: number | null;
  height?: number | null;
  id?: number | string | null;
  is_fb_sticker?: number | null;
  is_hidden?: number | null;
  is_pinned?: number | null;
  is_sticker?: number | null;
  rotation?: number | null;
  start_time_ms?: number | null;
  user?: InstagramUpstreamReelMentionUser | null;
  width?: number | null;
  x?: number | null;
  y?: number | null;
  z?: number | null;
}

export interface InstagramUpstreamReelMentionUser {
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUpstreamSharingFrictionInfo {
  bloks_app_url?: unknown | null;
  sharing_friction_payload?: unknown | null;
  should_have_sharing_friction?: boolean | null;
}

export interface InstagramUpstreamUserFeedItemCoauthorProducer {
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUserPostsPageItem {
  accessibility_caption?: string | null;
  ai_label_info?: InstagramItemAILabelInfo | null;
  are_remixes_crosspostable?: boolean | null;
  boost_unavailable_identifier?: unknown | null;
  boost_unavailable_reason?: unknown | null;
  boost_unavailable_reason_v2?: unknown[] | null;
  can_modify_carousel?: boolean | null;
  can_see_insights_as_brand?: boolean | null;
  can_viewer_reshare?: boolean | null;
  can_viewer_save?: boolean | null;
  caption?: InstagramUserPostsPageItemCaption | null;
  caption_is_edited?: boolean | null;
  carousel_media?: InstagramCarouselMedia[] | null;
  carousel_media_count?: number | null;
  carousel_media_ids?: string[] | null;
  carousel_media_pending_post_count?: number | null;
  client_cache_key?: string | null;
  clips_metadata?: InstagramNodeClipsMetadata | null;
  clips_tab_pinned_user_ids?: unknown[] | null;
  coauthor_producer_can_see_organic_insights?: boolean | null;
  coauthor_producers?: InstagramUserPostsPageItemCoauthorProducer[] | null;
  code?: string | null;
  collaborator_edit_eligibility?: boolean | null;
  comment_count?: number | null;
  comment_inform_treatment?: InstagramCommentInformTreatment | null;
  comment_likes_enabled?: boolean | null;
  commenting_disabled_for_viewer?: boolean | null;
  comments_disabled?: boolean | null;
  commerce_integrity_review_decision?: string | null;
  created_at?: string | null;
  creative_config?: unknown | null;
  creator_is_in_premium_reactions_alpha?: unknown | null;
  cutout_sticker_info?: unknown[] | null;
  deleted_reason?: number | null;
  device_timestamp?: number | null;
  disable_caption_and_comment?: boolean | null;
  display_uri?: string | null;
  eligible_insights_entrypoints?: string | null;
  enable_media_notes_production?: boolean | null;
  fb_user_tags?: InstagramFbUserTags | null;
  fbid?: number | string | null;
  featured_products?: unknown[] | null;
  filter_type?: number | null;
  fundraiser_tag?: InstagramFundraiserTag | null;
  has_audio?: boolean | null;
  has_delayed_metadata?: boolean | null;
  has_liked?: boolean | null;
  has_privately_liked?: boolean | null;
  has_shared_to_fb?: number | null;
  has_tagged_users?: boolean | null;
  has_views_fetching?: boolean | null;
  has_views_fetching_on_search_grid?: boolean | null;
  hidden_likes_string_variant?: number | null;
  hide_stickers_for_original_language?: boolean | null;
  hide_view_all_comment_entrypoint?: boolean | null;
  id?: number | string | null;
  ig_media_sharing_disabled?: boolean | null;
  ig_play_count?: number | null;
  igbio_product?: unknown | null;
  image_versions2?: InstagramUserPostsPageItemImageVersions2 | null;
  integrity_review_decision?: string | null;
  invited_coauthor_producers?: unknown[] | null;
  is_affiliate_commission_eligible?: boolean | null;
  is_comments_gif_composer_enabled?: boolean | null;
  is_cutout_sticker_allowed?: boolean | null;
  is_dash_eligible?: number | null;
  is_eligible_content_for_post_roll_ad?: boolean | null;
  is_eligible_for_autodub?: boolean | null;
  is_eligible_for_autodub_upsell?: boolean | null;
  is_eligible_for_organic_eager_refresh?: boolean | null;
  is_eligible_for_poe?: boolean | null;
  is_eligible_for_poe_premium?: boolean | null;
  is_in_profile_grid?: boolean | null;
  is_meta_ai_invocation_blocked_by_author?: boolean | null;
  is_open_to_public_submission?: boolean | null;
  is_organic_product_tagging_eligible?: boolean | null;
  is_paid_partnership?: boolean | null;
  is_photo_comments_composer_enabled_for_author?: boolean | null;
  is_post_live_clips_media?: boolean | null;
  is_quiet_post?: boolean | null;
  is_reshare_of_text_post_app_media_in_ig?: boolean | null;
  is_reuse_allowed?: boolean | null;
  is_short_drama?: boolean | null;
  is_social_ufi_disabled?: boolean | null;
  is_tagged_media_shared_to_viewer_profile_grid?: boolean | null;
  is_third_party_downloads_eligible?: boolean | null;
  is_visual_reply_commenter_notice_enabled?: boolean | null;
  lat?: number | null;
  like_and_view_counts_disabled?: boolean | null;
  like_count?: number | null;
  lng?: number | null;
  location?: InstagramItemLocation | null;
  locations?: unknown[] | null;
  mashup_info?: InstagramItemMashupInfo | null;
  media_attributions_data?: unknown[] | null;
  media_cropping_info?: InstagramMediaCroppingInfo | null;
  media_level_comment_controls?: string | null;
  media_overlay_info?: unknown | null;
  media_reposter_bottomsheet_enabled?: boolean | null;
  media_type?: number | null;
  media_ui_attributions_data?: unknown[] | null;
  media_ui_attributions_data_v2?: unknown[] | null;
  meta_ai_suggested_prompts?: unknown[] | null;
  mezql_token?: string | null;
  music_metadata?: unknown | null;
  number_of_qualities?: number | null;
  open_carousel_show_follow_button?: boolean | null;
  open_carousel_submission_state?: string | null;
  organic_tracking_token?: string | null;
  original_height?: number | null;
  original_lang_for_translations?: string | null;
  original_media_has_visual_reply_media?: boolean | null;
  original_width?: number | null;
  owner?: InstagramItemOwner | null;
  photo_of_you?: boolean | null;
  pk?: number | string | null;
  play_count?: number | null;
  premium_reaction_count?: number | null;
  product_suggestions?: unknown[] | null;
  product_type?: string | null;
  profile_grid_control_enabled?: boolean | null;
  profile_grid_thumbnail_fitting_style?: string | null;
  related_ads_pivots_media_info?: string | null;
  share_count_disabled?: boolean | null;
  sharing_friction_info?: InstagramSharingFrictionInfo | null;
  shop_routing_user_id?: unknown | null;
  should_request_ads?: boolean | null;
  should_show_author_pog_for_tagged_media_shared_to_profile_grid?: boolean | null;
  sponsor_tags?: InstagramSponsorTag[] | null;
  strong_id__?: string | null;
  subscribe_cta_visible?: boolean | null;
  subtype_name_for_REST__?: string | null;
  taken_at?: number | null;
  tappable_elements?: unknown[] | null;
  timeline_pinned_user_ids?: (number | string)[] | null;
  translated_langs_for_autodub?: unknown[] | null;
  tya_media_related_topics?: unknown[] | null;
  url?: string | null;
  user?: InstagramItemOwner | null;
  usertags?: InstagramCarouselMediaUsertags | null;
  video_codec?: string | null;
  video_dash_manifest?: string | null;
  video_duration?: number | null;
  video_sticker_locales?: string[] | null;
  video_url?: string | null;
  video_versions?: InstagramCarouselMediaVideoVersion[] | null;
}

export interface InstagramUserPostsPageItemCaption {
  bit_flags?: number | null;
  content_type?: string | null;
  created_at?: number | null;
  created_at_utc?: number | null;
  did_report_as_spam?: boolean | null;
  is_covered?: boolean | null;
  is_ranked_comment?: boolean | null;
  media_id?: number | string | null;
  pk?: number | string | null;
  private_reply_status?: number | null;
  share_enabled?: boolean | null;
  status?: string | null;
  strong_id__?: string | null;
  text?: string | null;
  text_translation?: string | null;
  type?: number | null;
  user?: InstagramUserPostsPageItemCaptionUser | null;
  user_id?: number | string | null;
}

export interface InstagramUserPostsPageItemCaptionUser {
  fbid_v2?: number | string | null;
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUserPostsPageItemCoauthorProducer {
  full_name?: string | null;
  id?: number | string | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUserPostsPageItemImageVersions2 {
  additional_candidates?: InstagramUserPostsPageItemImageVersions2AdditionalCandidate | null;
  candidates?: InstagramUserPostsPageItemImageVersions2Candidate[] | null;
  scrubber_spritesheet_info_candidates?: InstagramScrubberSpritesheetInfoCandidates | null;
}

export interface InstagramUserPostsPageItemImageVersions2AdditionalCandidate {
  first_frame?: InstagramMediaImageVersions2Candidate | null;
  igtv_first_frame?: InstagramMediaImageVersions2Candidate | null;
  smart_frame?: unknown | null;
}

export interface InstagramUserPostsPageItemImageVersions2Candidate {
  estimated_scans_sizes?: number[] | null;
  height?: number | null;
  is_spatial_image?: boolean | null;
  scans_profile?: string | null;
  url?: string | null;
  width?: number | null;
}

export interface InstagramUserPostsPageUser {
  full_name?: string | null;
  id?: number | string | null;
  is_active_on_text_post_app?: boolean | null;
  is_private?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  pk_id?: string | null;
  profile_grid_display_type?: string | null;
  profile_pic_id?: string | null;
  profile_pic_url?: string | null;
  strong_id__?: string | null;
  username?: string | null;
}

export interface InstagramUserPostsResponse {
  auto_load_more_enabled?: boolean | null;
  items: InstagramUserPostsPageItem[] | null;
  more_available?: boolean | null;
  next_max_id?: string | null;
  num_results?: number | null;
  pinned_profile_grid_items_ids?: unknown | null;
  profile_grid_items?: unknown | null;
  profile_grid_items_cursor?: unknown | null;
  special_empty_state?: unknown | null;
  status?: string | null;
  user?: InstagramUserPostsPageUser | null;
}

export interface InstagramUserReelsPageItem {
  caption?: InstagramMediaCaption | null;
  code?: string | null;
  comment_count?: number | null;
  created_at?: string | null;
  display_uri?: string | null;
  id?: number | string | null;
  ig_play_count?: number | null;
  image_versions2?: InstagramMediaImageVersions2 | null;
  like_count?: number | null;
  media?: InstagramItemMedia | null;
  play_count?: number | null;
  taken_at?: number | null;
  url?: string | null;
  user?: InstagramMediaUser | null;
}

export interface InstagramUserReelsResponse {
  items: InstagramUserReelsPageItem[] | null;
  max_id?: string | null;
  paging_info?: InstagramPagingInfo | null;
  status?: string | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadata {
  music_info?: InstagramXdtShortcodeMediaClipsMetadataMusicInfo | null;
  original_sound_info?: InstagramXdtShortcodeMediaClipsMetadataOriginalSoundInfo | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadataMusicInfo {
  music_asset_info?: InstagramXdtShortcodeMediaClipsMetadataMusicInfoMusicAssetInfo | null;
  music_consumption_info?: InstagramXdtShortcodeMediaClipsMetadataMusicInfoMusicConsumptionInfo | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadataMusicInfoMusicAssetInfo {
  audio_cluster_id?: string | null;
  display_artist?: string | null;
  is_explicit?: boolean | null;
  title?: string | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadataMusicInfoMusicConsumptionInfo {
  audio_filter_infos?: unknown[] | null;
  is_trending_in_clips?: boolean | null;
  should_mute_audio?: boolean | null;
  should_mute_audio_reason?: string | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadataOriginalSoundInfo {
  audio_asset_id?: number | string | null;
  audio_filter_infos?: unknown | null;
  consumption_info?: InstagramXdtShortcodeMediaClipsMetadataOriginalSoundInfoConsumptionInfo | null;
  ig_artist?: InstagramIgArtist | null;
  is_explicit?: boolean | null;
  original_audio_title?: string | null;
  should_mute_audio?: boolean | null;
}

export interface InstagramXdtShortcodeMediaClipsMetadataOriginalSoundInfoConsumptionInfo {
  is_trending_in_clips?: boolean | null;
  should_mute_audio_reason?: string | null;
}

export interface InstagramXdtShortcodeMediaCoauthorProducer {
  __typename?: string | null;
  full_name?: string | null;
  id?: number | string | null;
  is_unpublished?: boolean | null;
  is_verified?: boolean | null;
  pk?: number | string | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export interface InstagramXdtShortcodeMediaEdgeMediaToTaggedUser {
  edges?: InstagramXdtShortcodeMediaEdgeMediaToTaggedUserEdge[] | null;
}

export interface InstagramXdtShortcodeMediaEdgeMediaToTaggedUserEdge {
  node?: InstagramXdtShortcodeMediaEdgeMediaToTaggedUserEdgeNode | null;
}

export interface InstagramXdtShortcodeMediaEdgeMediaToTaggedUserEdgeNode {
  id?: number | string | null;
  user?: InstagramXdtShortcodeMediaOwner | null;
  x?: number | null;
  y?: number | null;
}

export interface InstagramXdtShortcodeMediaEdgeSidecarToChildren {
  edges?: InstagramXdtShortcodeMediaEdgeSidecarToChildrenEdge[] | null;
}

export interface InstagramXdtShortcodeMediaEdgeSidecarToChildrenEdge {
  node?: InstagramXdtShortcodeMediaEdgeSidecarToChildrenEdgeNode | null;
}

export interface InstagramXdtShortcodeMediaEdgeSidecarToChildrenEdgeNode {
  __typename?: string | null;
  dimensions?: InstagramDimensions | null;
  display_url?: string | null;
  id?: number | string | null;
  is_video?: boolean | null;
  shortcode?: string | null;
  video_url?: string | null;
}

export interface InstagramXdtShortcodeMediaLocation {
  __typename?: string | null;
  lat?: number | null;
  lng?: number | null;
  name?: string | null;
  pk?: number | string | null;
  profile_pic_url?: unknown | null;
}

export interface InstagramXdtShortcodeMediaOwner {
  full_name?: string | null;
  id?: number | string | null;
  is_verified?: boolean | null;
  profile_pic_url?: string | null;
  username?: string | null;
}

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";

export interface SearchPopularParams {
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: string | null;
  /** The topic to look up, such as basketball. */
  query: string;
}
