// Generated by generate-client from spec/openapi.json. Do not edit.

import type { BaseClient } from '../../base.js';
import type { GetCalendarRequest, GetDetailsRequest, GetPriceRequest, GetReviewsRequest, ParsedAutocompleteResponse, ParsedCalendarResponse, ParsedDetailsResponse, ParsedPriceResponse, ParsedReviewsResponse, ParsedSearchResponse, SearchLocationsParams, SearchRequest } from './types.js';

export class AirbnbClient {
  constructor(private readonly base: BaseClient) {}

  /** Check the availability of an Airbnb listing by month. Costs 1 credit. */
  async getCalendar(body: GetCalendarRequest): Promise<ParsedCalendarResponse> {
    return this.base.post<ParsedCalendarResponse>('/api/v1/airbnb/calendar', body);
  }

  /** Get details about an Airbnb listing. Costs 5 credits. */
  async getDetails(body: GetDetailsRequest): Promise<ParsedDetailsResponse> {
    return this.base.post<ParsedDetailsResponse>('/api/v1/airbnb/details', body);
  }

  /** Find Airbnb locations matching a text query. Costs 1 credit. */
  async searchLocations(params: SearchLocationsParams): Promise<ParsedAutocompleteResponse> {
    return this.base.get<ParsedAutocompleteResponse>('/api/v1/airbnb/locations', { ...params });
  }

  /** Get the price for an Airbnb listing over a date range. Costs 2 credits. */
  async getPrice(body: GetPriceRequest): Promise<ParsedPriceResponse> {
    return this.base.post<ParsedPriceResponse>('/api/v1/airbnb/price', body);
  }

  /** Get reviews for an Airbnb listing. Costs 2 credits. */
  async getReviews(body: GetReviewsRequest): Promise<ParsedReviewsResponse> {
    return this.base.post<ParsedReviewsResponse>('/api/v1/airbnb/reviews', body);
  }

  /** Search for Airbnb listings within a radius, by place ID, or by text query. Costs 5 credits. */
  async search(body: SearchRequest): Promise<ParsedSearchResponse> {
    return this.base.post<ParsedSearchResponse>('/api/v1/airbnb/search', body);
  }
}
