// Generated by generate-client from spec/openapi.json. Do not edit.

import type { BaseClient } from '../../base.js';
import type { GetEvmTokenSecurityParams, GetEvmTokenSecurityResponse, GetSolanaTokenSecurityParams, GetSolanaTokenSecurityResponse } from './types.js';

export class GoplusClient {
  constructor(private readonly base: BaseClient) {}

  /** GoPlus token security for one EVM token: honeypot, tax, owner and mint flags, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` (1 complete, 2 partial, 3 no contract code) and `result`, which is keyed by the lowercased address. Powered by GoPlus Security. Costs 3 credits. */
  async getEvmTokenSecurity(params: GetEvmTokenSecurityParams): Promise<GetEvmTokenSecurityResponse> {
    const { chain_id, address } = params;
    return this.base.get<GetEvmTokenSecurityResponse>(`/api/v1/goplus/evm/${encodeURIComponent(chain_id)}/tokens/${encodeURIComponent(address)}/security`);
  }

  /** GoPlus token security for one Solana mint: mint, freeze, close and metadata authorities, Token-2022 transfer fee and hook, top holders and liquidity. The GoPlus envelope is returned unchanged; read `code` and `result`, which is keyed by the mint. Powered by GoPlus Security. Costs 3 credits. */
  async getSolanaTokenSecurity(params: GetSolanaTokenSecurityParams): Promise<GetSolanaTokenSecurityResponse> {
    const { mint } = params;
    return this.base.get<GetSolanaTokenSecurityResponse>(`/api/v1/goplus/solana/tokens/${encodeURIComponent(mint)}/security`);
  }
}
