// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
  upgrade_url?: string | null;
}

export interface GetEvmTokenSecurityParams {
  /** Token contract address: 0x plus 40 hex characters, any case. */
  address: string;
  /** EVM chain id: 1 Ethereum, 56 BNB Chain, 8453 Base, 4663 Robinhood Chain. */
  chain_id: GoplusChainId;
}

export interface GetEvmTokenSecurityResponse {
  code?: number;
  message?: string;
  result?: Record<string, GoplusEvmTokenSecurity>;
}

export interface GetSolanaTokenSecurityParams {
  /** Token mint address, base58. */
  mint: string;
}

export interface GetSolanaTokenSecurityResponse {
  code?: number;
  message?: string;
  result?: Record<string, GoplusSolanaTokenSecurity>;
}

export type GoplusChainId = "1" | "56" | "8453" | "4663";

export interface GoplusEvmCexListing {
  cex_list?: string[];
  listed?: string;
}

export interface GoplusEvmDex {
  liquidity?: string;
  liquidity_type?: string;
  name?: string;
  pair?: string;
  pool_fee?: string;
  pool_manager?: string;
}

export interface GoplusEvmHolder {
  address?: string;
  balance?: string;
  is_contract?: number;
  is_locked?: number;
  percent?: string;
  tag?: string;
}

export interface GoplusEvmLpHolder {
  NFT_list?: GoplusEvmLpNft[] | null;
  address?: string;
  balance?: string;
  is_contract?: number;
  is_locked?: number;
  percent?: string;
  tag?: string;
  value?: string;
}

export interface GoplusEvmLpNft {
  NFT_id?: string;
  NFT_percentage?: string;
  amount?: string;
  in_effect?: string;
  value?: string;
}

export interface GoplusEvmTokenSecurity {
  anti_whale_modifiable?: string;
  buy_tax?: string;
  can_take_back_ownership?: string;
  cannot_buy?: string;
  cannot_sell_all?: string;
  creator_address?: string;
  creator_balance?: string;
  creator_percent?: string;
  dex?: GoplusEvmDex[];
  external_call?: string;
  hidden_owner?: string;
  holder_count?: string;
  holders?: GoplusEvmHolder[];
  honeypot_with_same_creator?: string;
  is_anti_whale?: string;
  is_blacklisted?: string;
  is_honeypot?: string;
  is_in_cex?: GoplusEvmCexListing;
  is_in_dex?: string;
  is_mintable?: string;
  is_open_source?: string;
  is_proxy?: string;
  is_whitelisted?: string;
  lp_holder_count?: string;
  lp_holders?: GoplusEvmLpHolder[];
  lp_total_supply?: string;
  owner_address?: string;
  owner_balance?: string;
  owner_change_balance?: string;
  owner_percent?: string;
  personal_slippage_modifiable?: string;
  selfdestruct?: string;
  sell_tax?: string;
  slippage_modifiable?: string;
  token_name?: string;
  token_symbol?: string;
  total_supply?: string;
  trading_cooldown?: string;
  transfer_pausable?: string;
  transfer_tax?: string;
}

export interface GoplusSolanaAddress {
  address?: string;
  malicious_address?: number;
}

export interface GoplusSolanaAuthorityStatus {
  authority?: GoplusSolanaAddress[];
  status?: string;
}

export interface GoplusSolanaDex {
  burn_percent?: number | null;
  day?: GoplusSolanaDexWindow;
  dex_name?: string;
  fee_rate?: string;
  id?: string;
  lp_amount?: string | null;
  month?: GoplusSolanaDexWindow;
  open_time?: string;
  price?: string;
  tvl?: string;
  type?: string;
  week?: GoplusSolanaDexWindow;
}

export interface GoplusSolanaDexWindow {
  price_max?: string;
  price_min?: string;
  volume?: string;
}

export interface GoplusSolanaFeeRate {
  fee_rate?: string;
  maximum_fee?: string;
}

export interface GoplusSolanaHolder {
  account?: string;
  balance?: string;
  is_locked?: number;
  locked_detail?: unknown[];
  percent?: string;
  tag?: string;
  token_account?: string;
}

export interface GoplusSolanaMetadata {
  description?: string;
  name?: string;
  symbol?: string;
  uri?: string;
}

export interface GoplusSolanaMetadataMutable {
  metadata_upgrade_authority?: GoplusSolanaAddress[];
  status?: string;
}

export interface GoplusSolanaScheduledFeeRate {
  epoch?: string;
  fee_rate?: string;
  maximum_fee?: string;
}

export interface GoplusSolanaTokenSecurity {
  balance_mutable_authority?: GoplusSolanaAuthorityStatus;
  closable?: GoplusSolanaAuthorityStatus;
  creators?: unknown[];
  default_account_state?: string;
  default_account_state_upgradable?: GoplusSolanaAuthorityStatus;
  dex?: GoplusSolanaDex[];
  freezable?: GoplusSolanaAuthorityStatus;
  holder_count?: string;
  holders?: GoplusSolanaHolder[];
  lp_holders?: GoplusSolanaHolder[];
  metadata?: GoplusSolanaMetadata;
  metadata_mutable?: GoplusSolanaMetadataMutable;
  mintable?: GoplusSolanaAuthorityStatus;
  non_transferable?: string;
  total_supply?: string;
  transfer_fee?: GoplusSolanaTransferFee;
  transfer_fee_upgradable?: GoplusSolanaAuthorityStatus;
  transfer_hook?: GoplusSolanaAddress[];
  transfer_hook_upgradable?: GoplusSolanaAuthorityStatus;
  trusted_token?: number;
}

export interface GoplusSolanaTransferFee {
  current_fee_rate?: GoplusSolanaFeeRate;
  scheduled_fee_rate?: GoplusSolanaScheduledFeeRate[];
}

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";
