// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ActivityRankInfoParams {
  chain: Chain;
}

export interface AddressListRequest {
  addresses: string[];
}

export interface AggedTokenTradesParams {
  chain: Chain;
  /** Bucket size. */
  period?: AggedTradePeriod;
  /** Wallet cohort to filter on. Omit for all wallets. */
  tag?: AggedTradeTag | null;
  token_address: string;
}

export interface AggedTokenTransfersParams {
  chain: Chain;
  /** Bucket size. */
  period?: AggedTradePeriod;
  token_address: string;
  /** Wallet whose transfers are aggregated. */
  wallet_address: string;
}

export interface AggedTrade {
  avatar: string;
  buy_amount: string;
  buy_count: number;
  buy_quote_address: string;
  buy_quote_amount: string;
  buy_usd_amount: string;
  claim_count: number;
  claim_quote_address: string;
  claim_quote_amount: string;
  ens: string;
  is_boost: boolean;
  is_close: boolean;
  is_open: boolean;
  max_seq_index: string;
  name: string;
  nickname: string;
  platform: string;
  platform_avatar: string;
  platform_username: string;
  pump_social_claim_count: number;
  pump_social_claim_quote_address: string;
  pump_social_claim_quote_amount: string;
  sell_amount: string;
  sell_count: number;
  sell_quote_address: string;
  sell_quote_amount: string;
  sell_usd_amount: string;
  twitter_name: string;
  twitter_username: string;
  wallet_address: string;
}

export interface AggedTradeBucket {
  timestamp: number;
  trades: AggedTrade[];
}

export type AggedTradePeriod = "1m" | "5m" | "1h" | "4h";

export type AggedTradeTag = "dev_team" | "smart_degen" | "insider" | "sniper" | "bundler" | "fresh_wallet" | "bluechip_owner" | "renowned" | "rat_trader";

export interface AggedTransfer {
  max_seq_index: string;
  transfer_in_amount: string;
  transfer_in_avg_price: string;
  transfer_in_count: number;
  transfer_in_usd_amount: string;
  transfer_out_amount: string;
  transfer_out_avg_price: string;
  transfer_out_count: number;
  transfer_out_usd_amount: string;
  wallet_address: string;
}

export interface AggedTransferBucket {
  timestamp: number;
  transfers: AggedTransfer[];
}

export interface BluechipRankParams {
  chain: Chain;
  /** Security screens applied before ranking. */
  filters?: TokenFilter[] | null;
  /** Ranking window. */
  interval?: TrendingInterval;
  /** Maximum tokens to return. */
  limit?: number;
}

export interface BluechipSecurityInfo {
  burn_ratio: string;
  burn_status: string;
  dev_token_burn_amount: string;
  dev_token_burn_ratio: string;
  is_show_alert: boolean;
  renounced_freeze_account?: number;
  renounced_mint?: number;
  top_10_holder_rate: string;
}

export interface BluechipToken {
  address: string;
  at_least_one_link: boolean;
  bluechip_rate: string;
  bot_degen_count: number;
  bot_degen_rate: number;
  bundler_rate: string;
  buys: number;
  chain: string;
  creator: string;
  creator_token_status: string;
  cto_flag: number;
  dev_team_hold_rate: number;
  dexscr_ad: number;
  dexscr_ad_ts: number;
  dexscr_boost_fee: number;
  dexscr_boost_ts: number;
  dexscr_trending_bar: number;
  dexscr_trending_bar_ts: number;
  dexscr_update_link: number;
  dexscr_update_link_ts: number;
  entrapment_ratio: string;
  history_highest_market_cap: number;
  holder_count: number;
  hot_level: number;
  image_dup: string;
  is_show_alert: boolean;
  is_wash_trading: boolean;
  launchpad: string;
  launchpad_platform: string;
  launchpad_status: number;
  liquidity: string;
  logo: string;
  market_cap: string;
  open_timestamp: number;
  price: string;
  price_change_percent_1h: string;
  price_change_percent_1m: string;
  price_change_percent_5m: string;
  rat_trader_amount_rate: string;
  security_info: BluechipSecurityInfo;
  sells: number;
  smart_buys_24h: number;
  smart_sells_24h: number;
  swaps: number;
  symbol: string;
  telegram_dup: number;
  token_links: BluechipTokenLinks;
  top70_sniper_hold_rate: number;
  twitter_change_flag: number;
  twitter_dup: number;
  twitter_rename_count: number;
  volume: string;
  website_dup: number;
}

export interface BluechipTokenLinks {
  address: string;
  bitbucket: string;
  description: string;
  discord: string;
  facebook: string;
  fracaster: unknown | null;
  geckoterminal: string;
  github: string;
  gmgn: string;
  instagram: string;
  linkedin: string;
  medium: string;
  reddit: string;
  telegram: string;
  tiktok: string;
  twitter_username: string;
  verify_status: number;
  website: string;
  youtube: string;
}

export type Chain = "sol" | "eth" | "bsc" | "base" | "tron" | "monad" | "megaeth" | "hyperevm" | "robinhood" | "arbitrum" | "arc" | "stable" | "xlayer";

export interface DevCreatedToken {
  biggest_pool: string;
  bundler_rate: number;
  chain: string;
  coin_creator_fee: number;
  coin_creator_fee_token_address: string;
  create_timestamp: number;
  cto_flag: boolean;
  dexscr_ad: boolean;
  dexscr_update_link: boolean;
  holders: number;
  is_open: boolean;
  is_pump: boolean;
  launchpad_platform: string;
  liquidity_less_4k: boolean;
  logo: string;
  marcket_cap: string;
  market_cap: string;
  pool_liquidity: string;
  swap_1h: number;
  symbol: string;
  token_address: string;
  token_ath_mc: string;
  total_fee: string;
  twitter_name_change_history: string[];
  volume_1h: string;
}

export interface DevCreatedTokensParams {
  chain: Chain;
  wallet_address: string;
}

export interface DevCreatorAthInfo {
  ath_mc: string;
  ath_token: string;
  creator: string;
  token_logo: string;
  token_name: string;
  token_symbol: string;
}

export interface DexAggregationResult {
  buyCount: number;
  buyCountChangeRate: number;
  buyVolume: number;
  buyVolumeChangeRate: number;
  chain: string;
  dexName: string;
  sellCount: number;
  sellCountChangeRate: number;
  sellVolume: number;
  sellVolumeChangeRate: number;
  tokenStatsCreated: number;
  tokenStatsCreatedChangeRate: number;
  tokenStatsMigrations: number;
  tokenStatsMigrationsChangeRate: number;
  tradeCount: number;
  tradeCountChangeRate: number;
  tradeVolume: number;
  tradeVolumeChangeRate: number;
  traderCount: number;
  traderCountChangeRate: number;
}

export interface DexTradesPollingParams {
  chain: Chain;
  window?: TimeWindow;
}

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
}

export interface FeeDistributionCharity {
  id: string;
  logo: string;
  name: string;
  slug: string;
  website: string;
  weight: string;
}

export interface FeeDistributionPlatform {
  bonus_category: string[];
  fee_authority: string;
  is_charity: boolean;
  is_locked: boolean;
  list: FeeDistributionRecipient[];
  show: boolean;
}

export interface FeeDistributionRecipient {
  charities?: FeeDistributionCharity[];
  has_claimed_fee: boolean;
  is_charity: boolean;
  is_creator: boolean;
  pfp: string;
  royalty_bps: number;
  twitter_username: string;
  username: string;
  wallet: string;
}

export interface FullTokenAthInfo {
  ath_mc?: string;
  ath_token?: string;
  token: FullTokenAthToken;
}

export interface FullTokenAthToken {
  address?: string;
  avatar?: string;
  name?: string;
  symbol?: string;
}

export interface FullTokenCreatorStat {
  amount: string;
  follow_count: number;
  from_address: string;
  fund_from: string;
  fund_tx_hash: string;
  inner_token_count: number;
  nickname: string;
  open_token_count: number;
  remark_count: number;
  transfer_ts: number;
  twitter_username: string;
  wallet_create_at: number;
}

export interface FullTokenInfo {
  address: string;
  ath_info: FullTokenAthInfo;
  ath_market_cap: string;
  ath_price: number;
  ath_ts: number;
  banner: string;
  biggest_pool_address: string;
  bluechip_owner_count: number;
  bluechip_owner_percentage: string;
  bot_degen_count: number;
  bot_degen_rate: string;
  callout_declaration: boolean;
  chain: string;
  creation_timestamp: number;
  creation_tool?: string;
  creator_address: string;
  creator_created_count: number;
  creator_hold_rate: string;
  creator_open_count?: number;
  creator_stat?: FullTokenCreatorStat;
  creator_token_balance: string;
  creator_token_status: string;
  cto_flag: number;
  decimals: number;
  dev_team_hold_rate: string;
  dexscr_boost_fee?: number;
  dexscr_update_link: number;
  dexscr_update_link_ts: number;
  fresh_wallet_rate: string;
  holder_count: number;
  image_dup_count?: number;
  is_hidden: boolean;
  launch_quote_address: string;
  launchpad: string;
  launchpad_platform: string;
  launchpad_progress: number;
  launchpad_status: number;
  link: FullTokenLinks;
  liquidity: number;
  live_preview?: FullTokenLivePreview;
  locked_ratio: number;
  logo: string;
  migrated_pool: string;
  migrated_pool_exchange: string;
  migrated_timestamp: number;
  migration_market_cap: number;
  migration_market_cap_quote: string;
  name: string;
  og?: boolean;
  open_timestamp?: number;
  priority_fee: string;
  private_vault_hold_rate: string;
  rug: FullTokenRug;
  rug_ratio: string;
  security: FullTokenSecurity;
  standard: string;
  symbol: string;
  tcid?: string;
  tip_fee: string;
  top70_sniper_hold_rate: string;
  top_10_holder_rate: string;
  top_bot_degen_percentage: string;
  top_bundler_trader_percentage: string;
  top_entrapment_trader_percentage: string;
  top_rat_trader_percentage: string;
  total_fee: string;
  total_supply: number;
  tpool: Tpool;
  trade_fee: string;
  trade_stat: FullTokenTradeStat;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
  twitter_create_token_count?: number;
  twitter_created_count?: number;
  twitter_del_post_count?: number;
  twitter_del_post_token_count?: number;
  twitter_rename_count?: number;
  visiting_count?: number;
}

export interface FullTokenLinks {
  geckoterminal: string;
  gmgn: string;
  telegram?: string;
  twitter_username: string;
  website: string;
}

export interface FullTokenLivePreview {
  detail_url_pump: string;
  end_live_timestamp: number;
  is_token_live: boolean;
  reply_count: number;
  start_live_timestamp: number;
  thumbnail: string;
}

export interface FullTokenRug {
  rug_ratio: string;
}

export interface FullTokenSecurity {
  average_tax: string;
  burn_ratio: string;
  burn_status: string;
  buy_tax: string;
  can_not_sell: number;
  can_sell: number;
  dev_token_burn_amount: string;
  dev_token_burn_ratio: string;
  flags: string[];
  hide_risk: boolean;
  high_tax: string;
  is_blacklist: boolean | null;
  is_honeypot: boolean | null;
  is_open_source: boolean | null;
  is_renounced: boolean | null;
  is_show_alert: boolean;
  lock_info: unknown | null;
  lock_summary: TokenFeeLockSummary;
  privileges: string[];
  renounced_freeze_account: boolean;
  renounced_mint: boolean;
  sell_tax: string;
  top_10_holder_rate: string;
  total_buy_tax: string;
  total_sell_tax: string;
}

export interface FullTokenTradeStat {
  bundler_wallets: number;
  creator_wallets: number;
  following_wallets: number;
  fresh_wallets: number;
  rat_trader_wallets: number;
  renowned_wallets: number;
  smart_wallets: number;
  sniper_wallets: number;
  top_wallets: number;
  updated_at: number;
  whale_wallets: number;
}

export interface GasPrice {
  auto: string;
  auto_mev: string;
  average: string;
  average_estimate_time: number;
  average_orign: string;
  average_prio_fee: string;
  average_prio_fee_mixed: string;
  base_fee?: string;
  block_number?: number;
  block_timestamp?: number;
  chain: string;
  eth_usd_price: number;
  high: string;
  high_estimate_time: number;
  high_orign: string;
  high_prio_fee: string;
  high_prio_fee_mixed: string;
  last_block: number;
  low: string;
  low_estimate_time: number;
  low_orign: string;
  low_prio_fee: string;
  low_prio_fee_mixed: string;
  native_token_usd_price: number;
  prio: string;
  prio_mev: string;
  suggest_base_fee: string;
  tip: string;
  tip_mev: string;
}

export interface GetActivityRankInfoData {
  activity_begin: number;
  activity_end: number;
  list: unknown[];
}

export interface GetActivityRankInfoResponse {
  code: number;
  data: GetActivityRankInfoData;
  message: string;
  reason: string;
}

export interface GetAggedTokenTradesData {
  trades: AggedTradeBucket[];
}

export interface GetAggedTokenTradesResponse {
  code: number;
  data: GetAggedTokenTradesData;
  message: string;
  reason: string;
}

export interface GetAggedTokenTransfersData {
  transfers: AggedTransferBucket[];
}

export interface GetAggedTokenTransfersResponse {
  code: number;
  data: GetAggedTokenTransfersData;
  message: string;
  reason: string;
}

export interface GetBluechipRankResponse {
  code: number;
  data: BluechipToken[];
  message: string;
  reason: string;
}

export interface GetDevCreatedTokensData {
  creator_ath_info: DevCreatorAthInfo;
  inner_count: number;
  last_create_timestamp: number;
  open_count: number;
  open_ratio: string;
  tokens: DevCreatedToken[];
}

export interface GetDevCreatedTokensResponse {
  code: number;
  data: GetDevCreatedTokensData;
  message: string;
  reason: string;
}

export interface GetDexTradesPollingData {
  allAggregationResult: DexAggregationResult;
  source: string;
  topLaunchpads: DexAggregationResult[];
  topProtocols: DexAggregationResult[];
}

export interface GetDexTradesPollingResponse {
  code: number;
  data: GetDexTradesPollingData;
  message: string;
  reason: string;
}

export interface GetGasPriceListData {
  gas_prices: GasPrice[];
}

export interface GetGasPriceListResponse {
  code: number;
  data: GetGasPriceListData;
  message: string;
  reason: string;
}

export interface GetHotSearchesResponse {
  code: number;
  data: TrendingChainBucket[];
  message: string;
}

export interface GetLaunchpadTaxPolicyData {
  platforms: Record<string, LaunchpadTaxPlatform>;
  revision: string;
  tipsConfigs: LaunchpadTaxTipsConfigs;
}

export interface GetLaunchpadTaxPolicyResponse {
  code: number;
  data: GetLaunchpadTaxPolicyData;
  message: string;
  reason: string;
}

export interface GetLiveTokenPreviewData {
  address: string;
  create_timestamp: number;
  creator: string;
  description: string;
  detail_url_gmgn: string;
  detail_url_pump: string;
  end_live_timestamp: number | null;
  is_token_live: boolean;
  logo: string;
  mc: string;
  name: string;
  price_24_change: string;
  reply_count: number;
  start_live_timestamp: number;
  symbol: string;
  telegram: string;
  thumbnail: string;
  twitter: string;
  website: string;
}

export interface GetLiveTokenPreviewResponse {
  code: number;
  data: GetLiveTokenPreviewData;
  message: string;
  reason: string;
}

export interface GetLiveTwitchKolData {
  base: Record<string, TwitchKolChannel>;
  bsc: Record<string, TwitchKolChannel>;
  sol: Record<string, TwitchKolChannel>;
}

export interface GetLiveTwitchKolResponse {
  code: number;
  data: GetLiveTwitchKolData;
  message: string;
  reason: string;
}

export interface GetMajorCoinPricesData {
  prices: MajorCoinPrice[];
}

export interface GetMajorCoinPricesResponse {
  code: number;
  data: GetMajorCoinPricesData;
  message: string;
  reason: string;
}

export interface GetMultiTokenFullInfoResponse {
  code: number;
  data: FullTokenInfo[];
  message: string;
  reason: string;
}

export interface GetMultiTokenInfoResponse {
  code: number;
  data: MultiTokenInfo[];
  message: string;
  reason: string;
}

export interface GetMultiWindowTokenInfoResponse {
  code: number;
  data: MultiWindowTokenInfo[];
  message: string;
  reason: string;
}

export interface GetNativeTransferData {
  address: string;
  amount: string;
  from_address: string;
  fund_tx_hash: string;
  nickname: string;
  transfer_ts: number;
  twitter_username: string;
}

export interface GetNativeTransferResponse {
  code: number;
  data: GetNativeTransferData;
  message: string;
  reason: string;
}

export interface GetNewPairsData {
  pairs: NewPair[];
}

export interface GetNewPairsResponse {
  code: number;
  data: GetNewPairsData;
  message: string;
  reason: string;
}

export interface GetRecommendSlippageData {
  display_slippage: string;
  has_tax: boolean;
  recommend_sell_slippage: string;
  recommend_slippage: string;
  volatility: number;
}

export interface GetRecommendSlippageResponse {
  code: number;
  data: GetRecommendSlippageData;
  message: string;
  reason: string;
}

export interface GetSimilarCoinExtremesData {
  earliest: SimilarCoinExtreme | null;
  max_mcp: SimilarCoinExtreme | null;
}

export interface GetSimilarCoinExtremesResponse {
  code: number;
  data: GetSimilarCoinExtremesData;
  message: string;
  reason: string;
}

export interface GetSimilarCoinsResponse {
  code: number;
  data: SimilarCoin[];
  message: string;
  reason: string;
}

export interface GetSmartMoneyWalletData {
  all_pnl: number;
  avatar: string | null;
  avg_holding_peroid: unknown | null;
  balance: string;
  bnb_balance: string;
  buy: number;
  buy_1d: number;
  buy_30d: number;
  buy_7d: number;
  ens?: unknown | null;
  eth_balance: string;
  followers_count: number;
  history_bought_cost: unknown | null;
  is_contract: boolean;
  last_active_timestamp: number;
  name: string | null;
  pnl: number;
  pnl_1d: number;
  pnl_2x_5x_num: unknown | null;
  pnl_30d: number;
  pnl_7d: number;
  pnl_gt_5x_num: unknown | null;
  pnl_lt_2x_num: unknown | null;
  pnl_lt_minus_dot5_num: unknown | null;
  pnl_minus_dot5_0x_num: unknown | null;
  profit_num: unknown | null;
  realized_profit: number;
  realized_profit_1d: number;
  realized_profit_30d: number;
  realized_profit_7d: number;
  refresh_requested_at: unknown | null;
  risk?: WalletRiskProfile;
  sell: number;
  sell_1d: number;
  sell_30d: number;
  sell_7d: number;
  sol_balance: string;
  tag_rank: WalletTagRank;
  tags: string[];
  token_avg_cost: unknown | null;
  token_num: unknown | null;
  token_sold_avg_profit: unknown | null;
  total_profit: number;
  total_profit_pnl: number;
  total_value: number;
  trx_balance: string;
  twitter_bind: boolean;
  twitter_fans_num: number;
  twitter_name: string | null;
  twitter_username?: string | null;
  unrealized_pnl: number;
  unrealized_profit: number;
  updated_at: number | null;
  winrate: unknown | null;
}

export interface GetSmartMoneyWalletInfoData {
  all_pnl: number;
  avatar: string | null;
  avg_holding_peroid: number | null;
  balance: string;
  bnb_balance: string;
  buy: number;
  buy_1d: number;
  buy_30d: number;
  buy_7d: number;
  ens: string | null;
  eth_balance: string;
  followers_count: number;
  history_bought_cost: number | null;
  is_contract: boolean;
  last_active_timestamp: number;
  name: string | null;
  pnl: number;
  pnl_1d: number;
  pnl_2x_5x_num: number | null;
  pnl_30d: number;
  pnl_7d: number;
  pnl_gt_5x_num: number | null;
  pnl_lt_2x_num: number | null;
  pnl_lt_minus_dot5_num: number | null;
  pnl_minus_dot5_0x_num: number | null;
  profit_num: number | null;
  realized_profit: number;
  realized_profit_1d: number;
  realized_profit_30d: number;
  realized_profit_7d: number;
  refresh_requested_at: number | null;
  risk: SmartMoneyRisk;
  sell: number;
  sell_1d: number;
  sell_30d: number;
  sell_7d: number;
  sol_balance: string;
  tag_rank: Record<string, number | null>;
  tags: string[];
  token_avg_cost: number | null;
  token_num: number | null;
  token_sold_avg_profit: number | null;
  total_profit: number;
  total_profit_pnl: number;
  total_value: number;
  trx_balance: string;
  twitter_bind: boolean;
  twitter_fans_num: number;
  twitter_name: string | null;
  twitter_username: string | null;
  unrealized_pnl: number;
  unrealized_profit: number;
  updated_at: number;
  winrate: number | null;
}

export interface GetSmartMoneyWalletInfoResponse {
  code: number;
  data: GetSmartMoneyWalletInfoData;
  msg: string;
}

export interface GetSmartMoneyWalletResponse {
  code: number;
  data: GetSmartMoneyWalletData;
  msg: string;
}

export interface GetSwapRankingsData {
  rank: SwapRankToken[];
}

export interface GetSwapRankingsResponse {
  code: number;
  data: GetSwapRankingsData;
  message: string;
  reason: string;
}

export interface GetTokenAiNarrativeData {
  en: string;
  source: number;
  zh_cn: string;
  zh_tw: string;
}

export interface GetTokenAiNarrativeResponse {
  code: number;
  data: GetTokenAiNarrativeData;
  message: string;
  reason: string;
}

export interface GetTokenBundlerStatData {
  bundler_count: number;
  bundler_hold_ratio: string;
  bundler_max_hold_ratio: string;
  bundler_swap_quote_amount: string;
  bundler_swap_ratio: string;
  bundler_swaps: number;
}

export interface GetTokenBundlerStatResponse {
  code: number;
  data: GetTokenBundlerStatData;
  message: string;
  reason: string;
}

export interface GetTokenCandlesData {
  _debug_tpool: Tpool | null;
  _debug_tpool_desc: string;
  list: McapCandle[];
}

export interface GetTokenCandlesResponse {
  code: number;
  data: GetTokenCandlesData;
  message: string;
  reason: string;
}

export interface GetTokenCommunityMessagesData {
  chain: string;
  community: TokenCommunity;
  declaration_level: string;
  has_more: boolean;
  messages: TokenCommunityMessage[];
  top_message?: TokenCommunityMessage;
}

export interface GetTokenCommunityMessagesResponse {
  code: number;
  data: GetTokenCommunityMessagesData;
  message: string;
  reason: string;
}

export interface GetTokenDevInfoData {
  address: string;
  creator_address: string;
  creator_open_count: number;
  creator_token_balance: string;
  creator_token_status: string;
  cto_flag: number;
  dexscr_ad: number;
  dexscr_ad_ts: number;
  dexscr_boost_fee: number;
  dexscr_boost_ts: number;
  dexscr_trending_bar: number;
  dexscr_trending_bar_ts: number;
  dexscr_update_link: number;
  dexscr_update_link_ts: number;
  fund_from: string;
  fund_from_ts: number;
  offchain: boolean;
  top_10_holder_rate: string;
  twitter_change_flag: boolean;
  twitter_create_token_count: number;
  twitter_created_count: number;
  twitter_del_post_count: number;
  twitter_del_post_token_count: number;
  twitter_name_change_history: unknown[];
  twitter_rename_count: number;
}

export interface GetTokenDevInfoResponse {
  code: number;
  data: GetTokenDevInfoData;
  message: string;
  reason: string;
}

export interface GetTokenFeeDistributionData {
  launchpad: string;
  platform_data: FeeDistributionPlatform | null;
}

export interface GetTokenFeeDistributionResponse {
  code: number;
  data: GetTokenFeeDistributionData;
  message: string;
  reason: string;
}

export interface GetTokenFeeInfoData {
  address: string;
  launchpad: TokenLaunchpad;
  pool_fee_info_list: TokenFeePool[];
  security: TokenFeeSecurity;
}

export interface GetTokenFeeInfoResponse {
  code: number;
  data: GetTokenFeeInfoData;
  message: string;
  reason: string;
}

export interface GetTokenHolderExtraInfoData {
  list: HolderExtraInfo[];
}

export interface GetTokenHolderExtraInfoResponse {
  code: number;
  data: GetTokenHolderExtraInfoData;
  message: string;
  reason: string;
}

export interface GetTokenHolderStatResponse {
  code: number;
  data: TagCounts;
  message: string;
  reason: string;
}

export interface GetTokenHoldersData {
  list: TokenHolder[];
  next: string;
}

export interface GetTokenHoldersResponse {
  code: number;
  data: GetTokenHoldersData;
  message: string;
  reason: string;
}

export interface GetTokenInfoBriefData {
  tokens: TokenBrief[];
}

export interface GetTokenInfoBriefResponse {
  code: number;
  data: GetTokenInfoBriefData;
  message: string;
  reason: string;
}

export interface GetTokenLiquidityData {
  history: LiquidityHistory[];
  next: string;
}

export interface GetTokenLiquidityResponse {
  code: number;
  data: GetTokenLiquidityData;
  message: string;
  reason: string;
}

export interface GetTokenLiquidityStatsData {
  bundler_wallets: number;
  chain: string;
  creator_wallets: number;
  following_wallets: number;
  fresh_wallets: number;
  rat_trader_wallets: number;
  renowned_wallets: number;
  smart_wallets: number;
  sniper_wallets: number;
  token_address: string;
  top_wallets: number;
  whale_wallets: number;
}

export interface GetTokenLiquidityStatsResponse {
  code: number;
  data: GetTokenLiquidityStatsData;
  message: string;
  reason: string;
}

export interface GetTokenLiquidityTrendData {
  pool_size: string;
  pools: string;
}

export interface GetTokenLiquidityTrendResponse {
  code: number;
  data: GetTokenLiquidityTrendData;
  message: string;
  reason: string;
}

export interface GetTokenLogoHistoryResponse {
  code: number;
  data: TokenLogoHistoryEntry[];
  message: string;
  reason: string;
}

export interface GetTokenMcapCandlesData {
  _debug_tpool: unknown | null;
  list: McapCandle[];
}

export interface GetTokenMcapCandlesResponse {
  code: number;
  data: GetTokenMcapCandlesData;
  message: string;
  reason: string;
}

export interface GetTokenPoolFeeInfoData {
  list: PoolFeeInfo[];
}

export interface GetTokenPoolFeeInfoResponse {
  code: number;
  data: GetTokenPoolFeeInfoData;
  message: string;
  reason: string;
}

export interface GetTokenPricesData {
  list: TokenPrice[];
}

export interface GetTokenPricesResponse {
  code: number;
  data: GetTokenPricesData;
  message: string;
  reason: string;
}

export interface GetTokenSecurityData {
  address: string;
  launchpad: TokenLaunchpad;
  security: TokenSecurity;
}

export interface GetTokenSecurityResponse {
  code: number;
  data: GetTokenSecurityData;
  message: string;
  reason: string;
}

export interface GetTokenSignalsResponse {
  code: number;
  data: TokenSignal[];
  message: string;
  reason: string;
}

export interface GetTokenSocialsData {
  address: string;
  link: TokenSocialLink;
  rug: TokenRug;
  vote: TokenVote;
}

export interface GetTokenSocialsResponse {
  code: number;
  data: GetTokenSocialsData;
  message: string;
  reason: string;
}

export interface GetTokenStatsData {
  bluechip_owner_count: number;
  bluechip_owner_percentage: string;
  bot_degen_count: number;
  bot_degen_rate: string;
  creator_created_count: number;
  creator_hold_rate: string;
  creator_token_balance: string;
  degen_call_count: number;
  dev_team_hold_rate: string;
  fresh_wallet_rate: string;
  holder_count: number;
  private_vault_hold_rate: string;
  signal_count: number;
  top70_sniper_hold_rate: string;
  top_10_holder_rate: string;
  top_bot_degen_percentage: string;
  top_bundler_trader_percentage: string;
  top_entrapment_trader_percentage: string;
  top_rat_trader_percentage: string;
}

export interface GetTokenStatsResponse {
  code: number;
  data: GetTokenStatsData;
  message: string;
  reason: string;
}

export interface GetTokenTraderStatResponse {
  code: number;
  data: TagCounts;
  message: string;
  reason: string;
}

export interface GetTokenTradersData {
  list: TokenHolder[];
  next: string;
}

export interface GetTokenTradersResponse {
  code: number;
  data: GetTokenTradersData;
  message: string;
  reason: string;
}

export interface GetTokenTradesData {
  history: TradeHistory[];
  next: string;
}

export interface GetTokenTradesResponse {
  code: number;
  data: GetTokenTradesData;
  message: string;
  reason: string;
}

export interface GetTokenTradesV2Data {
  history: TradeHistory[];
  next: string;
}

export interface GetTokenTradesV2Response {
  code: number;
  data: GetTokenTradesV2Data;
  message: string;
  reason: string;
}

export interface GetTokenTrendsData {
  trends: TokenTrendSeries;
}

export interface GetTokenTrendsResponse {
  code: number;
  data: GetTokenTrendsData;
  message: string;
  reason: string;
}

export interface GetTokenWalletTagsStatData {
  bundler_wallets: number;
  chain: string;
  creator_wallets: number;
  following_wallets: number;
  fresh_wallets: number;
  rat_trader_wallets: number;
  renowned_wallets: number;
  smart_wallets: number;
  sniper_wallets: number;
  token_address: string;
  top_wallets: number;
  whale_wallets: number;
}

export interface GetTokenWalletTagsStatResponse {
  code: number;
  data: GetTokenWalletTagsStatData;
  message: string;
  reason: string;
}

export interface GetTopBuyersData {
  holders: TopBuyerHolders;
}

export interface GetTopBuyersResponse {
  code: number;
  data: GetTopBuyersData;
  msg: string;
}

export interface GetTopCallersData {
  current_user: TopCaller | null;
  list: TopCaller[];
}

export interface GetTopCallersResponse {
  code: number;
  data: GetTopCallersData;
  message: string;
  reason: string;
}

export interface GetTrendingTokensResponse {
  code: number;
  data: TrendingChainBucket[];
  message: string;
}

export interface GetWalletActivityData {
  activities: WalletActivityEvent[];
  next: string;
}

export interface GetWalletActivityResponse {
  code: number;
  data: GetWalletActivityData;
  message: string;
  reason: string;
}

export interface GetWalletChainBalancesResponse {
  code: number;
  data: WalletChainBalance[];
  message: string;
  reason: string;
}

export interface GetWalletCommonStatData {
  avatar: string;
  bind_status: string;
  created_at: number;
  created_token_count: number;
  ens: string;
  follow_count: number;
  followers_count: number;
  fund_amount: string;
  fund_from: string;
  fund_from_address: string;
  fund_from_ts: number;
  fund_tx_hash: string;
  is_blue_verified: boolean;
  name: string;
  nick_name: string;
  remark_count: number;
  tag: string;
  tag_rank: WalletTagRank;
  tags: string[];
  twitter_bind: boolean;
  twitter_description: string;
  twitter_fans_num: number;
  twitter_id: string;
  twitter_name: string;
  twitter_username: string;
  verified: boolean;
  wallet_address: string;
}

export interface GetWalletCommonStatResponse {
  code: number;
  data: GetWalletCommonStatData;
  message: string;
  reason: string;
}

export interface GetWalletRankingsData {
  rank: RankedWallet[];
}

export interface GetWalletRankingsResponse {
  code: number;
  data: GetWalletRankingsData;
  message: string;
  reason: string;
}

export interface GetWalletStatData {
  bought_cost: string;
  buy: number;
  last_timestamp: number;
  native_balance: string;
  pnl_stat: WalletPnlStat;
  realized_profit: string;
  realized_profit_pnl: string;
  sell: number;
  sold_fee: string;
  sold_income: string;
  total_cost: string;
  wallet_address: string;
}

export interface GetWalletStatResponse {
  code: number;
  data: GetWalletStatData;
  message: string;
  reason: string;
}

export interface GetWebsiteInfoData {
  address: string;
  created_at: number;
  ip: string;
  website: string;
}

export interface GetWebsiteInfoResponse {
  code: number;
  data: GetWebsiteInfoData;
  message: string;
  reason: string;
}

export interface GmgnSearchCoin {
  address: string;
  ath_market_cap: string;
  buy_tax: string;
  chain: string;
  created_at: number;
  creation_tool: string;
  creator: string;
  cto_flag: number;
  dexscr_ad: number;
  dexscr_boost_fee: number;
  dexscr_trending_bar_ts: number;
  dexscr_update_link: number;
  exchange: string;
  follow_state: boolean;
  holder_count: number;
  hot_level: number;
  is_honeypot: boolean | null;
  is_og: boolean;
  is_show_alert: boolean;
  kol_count: number;
  launch_quote_address: string;
  launchpad: string;
  launchpad_platform: string;
  launchpad_status: number;
  liquidity: string;
  logo: string;
  mcp: string;
  migrated_pool_exchange: string;
  name: string;
  offchain: boolean;
  price: string;
  price_24h: string;
  progress: number;
  quote_address: string;
  remark_name: string;
  renounced_freeze_account: boolean | null;
  sell_tax: string;
  standard: string;
  swaps_1h: number;
  swaps_24h: number;
  swaps_5m: number;
  swaps_6h: number;
  symbol: string;
  tax_allocation?: Record<string, unknown>;
  token_link: GmgnSearchTokenLink;
  total_buy_tax: number;
  total_fee: string;
  total_sell_tax: number;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
  twitter_change_flag: number;
  twitter_rename_count: number;
  visiting_count: number;
  volume_1h: number;
  volume_24h: number;
}

export interface GmgnSearchTokenLink {
  address: string;
  bitbucket: string;
  description: string;
  discord: string;
  facebook: string;
  fracaster: unknown | null;
  geckoterminal: string;
  github: string;
  gmgn: string;
  instagram: string;
  linkedin: string;
  medium: string;
  reddit: string;
  telegram: string;
  tiktok: string;
  twitter_username: string;
  verify_status: number;
  website: string;
  youtube: string;
}

export interface GmgnSearchWallet {
  address: string;
  avatar: string;
  balance: string;
  chain: string;
  ens: string;
  follow_count: number;
  follow_state: boolean;
  fund_from: string;
  fund_from_ts: number;
  last_active_time: number;
  pnl_7d: string;
  realized_profit_7d: string;
  remark_count: number;
  remark_name: string;
  twitter_fans_num: number;
  twitter_name: string;
  twitter_username: string;
  wallet_tags: string[];
  win_rate_7d: number;
}

export interface HolderExtraInfo {
  addr_type: number;
  address: string;
  avatar: string | null;
  created_at: number;
  exchange: string;
  is_new: boolean;
  is_on_curve: boolean;
  maker_token_tags: string[] | null;
  name: string | null;
  native_balance: string;
  native_transfer: HolderNativeTransfer | null;
  tags: string[] | null;
  token_transfer_in: HolderExtraTokenTransfer | null;
  token_transfer_out: HolderTokenTransfer | null;
  transfer_in: boolean;
  twitter_name: string | null;
  twitter_username: string | null;
}

export interface HolderExtraTokenTransfer {
  address: string;
  name: string | null;
  timestamp: number;
  tx_hash: string;
  type: string;
}

export interface HolderNativeTransfer {
  amount: string;
  from_address: string;
  name: string | null;
  timestamp: number;
  tx_hash: string;
}

export type HolderOrderBy = "amount_percentage" | "last_active_timestamp" | "netflow_usd" | "profit" | "realized_profit" | "unrealized_profit" | "buy_volume_cur" | "sell_volume_cur";

export interface HolderStatParams {
  chain: Chain;
  token_address: string;
}

export type HolderTag = "smart_degen" | "fresh_wallet" | "renowned" | "bundler" | "bluechip_owner" | "sniper" | "rat_trader" | "dev" | "transfer_in" | "dex_bot";

export interface HolderTokenTransfer {
  address: string;
  name: string | null;
  timestamp: number;
  tx_hash: string;
  type: string;
}

export interface HoldersParams {
  chain: Chain;
  cost?: number;
  cursor?: string | null;
  direction?: SortDirection;
  limit?: number;
  order_by?: HolderOrderBy;
  tag?: HolderTag | null;
  token_address: string;
}

export interface LaunchpadTaxPlatform {
  launchpad_platform_tax_policy: string;
}

export interface LaunchpadTaxPolicyParams {
  chain: Chain;
}

export interface LaunchpadTaxTip {
  en: string;
  zhCN: string;
  zhTW: string;
}

export interface LaunchpadTaxTipsConfigs {
  icons: unknown[];
  tips: LaunchpadTaxTip[];
}

export interface LiquidityHistory {
  amount_usd: string;
  balance: string;
  base_amount: string;
  contract_address: string;
  event: string;
  history_base: string;
  history_bought_amount: string;
  history_quote: string;
  history_sold_amount: string;
  history_sold_income: string;
  id: string;
  is_open_or_close: number;
  is_single: boolean;
  maker: string;
  maker_avatar: string;
  maker_ens: string;
  maker_name: string;
  maker_tags: string[];
  maker_token_tags: string[];
  maker_twitter_name: string;
  maker_twitter_username: string;
  max_price: string;
  min_price: string;
  price_usd: string;
  quote_address: string;
  quote_amount: string;
  quote_symbol: string;
  realized_profit: string;
  timestamp: number;
  token_address: string;
  total_trade: number;
  tx_hash: string;
  unrealized_profit: string;
}

export interface LiquidityParams {
  chain: Chain;
  cursor?: string | null;
  limit?: number;
  token_address: string;
}

export interface LivePreviewParams {
  chain: Chain;
  token_address: string;
}

export interface LockSummary {
  is_locked: boolean;
  left_lock_percent: string;
  lock_detail: unknown | null;
  lock_percent: string;
  lock_tags: string[] | null;
}

export interface MajorCoinPrice {
  price: string;
  symbol: string;
}

export interface McapCandle {
  amount: string;
  close: string;
  high: string;
  low: string;
  open: string;
  source: string;
  time: number;
  volume: string;
}

export interface McapCandlesParams {
  chain: Chain;
  limit?: number;
  resolution?: Resolution;
  token_address: string;
}

export interface MultiTokenFullInfoParams {
  chain: Chain;
}

export interface MultiTokenInfo {
  address: string;
  ath_price: number;
  biggest_pool_address: string;
  chain: string;
  creation_timestamp: number;
  creator_address: string;
  decimals: number;
  holder_count: number;
  is_hidden?: boolean;
  launchpad: string;
  launchpad_platform: string;
  launchpad_progress: number;
  launchpad_status: number;
  liquidity: number;
  locked_ratio: number;
  logo: string;
  migrated_pool: string;
  migrated_timestamp: number;
  migration_market_cap: number;
  migration_market_cap_quote: string;
  name: string;
  route_info_init?: Record<string, RouteInfoInitMember>;
  standard: string;
  symbol: string;
  total_supply: number;
  tpool: Tpool;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
}

export interface MultiTokenInfoParams {
  chain: Chain;
}

export interface MultiWindowTokenDev {
  address: string;
  creator_address: string;
  creator_open_count: number;
  creator_token_balance: string;
  creator_token_status: string;
  cto_flag: number;
  dexscr_ad: number;
  dexscr_ad_ts: number;
  dexscr_boost_fee: number;
  dexscr_boost_ts: number;
  dexscr_trending_bar: number;
  dexscr_trending_bar_ts: number;
  dexscr_update_link: number;
  dexscr_update_link_ts: number;
  fund_from: string;
  fund_from_ts: number;
  offchain: boolean;
  top_10_holder_rate: string;
  twitter_change_flag: boolean;
  twitter_create_token_count: number;
  twitter_created_count: number;
  twitter_del_post_count: number;
  twitter_del_post_token_count: number;
  twitter_name_change_history: unknown[];
  twitter_rename_count: number;
}

export interface MultiWindowTokenInfo {
  address: string;
  banner: string;
  biggest_pool_address: string;
  callout_declaration?: boolean;
  circulating_supply: string;
  creation_timestamp: number;
  creation_tool: string;
  decimals: number;
  dev: MultiWindowTokenDev;
  holder_count: number;
  image_dup_count: number;
  is_hidden?: boolean;
  liquidity: string;
  logo: string;
  max_supply: string;
  migrated_timestamp: number;
  name: string;
  offchain: boolean;
  og: boolean;
  open_timestamp: number;
  pool: MultiWindowTokenPool;
  price: MultiWindowTokenPrice;
  priority_fee: string;
  standard: string;
  symbol: string;
  tcid: string;
  tip_fee: string;
  total_fee: string;
  total_supply: string;
  tpool: Tpool;
  trade_fee: string;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
  visiting_count: number;
}

export interface MultiWindowTokenInfoParams {
  chain: Chain;
}

export interface MultiWindowTokenPool {
  address: string;
  base_address: string;
  base_reserve: string;
  base_reserve_value: string;
  base_symbol?: string;
  base_vault_address: string;
  creation_timestamp: number;
  creator: string;
  exchange: string;
  factory?: string;
  fee_ratio: string;
  initial_base_reserve: string;
  initial_liquidity: string;
  initial_quote_reserve: string;
  liquidity: string;
  pool_address: string;
  quote_address: string;
  quote_reserve: string;
  quote_reserve_value: string;
  quote_symbol: string;
  quote_vault_address: string;
  token0_address: string;
  token1_address: string;
}

export interface MultiWindowTokenPrice {
  address: string;
  buy_volume_1h: string;
  buy_volume_1m: string;
  buy_volume_24h: string;
  buy_volume_5m: string;
  buy_volume_6h: string;
  buys_1h: number;
  buys_1m: number;
  buys_24h: number;
  buys_5m: number;
  buys_6h: number;
  hot_level: number;
  price: string;
  price_1h: string;
  price_1m: string;
  price_24h: string;
  price_5m: string;
  price_6h: string;
  sell_volume_1h: string;
  sell_volume_1m: string;
  sell_volume_24h: string;
  sell_volume_5m: string;
  sell_volume_6h: string;
  sells_1h: number;
  sells_1m: number;
  sells_24h: number;
  sells_5m: number;
  sells_6h: number;
  swaps_1h: number;
  swaps_1m: number;
  swaps_24h: number;
  swaps_5m: number;
  swaps_6h: number;
  volume_1h: string;
  volume_1m: string;
  volume_24h: string;
  volume_5m: string;
  volume_6h: string;
}

export interface NativeTransferParams {
  chain: Chain;
  wallet_address: string;
}

export interface NewPair {
  address: string;
  base_address: string;
  base_token_info: NewPairBaseToken;
  bot_degen_count?: number;
  bot_degen_rate?: number;
  chain: string;
  dev_team_hold_rate?: number;
  dexscr_ad_ts?: number;
  dexscr_boost_fee?: number;
  dexscr_boost_ts?: number;
  dexscr_update_link_ts?: number;
  exchange: string;
  history_highest_market_cap?: number;
  image_dup: string;
  initial_liquidity: string;
  initial_quote_reserve: string;
  launch_quote_address?: string;
  launchpad?: string;
  launchpad_platform?: string;
  migrated_pool_exchange?: string;
  open_timestamp: number;
  quote_address: string;
  quote_reserve?: string;
  quote_reserve_usd?: string;
  quote_symbol: string;
  seq_index: string;
  telegram_dup?: number;
  top70_sniper_hold_rate?: number;
  total_fee?: number;
  twitter_dup?: number;
  visiting_count?: number;
  website_dup?: number;
}

export interface NewPairBaseToken {
  address: string;
  bundler_rate?: number;
  bundler_trader_amount_rate?: string;
  burn_ratio?: string;
  burn_status: string;
  buy_tax?: string;
  buy_volume_1h: string;
  buy_volume_1m: string;
  buy_volume_24h: string;
  buy_volume_5m: string;
  buy_volume_6h: string;
  buys?: number;
  creation_timestamp: number;
  creator: string;
  creator_balance_rate?: string;
  creator_created_inner_count?: number;
  creator_created_open_ratio?: number;
  creator_token_status?: string;
  cto_flag: number;
  dev_token_burn_ratio?: number;
  dexscr_ad: number;
  dexscr_update_link: number;
  entrapment_ratio?: string;
  fund_from_address?: string;
  holder_count?: number;
  hot_level?: number;
  insider_ratio?: number;
  is_honeypot: string;
  is_og?: boolean;
  is_token_live?: boolean;
  launchpad_status: number;
  liquidity: string;
  logo: string;
  market_cap: string;
  name: string;
  price: string;
  price_1h: string;
  price_1m: string;
  price_24h: string;
  price_5m: string;
  price_6h: string;
  price_change_percent1h: string;
  price_change_percent1m: string;
  price_change_percent5m: string;
  progress: number;
  rat_trader_amount_rate?: number;
  renounced: number;
  renounced_freeze_account: number;
  renounced_mint: number;
  renowned_count?: number;
  rug_ratio?: number;
  sell_tax?: string;
  sell_volume_1h: string;
  sell_volume_1m: string;
  sell_volume_24h: string;
  sell_volume_5m: string;
  sell_volume_6h: string;
  sells?: number;
  smart_degen_count?: number;
  sniper_count?: number;
  social_links: NewPairSocialLinks;
  standard?: string;
  swaps?: number;
  symbol: string;
  top_10_holder_rate?: number;
  total_supply: number;
  twitter_change_flag: number;
  twitter_create_token_count?: number;
  twitter_del_post_token_count?: number;
  twitter_rename_count?: number;
  volume: string;
}

export interface NewPairSocialLinks {
  telegram?: string;
  twitter_username?: string;
  website?: string;
}

export type NewPairsOrderBy = "open_timestamp" | "creation_timestamp" | "market_cap" | "holder_count" | "liquidity" | "volume" | "swaps" | "progress" | "price_change_percent1h";

export interface NewPairsParams {
  chain: Chain;
  /** Security screens applied before sorting. */
  filters?: TokenFilter[] | null;
  /** Age window — only pairs opened inside it are returned. */
  interval?: TrendingInterval;
  /** Restrict to these launchpads, e.g. `Pump.fun`, `letsbonk`, `fourmeme`. */
  launchpad_platforms?: string[] | null;
  /** Maximum pairs to return. */
  limit?: number;
  /** Column to sort on. */
  order_by?: NewPairsOrderBy;
}

export interface PoolFeeInfo {
  address: string;
  exchange: string;
  fee_params: unknown | null;
  fee_ratio: number;
  is_dynamic_fee: boolean;
  liquidity: number;
  meteora_damm_v2_base_fee_config: unknown | null;
  meteora_virtual_curve_fee_config: unknown | null;
  pool_type: string;
}

export interface PoolFeeInfoParams {
  chain: Chain;
  token_address: string;
}

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";

export interface RankedWallet {
  address: string;
  arc_balance: string;
  avatar: string;
  avg_cost_1d: string;
  avg_cost_30d: string;
  avg_cost_7d: string;
  avg_holding_period_1d: number;
  avg_holding_period_30d: number;
  avg_holding_period_7d: number;
  balance: string;
  buy: number;
  buy_1d: number;
  buy_30d: number;
  buy_7d: number;
  daily_profit_7d: WalletDailyProfit[] | null;
  eth_balance: string;
  follow_count: number;
  hyperevm_balance: string;
  last_active: number;
  monad_balance: string;
  name: string;
  net_inflow_1d: string;
  net_inflow_30d: string;
  net_inflow_7d: string;
  nickname: string;
  pnl_1d: string;
  pnl_2x_5x_num_7d: number;
  pnl_30d: string;
  pnl_7d: string;
  pnl_gt_5x_num_7d: number;
  pnl_lt_2x_num_7d: number;
  pnl_lt_minus_dot5_num_7d: number;
  pnl_minus_dot5_0x_num_7d: number;
  realized_profit_1d: string;
  realized_profit_30d: string;
  realized_profit_7d: string;
  remark_count: number;
  robinhood_balance: string;
  sell: number;
  sell_1d: number;
  sell_30d: number;
  sell_7d: number;
  sol_balance: string;
  tags: string[];
  trx_balance: string;
  twitch_channel_name: string;
  twitter_description: string;
  twitter_name: string;
  twitter_username: string;
  txs: number;
  txs_1d: number;
  txs_30d: number;
  txs_7d: number;
  volume_1d: string;
  volume_30d: string;
  volume_7d: string;
  wallet_address: string;
  winrate_1d: number;
  winrate_30d: number;
  winrate_7d: number;
  xlayer_balance: string;
}

export interface RecommendSlippageParams {
  chain: Chain;
  token_address: string;
}

export type Resolution = "1s" | "15s" | "30s" | "1m" | "3m" | "5m" | "15m" | "30m" | "1h" | "4h" | "12h" | "1d" | "1w" | "1mo";

export interface RouteInfoInitMember {
  a?: string | null;
  b?: string | null;
  ma?: string | null;
  maa?: string | null;
  mb?: string | null;
  mba?: string | null;
  p?: string | null;
  "p:c"?: string;
  "p:fc"?: string;
  "pa:c"?: string;
  "pa:fc"?: string;
  rbh?: string | null;
  rs?: string;
  s?: Record<string, string>;
  sc?: string;
}

export interface RuggedToken {
  address: string;
  logo: string;
  name: string;
  symbol: string;
}

export interface SearchParams {
  chain: Chain;
  /** Name, symbol, contract address or wallet address. */
  q: string;
}

export interface SearchTokensData {
  coins: GmgnSearchCoin[];
  wallets: GmgnSearchWallet[];
}

export interface SearchTokensResponse {
  code: number;
  data: SearchTokensData;
  message: string;
  reason: string;
}

export interface SecurityParams {
  chain: Chain;
  token_address: string;
}

export interface SimilarCoin {
  address: string;
  chain: string;
  is_og: boolean;
  last_trade_time: number;
  liquidity: number;
  logo: string;
  mcp: number;
  name: string;
  open_or_create_time: number;
  symbol: string;
}

export interface SimilarCoinExtreme {
  address: string;
  chain: string;
  is_og: boolean;
  last_trade_time: number;
  liquidity: number;
  logo: string;
  mcp: number;
  name: string;
  open_or_create_time: number;
  symbol: string;
}

export interface SimilarCoinExtremesParams {
  chain: Chain;
  name: string;
  symbol: string;
  token_address: string;
}

export type SimilarCoinsOrderBy = "mcp" | "open_or_create_time";

export interface SimilarCoinsParams {
  chain: Chain;
  name: string;
  order_by?: SimilarCoinsOrderBy;
  symbol: string;
  token_address: string;
}

export interface SmartMoneyRisk {
  fast_tx: string;
  fast_tx_ratio: number;
  no_buy_hold: string;
  no_buy_hold_ratio: number;
  sell_pass_buy: string;
  sell_pass_buy_ratio: number;
  token_active: string;
  token_honeypot: string;
  token_honeypot_ratio: number;
}

export interface SmartMoneyWalletInfoParams {
  chain: Chain;
  wallet_address: string;
}

export interface SocialsParams {
  chain: Chain;
  token_address: string;
}

export type SortDirection = "desc";

export interface StatsParams {
  chain: Chain;
  token_address: string;
}

export interface SwapRankToken {
  address: string;
  bluechip_owner_percentage: number;
  bot_degen_count: number;
  bot_degen_rate: number;
  bundler_rate: number;
  burn_ratio: number;
  burn_status: string;
  buy_tax: string;
  buys: number;
  chain: string;
  creation_timestamp: number;
  creator: string;
  creator_close: boolean;
  creator_token_status: string;
  cto_flag: number;
  dev_team_hold_rate: number;
  dev_token_burn_amount: number;
  dev_token_burn_ratio: number;
  dexscr_ad: number;
  dexscr_ad_ts: number;
  dexscr_boost_fee: number;
  dexscr_boost_ts: number;
  dexscr_trending_bar: number;
  dexscr_trending_bar_ts: number;
  dexscr_update_link: number;
  dexscr_update_link_ts: number;
  end_live_timestamp: number;
  entrapment_ratio: number;
  exchange: string;
  fund_from_address?: string;
  gas_fee: number;
  history_highest_market_cap: number;
  holder_count: number;
  hot_level: number;
  id: number;
  image_dup: string;
  initial_liquidity: number;
  is_honeypot: number;
  is_og: boolean;
  is_open_source: number;
  is_renounced: number;
  is_show_alert: boolean;
  is_token_live: boolean;
  is_wash_trading: boolean;
  launch_quote_address: string;
  launchpad: string;
  launchpad_platform: string;
  launchpad_status: string;
  liquidity: number;
  lock_percent: number;
  logo: string;
  market_cap: number;
  migrated_pool_exchange: string;
  name: string;
  open_timestamp: number;
  pool_type: number;
  pool_type_str: string;
  price: number;
  price_change_percent: number;
  price_change_percent1h: number;
  price_change_percent1m: number;
  price_change_percent5m: number;
  rank: number;
  rat_trader_amount_rate: number;
  renounced_freeze_account: number;
  renounced_mint: number;
  renowned_count: number;
  rug_ratio: number;
  score: number;
  sell_tax: string;
  sells: number;
  smart_degen_count: number;
  sniper_count: number;
  square_mentions: number;
  start_live_timestamp: number;
  swaps: number;
  symbol: string;
  tcid: string;
  telegram: string;
  telegram_dup: number;
  top70_sniper_hold_rate: number;
  top_10_holder_rate: number;
  total_supply: number;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
  twitter_change_flag: number;
  twitter_create_token_count: number;
  twitter_del_post_token_count: number;
  twitter_dup: number;
  twitter_rename_count: number;
  twitter_username: string;
  visiting_count: number;
  volume: number;
  website: string;
  website_dup: number;
}

export interface SwapRankingsParams {
  chain: Chain;
  /** Restrict to these exchanges/launchpads, e.g. `pump`, `raydium`, `meteora`. */
  platforms?: string[] | null;
  /** Activity window to rank over. */
  timeframe?: TimeWindow;
}

export interface SymbolListRequest {
  symbols: string[];
}

export interface TagCounts {
  bluechip_owner_count: number;
  bundler_count: number;
  dev_count: number;
  dex_bot_count: number;
  following_count: number;
  fresh_wallet_count: number;
  insider_count: number;
  renowned_count: number;
  smart_degen_count: number;
  sniper_count: number;
}

export type TimeWindow = "1h" | "24h";

export interface TokenAiNarrativeParams {
  chain: Chain;
  token_address: string;
}

export interface TokenBrief {
  address: string;
  chain: string;
  decimals: number;
  is_honeypot: boolean;
  is_show_alert: boolean;
  launchpad: string;
  launchpad_platform: string;
  liqudity: string;
  logo: string;
  migrated_pool_exchange: string;
  renounced_freeze_account: boolean | null;
  symbol: string;
  total_supply?: string;
}

export interface TokenBundlerStatParams {
  chain: Chain;
  token_address: string;
}

export interface TokenCandlesParams {
  chain: Chain;
  /** Unix milliseconds lower bound, inclusive. */
  from_timestamp?: number;
  /** Maximum candles. */
  limit?: number;
  /** Candle width. */
  resolution?: Resolution;
  /** Unix milliseconds upper bound. Defaults to now. */
  to_timestamp?: number | null;
  token_address: string;
}

export interface TokenCommunity {
  token_address: string;
}

export interface TokenCommunityMessage {
  accu_cost: string;
  accu_fee: string;
  balance: string;
  content: string;
  created_at: string;
  current_holding_usd: string;
  current_pnl_usd: string;
  display_content?: string;
  display_name: string;
  follower_count: number;
  id: string;
  is_blue_verified: boolean;
  is_kol: boolean;
  is_safe: string;
  like_count: number;
  media_url: string | null;
  multiplier: string;
  profile_image_url: string;
  reply_count: number;
  source: string;
  ulid: string;
  user_twitter_url: string;
  username: string;
  wallet_address: string;
}

export interface TokenCommunityMessagesParams {
  chain: Chain;
  /** Maximum messages. */
  limit?: number;
  token_address: string;
}

export interface TokenDevInfoParams {
  chain: Chain;
  token_address: string;
}

export interface TokenFeeDistributionParams {
  chain: Chain;
  token_address: string;
}

export interface TokenFeeInfoParams {
  chain: Chain;
  token_address: string;
}

export interface TokenFeeLockDetail {
  is_blackhole: boolean;
  percent: string;
  pool: string;
}

export interface TokenFeeLockSummary {
  is_locked: boolean;
  left_lock_percent: string;
  lock_detail: TokenFeeLockDetail[] | null;
  lock_percent: string;
  lock_tags: unknown | null;
}

export interface TokenFeePool {
  address: string;
  exchange: string;
  fee_params: string[] | null;
  fee_ratio: number;
  is_dynamic_fee: boolean;
  liquidity: number;
  meteora_damm_v2_base_fee_config: unknown | null;
  meteora_virtual_curve_fee_config: unknown | null;
  pool_type: string;
}

export interface TokenFeeSecurity {
  address: string;
  audit?: TokenFeeSecurityAudit;
  average_tax: string;
  blacklist: number;
  burn_ratio: string;
  burn_status: string;
  buy_tax: string;
  can_not_sell: number;
  can_sell: number;
  dev_token_burn_amount: string;
  dev_token_burn_ratio: string;
  flags: string[];
  hide_risk: boolean;
  high_tax: string;
  honeypot: number;
  is_blacklist: boolean | null;
  is_honeypot: boolean | null;
  is_open_source: boolean | null;
  is_renounced: boolean | null;
  is_show_alert: boolean;
  lockInfo: unknown | null;
  lock_summary: TokenFeeLockSummary;
  open_source: number;
  privileges: unknown | null;
  renounced: number | null;
  renounced_freeze_account?: boolean;
  renounced_mint?: boolean;
  sell_tax: string;
  top_10_holder_rate: string;
  total_buy_tax: string;
  total_sell_tax: string;
}

export interface TokenFeeSecurityAudit {
  description: string;
  description_zh: string;
  security_engine: string;
}

export type TokenFilter = "not_honeypot" | "verified" | "renounced" | "frozen" | "has_social" | "burn";

export interface TokenHolder {
  account_address: string;
  accu_amount: number;
  accu_cost: number;
  addr_type: number;
  address: string;
  amount_cur: number;
  amount_percentage: number;
  avatar: string | null;
  avg_cost: number | null;
  avg_sold: number | null;
  balance: number;
  bluechip_holding_info?: TokenHolderBluechipHolding[];
  buy_amount_cur: number;
  buy_tx_count_cur: number;
  buy_volume_cur: number;
  cost: number;
  cost_cur: number;
  created_at: number;
  current_buy_amount: number;
  current_sell_amount: number;
  current_transfer_in_amount: number;
  current_transfer_out_amount: number;
  end_holding_at: number | null;
  exchange: string;
  history_bought_cost: number;
  history_bought_fee: number;
  history_sold_fee: number;
  history_sold_income: number;
  history_transfer_in_amount: number;
  history_transfer_in_cost: number;
  history_transfer_out_amount: number;
  history_transfer_out_fee: number;
  history_transfer_out_income: number;
  is_new: boolean;
  is_on_curve: boolean;
  is_suspicious: boolean;
  last_active_timestamp: number;
  last_block: number;
  maker_token_tags: string[];
  name: string | null;
  native_balance: string;
  native_transfer: HolderNativeTransfer | null;
  netflow_amount: number;
  netflow_usd: number;
  profit: number;
  profit_change: number | null;
  realized_pnl: number | null;
  realized_profit: number;
  sell_amount_cur: number;
  sell_amount_percentage: number;
  sell_tx_count_cur: number;
  sell_volume_cur: number;
  start_holding_at: number | null;
  tags: string[];
  token_transfer: HolderTokenTransfer;
  token_transfer_in: HolderTokenTransfer;
  token_transfer_out: HolderTokenTransfer;
  total_bc_value?: number;
  total_cost: number;
  transfer_in: boolean;
  transfer_in_count: number;
  transfer_out_count: number;
  twitter_name: string | null;
  twitter_username: string | null;
  unrealized_pnl: number | null;
  unrealized_profit: number;
  usd_value: number;
  wallet_tag_v2: string;
}

export interface TokenHolderBluechipHolding {
  balance: string;
  logo: string;
  symbol: string;
  token_address: string;
  value: string;
}

export interface TokenHolderExtraInfoParams {
  chain: Chain;
  token_address: string;
  /** Holders to enrich. Repeat the param for more than one. */
  wallet_addresses: string[];
}

export interface TokenInfoBriefParams {
  chain: Chain;
}

export interface TokenLaunchpad {
  address: string;
  description: string;
  launch_quote_address: string;
  launchpad: string;
  launchpad_platform: string;
  launchpad_progress: string;
  launchpad_status: number;
  migrated_pool_exchange: string;
}

export interface TokenLiquidityStatsParams {
  chain: Chain;
  token_address: string;
}

export interface TokenLiquidityTrendParams {
  chain: Chain;
  token_address: string;
}

export interface TokenLogoHistoryEntry {
  logo: string;
  timestamp: number;
}

export interface TokenLogoHistoryParams {
  chain: Chain;
  token_address: string;
}

export interface TokenPrice {
  address: string;
  price: string;
}

export interface TokenPricesParams {
  chain: Chain;
}

export interface TokenRug {
  address: string;
  holder_rugged_num: number;
  holder_token_num: number;
  rug_ratio: string;
  rugged_tokens: RuggedToken[] | null;
}

export interface TokenSecurity {
  address: string;
  average_tax: string;
  blacklist: number;
  burn_ratio: string;
  burn_status: string;
  buy_tax: string;
  can_not_sell: number;
  can_sell: number;
  dev_token_burn_amount: string;
  dev_token_burn_ratio: string;
  flags: string[];
  hide_risk: boolean;
  high_tax: string;
  honeypot: number;
  is_blacklist: boolean | null;
  is_honeypot: boolean | null;
  is_open_source: boolean | null;
  is_renounced: boolean | null;
  is_show_alert: boolean;
  lockInfo: unknown | null;
  lock_summary: LockSummary;
  open_source: number;
  privileges: unknown | null;
  renounced: number | null;
  renounced_freeze_account: boolean;
  renounced_mint: boolean;
  sell_tax: string;
  top_10_holder_rate: string;
  total_buy_tax?: string;
  total_sell_tax?: string;
}

export interface TokenSignal {
  ath: number;
  cur_data: TokenSignalCurrentStats;
  data: TokenSignalTokenInfo;
  first_trigger_mc: number;
  id: string;
  market_cap: number;
  signal_times: number;
  signal_times_by_type: Record<string, number>;
  signal_type: number;
  token_address: string;
  trigger_at: number;
  trigger_mc: number;
}

export interface TokenSignalCurrentStats {
  holder_count: number;
  liquidity: number;
  top_10_holder_rate: number;
}

export interface TokenSignalGroupRequest {
  /** Restrict to tokens launched on these platforms. */
  launchpad_platforms?: string[] | null;
  /** GMGN signal ids to match, e.g. `1` for a surge. */
  signal_types: number[];
  /** Drop tokens whose lifetime launchpad fees are below this. */
  total_fee_min?: number | null;
}

export interface TokenSignalTokenInfo {
  address: string;
  binance_charity_tax: number;
  bonus_category: unknown | null;
  bot_degen_count: number;
  bot_degen_rate: number;
  bundler_mhr: number;
  bundler_trader_amount_rate: number;
  burn_status: string;
  burn_tax: number;
  buy_tax: number;
  buys_1h: number;
  buys_1m: number;
  buys_24h: number;
  buys_6h: number;
  callout_count: number;
  callout_declaration: boolean;
  chain: string;
  claim_avatar: string;
  claim_fee_is_first: boolean;
  claim_fee_sol_amount: string;
  claim_platform: string;
  claim_platform_avatar: string;
  claim_platform_username: string;
  claim_twitter_user_name: string;
  claim_wallet_address: string;
  complete_cost_time: number;
  complete_timestamp: number;
  created_timestamp: number;
  created_timestamp_us: number;
  creation_tool: string;
  creator: string;
  creator_balance_rate: number;
  creator_created_count: number;
  creator_created_open_count: number;
  creator_created_open_ratio: number;
  creator_token_status: string;
  cto_flag: boolean;
  decimals: number;
  dev_tax: number;
  dev_team_hold_rate: number;
  dev_token_burn_amount: number;
  dev_token_burn_ratio: number;
  dexscr_ad: boolean;
  dexscr_boost_fee: number;
  dexscr_trending_bar: boolean;
  dexscr_update_link: boolean;
  dividend_tax: number;
  end_live_timestamp: number;
  entrapment_ratio: number;
  exchange: string;
  fee_params: unknown | null;
  fracaster: unknown | null;
  fresh_wallet_rate: number;
  fund_from: string;
  fund_from_address: string;
  fund_from_ts: number;
  giggle_charity_tax: number;
  has_at_least_one_social: boolean;
  holder_count: number;
  image_dup: number;
  instagram: string;
  is_honeypot: string;
  is_og: boolean;
  is_token_live: boolean;
  is_wash_trading: boolean;
  launchpad: string;
  launchpad_platform: string;
  liquidity: number;
  liquidity_tax: number;
  logo: string;
  market_cap: number;
  max_amount: number;
  migrated_pool_exchange?: string;
  min_amount: number;
  name: string;
  net_buy_1h: number;
  net_buy_1m: number;
  net_buy_24h: number;
  net_buy_6h: number;
  offchain: boolean;
  open_source: string;
  open_timestamp: number;
  open_timestamp_us: number;
  other_tax: number;
  owner_renounced: string;
  pool_address: string;
  priority_fee: number;
  private_vault_hold_rate: number;
  progress: number;
  quote_address: string;
  rat_trader_amount_rate: number;
  renounced_freeze_account: boolean;
  renounced_mint: boolean;
  renowned_count: number;
  rug_ratio: number;
  sell_tax: number;
  sells_1h: number;
  sells_1m: number;
  sells_24h: number;
  sells_6h: number;
  seq_index: string;
  show_sharing_fee: boolean;
  smart_degen_count: number;
  sniper_count: number;
  standard: string;
  start_live_timestamp: number;
  status: number;
  suspected_insider_hold_rate: number;
  swaps_1h: number;
  swaps_1m: number;
  swaps_24h: number;
  swaps_6h: number;
  symbol: string;
  tc_name: string;
  tcid: string;
  telegram: string;
  telegram_dup: number;
  tg_call_count: number;
  tiktok: string;
  tip_fee: number;
  top70_sniper_hold_rate: number;
  top_10_holder_rate: number;
  top_10_holder_rate_snp: number;
  total_buy_tax: number;
  total_fee: number;
  total_sell_tax: number;
  total_supply: number;
  trade_fee: number;
  trans_name: string;
  trans_name_zhcn: string;
  trans_symbol: string;
  trans_symbol_zhcn: string;
  trigger_count: number;
  tweet_publish_time: number;
  twitter: string;
  twitter_create_token_count: number;
  twitter_del_post_token_count: number;
  twitter_dup: number;
  twitter_handle: string;
  twitter_is_tweet: boolean;
  twitter_rename_count: number;
  usd_market_cap: number;
  vault_tax: number;
  visiting_count: number;
  volume_1h: number;
  volume_1m: number;
  volume_24h: number;
  volume_6h: number;
  website: string;
  website_dup: number;
  x_user_follower: number;
  x_user_following: number;
  zora_social_info: unknown | null;
}

export interface TokenSignalsParams {
  chain: Chain;
}

export interface TokenSignalsRequest {
  /** Signal groups evaluated together; a token matching any group is returned. */
  groups: TokenSignalGroupRequest[];
}

export interface TokenSocialLink {
  address: string;
  bitbucket: string;
  description: string;
  discord: string;
  facebook: string;
  fracaster: string | null;
  geckoterminal: string;
  github: string;
  gmgn: string;
  instagram: string;
  linkedin: string;
  medium: string;
  reddit: string;
  telegram: string;
  tiktok: string;
  twitter_username: string;
  verify_status: number;
  website: string;
  youtube: string;
}

export interface TokenTradesV2Params {
  chain: Chain;
  /** Pagination token from the previous page's `data.next`. */
  cursor?: string | null;
  /** Restrict to a single maker wallet. */
  maker?: string;
  token_address: string;
}

export interface TokenTrendPoint {
  timestamp: number;
  value: string;
}

export interface TokenTrendSeries {
  avg_holding_balance?: TokenTrendPoint[];
  bot_degen_percent?: TokenTrendPoint[];
  bundler_percent?: TokenTrendPoint[];
  entrapment_percent?: TokenTrendPoint[];
  holder_count?: TokenTrendPoint[];
  insider_percent?: TokenTrendPoint[];
  top100_holder_percent?: TokenTrendPoint[];
  top10_holder_percent?: TokenTrendPoint[];
}

export interface TokenTrendsParams {
  chain: Chain;
  token_address: string;
  /** Series to return. Repeat the param for more than one. */
  trends_types?: TokenTrendsType[];
}

export type TokenTrendsType = "avg_holding_balance" | "holder_count" | "top10_holder_percent" | "top100_holder_percent" | "bundler_percent" | "insider_percent" | "bot_degen_percent" | "entrapment_percent";

export interface TokenVote {
  like: number;
  unlike: number;
}

export interface TopBuyerHolderInfo {
  maker_token_tags: string[];
  status?: string;
  tags: string[] | null;
  wallet_address: string;
}

export interface TopBuyerHolders {
  bought_more: number;
  chain: string;
  hold_diff: number;
  holderInfo: TopBuyerHolderInfo[];
  holder_count: number;
  sold_diff: number;
  sold_part_diff: number;
  statusNow: TopBuyerStatusNow;
  top70_sniper_hold_rate: string;
}

export interface TopBuyerStatusNow {
  bought_more: number;
  bought_rate: string;
  hold: number;
  holding_rate: string;
  smart_count_bought_more: number | null;
  smart_count_hold: number | null;
  smart_count_sold: number | null;
  smart_count_sold_part: number | null;
  smart_count_transfered: number | null;
  smart_pos: number[];
  sold: number;
  sold_part: number;
  top_10_holder_rate: number;
  transfered: number;
}

export interface TopBuyersParams {
  chain: Chain;
  token_address: string;
}

export interface TopCaller {
  avg_multiplier: string;
  display_name?: string;
  encrypted_user_id?: string;
  follower_count: number;
  hit_2x_count: number;
  is_blue: boolean;
  prev_rank: number;
  profile_image_url?: string;
  rank: number;
  tier: string;
  top_tokens: TopCallerToken[];
  total_calls: number;
  twitter_avatar: string;
  twitter_name: string;
  twitter_username: string;
  username?: string;
  wallet: string;
}

export interface TopCallerToken {
  chain: string;
  launchpad: string;
  launchpad_platform: string;
  multiplier: string;
  token: string;
  token_logo: string;
  token_symbol: string;
}

export interface TopCallersParams {
  chain: Chain;
  /** Window the call multiples are scored over. */
  window?: TimeWindow;
}

export interface Tpool {
  base_address: string;
  exchange: string;
  launch_type: string;
  pool_address: string;
  quote_address: string;
}

export interface TradeHistory {
  amount_usd: string;
  balance: string;
  base_amount: string;
  dex_native: string;
  dex_usd: string;
  event: string;
  gas_native: string;
  gas_usd: string;
  history_bought_amount: string;
  history_sold_amount: string;
  history_sold_income: string;
  id: string;
  is_open_or_close: number;
  maker: string;
  maker_avatar: string;
  maker_ens: string;
  maker_event_tags: string[];
  maker_name: string;
  maker_tags: string[];
  maker_token_tags: string[];
  maker_twitter_name: string;
  maker_twitter_username: string;
  price_usd: string;
  priority_fee: string;
  quote_address: string;
  quote_amount: string;
  quote_symbol: string;
  realized_profit: string;
  timestamp: number;
  tip_fee: string;
  token_address: string;
  total_trade: number;
  tx_hash: string;
  unrealized_profit: string;
}

export type TraderOrderBy = "profit" | "realized_profit" | "unrealized_profit" | "amount_percentage" | "last_active_timestamp" | "netflow_usd" | "buy_volume_cur" | "sell_volume_cur";

export interface TraderStatParams {
  chain: Chain;
  token_address: string;
}

export interface TradersParams {
  chain: Chain;
  cursor?: string | null;
  direction?: SortDirection;
  limit?: number;
  order_by?: TraderOrderBy;
  /** Wallet cohort to filter on. Omit for all traders. */
  tag?: HolderTag | null;
  token_address: string;
}

export interface TradesParams {
  chain: Chain;
  /** Opaque pagination token. trades returns a fixed page (~50) with no page-size control; paginate by passing the previous response's `data.next` token here. */
  cursor?: string | null;
  maker?: string;
  token_address: string;
}

export interface TrendingChainBucket {
  chain: string;
  filter_id: string;
  interval: string;
  tokens: TrendingToken[];
  version: string;
}

export interface TrendingChainRequest {
  /** Chain to rank tokens on. */
  chain?: Chain;
  /** Security screens applied before ranking. */
  filters?: TokenFilter[] | null;
  /** Ranking window — GMGN recomputes the leaderboard per window. */
  interval?: TrendingInterval;
  /** Restrict to tokens launched on these platforms, e.g. `Pump.fun`, `letsbonk`, `fourmeme`. */
  launchpad_platforms?: string[] | null;
  /** Maximum tokens in this chain's bucket. Omit to take GMGN's own default, which is the whole leaderboard it has for that chain. */
  limit?: number | null;
}

export type TrendingInterval = "1m" | "5m" | "1h" | "6h" | "24h";

export interface TrendingToken {
  a: string;
  bdc: number;
  bdr: number;
  bdrr: number;
  bop: number;
  br: number;
  btax: string;
  bu: number;
  c: string;
  cc: boolean;
  co_d: boolean;
  ct: number;
  cto: number;
  d_br: number;
  d_ct: string;
  d_ffa?: string;
  d_ts: string;
  dhr: number;
  dtba: number;
  dtbr: number;
  dx_ad: number;
  dx_adts: number;
  dx_bf: number;
  dx_bts: number;
  dx_tb: number;
  dx_tbts: number;
  dx_ul: number;
  dx_ults: number;
  elt: number;
  etpr: number;
  ex: string;
  gf: number;
  hd: number;
  hhmc: number;
  hl: number;
  ilq: number;
  img_dup: string;
  isa: boolean;
  isog: boolean;
  itl: boolean;
  itv: string;
  iwt: boolean;
  kol: number;
  l: string;
  lkp?: number;
  lp: string;
  lpp: string;
  lpst: string;
  lq: number;
  lqa: string;
  m_t: string;
  m_w: string;
  m_x: string;
  m_xctc: number;
  m_xdpc: number;
  mc: number;
  mpe: string;
  nm: string;
  nt: number;
  ntg: number;
  nws: number;
  ot: number;
  p: number;
  pcp: number;
  pcp1h: number;
  pcp1m: number;
  pcp5m: number;
  rat: number;
  rug: number;
  s: string;
  s_blk?: number;
  s_brs: string;
  s_ihp: number | null;
  s_nm?: number;
  s_or?: number;
  s_os: number;
  s_qsafe?: string;
  sc: number;
  se: number;
  slt: number;
  smt: number;
  snp: number;
  ssf: boolean;
  stax: string;
  std?: string;
  sw: number;
  t10: number;
  t70_shr: number;
  tcid: string;
  ts_n: string;
  ts_nzh: string;
  ts_s: string;
  ts_szh: string;
  tsp: number;
  v: number;
  v_c: number;
  xcc: number;
  xcf: number;
}

export interface TrendingTokensRequest {
  /** One entry per chain. GMGN ranks every entry in a single upstream call and returns the buckets in the same order. */
  requests: TrendingChainRequest[];
}

export interface TwitchKolChannel {
  channel_name: string;
}

export interface WalletActivityEvent {
  buy_cost_usd: string | null;
  chain: string;
  cost_usd: string;
  dex_native: string;
  dex_usd: string;
  event_type: string;
  from_address: string;
  gas_native: string;
  gas_usd: string;
  is_open_or_close: number;
  launchpad: string;
  launchpad_platform: string;
  price: string;
  price_usd: string;
  priority_fee: string;
  quote_address: string;
  quote_amount: string;
  quote_token: WalletActivityQuoteToken;
  timestamp: number;
  tip_fee: string;
  to_address: string;
  token: WalletActivityToken;
  token_amount: string;
  tx_hash: string;
  wallet: string;
}

export interface WalletActivityParams {
  chain: Chain;
  /** Opaque cursor from a previous `next`. */
  cursor?: string | null;
  limit?: number;
  /** Event types to include; defaults to buy and sell. */
  type?: string[] | null;
  wallet_address: string;
}

export interface WalletActivityQuoteToken {
  decimals: number;
  logo: string;
  name: string;
  symbol: string;
  token_address: string;
}

export interface WalletActivityToken {
  address: string;
  logo: string;
  symbol: string;
  total_supply: string;
}

export interface WalletChainBalance {
  address: string;
  balance: string;
  chain: string;
  token_num: number;
  total_volume: string | null;
}

export interface WalletChainBalancesParams {
  chain: Chain;
  wallet_address: string;
}

export interface WalletCommonStatParams {
  chain: Chain;
  wallet_address: string;
}

export interface WalletDailyProfit {
  profit: string;
  timestamp: number;
}

export interface WalletPnlParams {
  chain: Chain;
  /** Window the P&L is computed over. */
  period?: WalletRankPeriod;
  wallet_address: string;
}

export interface WalletPnlStat {
  avg_holding_period: number | null;
  pnl_0x_2x_num: number;
  pnl_2x_5x_num: number;
  pnl_gt_5x_num: number;
  pnl_lt_nd5_num: number;
  pnl_nd5_0x_num: number;
  token_num: number;
  winrate: number | null;
}

export type WalletRankOrderBy = "pnl_1d" | "pnl_7d" | "pnl_30d" | "winrate_1d" | "winrate_7d" | "winrate_30d";

export type WalletRankPeriod = "1d" | "7d" | "30d";

export interface WalletRankingsParams {
  chain: Chain;
  /** Metric to sort on. Its window is independent of `period`. */
  order_by?: WalletRankOrderBy;
  /** Leaderboard window GMGN computes the rank over. */
  period?: WalletRankPeriod;
}

export interface WalletRiskProfile {
  fast_tx: string;
  fast_tx_ratio: number;
  no_buy_hold: string;
  no_buy_hold_ratio: number;
  sell_pass_buy: string;
  sell_pass_buy_ratio: number;
  token_active: string;
  token_honeypot: string;
  token_honeypot_ratio: number;
}

export interface WalletStatParams {
  chain: Chain;
  /** P&L window. Omit for all-time. */
  period?: WalletStatPeriod | null;
  wallet_address: string;
}

export type WalletStatPeriod = "1d" | "7d" | "all";

export interface WalletTagRank {
  arbitrager?: number | null;
  axiom?: number | null;
  kol?: number;
  photon?: number | null;
  top_followed?: number;
  top_renamed?: number;
  trojan?: number | null;
  wash_trader?: number;
}

export interface WalletTagsStatParams {
  chain: Chain;
  token_address: string;
}

export interface WebsiteInfoParams {
  chain: Chain;
  token_address: string;
}
