// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number | string)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
  upgrade_url?: string | null;
}

export interface GetCollectionVideosParams {
  /** The `max_cursor` from the previous page, sent as `cursor`. Omit it for the first page. */
  cursor?: string | null;
  /** A public TikTok collection URL: `https://www.tiktok.com/@<handle>/collection/<name>-<id>`. */
  url: string;
}

export interface GetCommentRepliesParams {
  /** The comment id: `cid` from `/v1/tiktok/video/comments`. */
  comment_id: string;
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: number | null;
  /** A TikTok video or photo post URL: `https://www.tiktok.com/@<handle>/video/<id>`, `/photo/<id>`, or a `https://vm.tiktok.com/<code>/` share link. */
  url: string;
}

export interface GetCommentsParams {
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: number | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
  /** A TikTok video or photo post URL: `https://www.tiktok.com/@<handle>/video/<id>`, `/photo/<id>`, or a `https://vm.tiktok.com/<code>/` share link. */
  url: string;
}

export type GetCommentsResponse = TikTokCommentsResponse | TikTokTrimmedCommentsResponse;

export interface GetFollowersParams {
  /** The TikTok handle, with or without a leading @. Send `handle` or `user_id`, not both. */
  handle?: string | null;
  /** The `min_time` from the previous page. Omit it for the first page. */
  min_time?: number | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
  /** The numeric TikTok user id (`user.id` from `/v1/tiktok/profile`). Send `handle` or `user_id`, not both. */
  user_id?: string | null;
}

export type GetFollowersResponse = TikTokFollowersResponse | TikTokTrimmedFollowersResponse;

export interface GetFollowingParams {
  /** The TikTok handle, with or without a leading @. */
  handle: string;
  /** The `min_time` from the previous page. Omit it for the first page. */
  min_time?: number | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
}

export type GetFollowingResponse = TikTokFollowingResponse | TikTokTrimmedFollowingResponse;

export interface GetProfileParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: GetProfileParamsCacheMaxAge | null;
  /** The TikTok handle, with or without a leading @. Send `handle` or `user_id`, not both. */
  handle?: string | null;
  /** The numeric TikTok user id (`user.id` from `/v1/tiktok/profile`). Send `handle` or `user_id`, not both. */
  user_id?: string | null;
}

export type GetProfileParamsCacheMaxAge = "1d" | "3d" | "7d" | "14d" | "30d";

export interface GetProfileVideosParams {
  /** The TikTok handle, with or without a leading @. Send `handle` or `user_id`, not both. */
  handle?: string | null;
  /** The `max_cursor` from the previous page. Omit it for the first page. */
  max_cursor?: string | null;
  /** Two-letter country code for the proxy, such as `US`, `GB` or `PH`. TikTok answers as it does to a viewer in that country; it does not filter results to that country. */
  region?: string | null;
  /** `latest` (default) or `popular`, most viewed first. */
  sort_by?: GetProfileVideosParamsSortBy | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
  /** The numeric TikTok user id (`user.id` from `/v1/tiktok/profile`). Send `handle` or `user_id`, not both. */
  user_id?: string | null;
}

export type GetProfileVideosParamsSortBy = "latest" | "popular";

export type GetProfileVideosResponse = TikTokProfileVideosResponse | TikTokTrimmedProfileVideosResponse;

export interface GetSearchSuggestionsParams {
  /** What to search TikTok for. */
  query: string;
  /** Two-letter country code for the proxy, such as `US`, `GB` or `PH`. TikTok answers as it does to a viewer in that country; it does not filter results to that country. */
  region?: string | null;
}

export interface GetSongParams {
  /** The sound's clip id, the number at the end of a sound URL such as `https://www.tiktok.com/music/Different-Acoustic-6717159721276540930`. */
  clipId: string;
}

export interface GetSongVideosParams {
  /** The sound's clip id, the number at the end of a sound URL such as `https://www.tiktok.com/music/Different-Acoustic-6717159721276540930`. */
  clipId: string;
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: number | null;
}

export interface GetTranscriptParams {
  /** Two-letter language code of the captions, such as `en` or `es`. Omit it for the captions in the video's original language. */
  language?: string | null;
  /** A TikTok video or photo post URL: `https://www.tiktok.com/@<handle>/video/<id>`, `/photo/<id>`, or a `https://vm.tiktok.com/<code>/` share link. */
  url: string;
  /** Accepted for Scrape Creators compatibility. It has no effect: only captions TikTok already has are returned. */
  use_ai_as_fallback?: boolean | null;
}

export interface GetTrendingFeedParams {
  /** Two-letter country code, such as `US` or `GB`. The feed is what TikTok serves a viewer in that country, not only videos from it. */
  region: string;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
}

export type GetTrendingFeedResponse = TikTokTrendingFeedResponse | TikTokTrimmedTrendingFeedResponse;

export interface GetVideoParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: GetVideoParamsCacheMaxAge | null;
  /** Set to `true` to add `transcript`, the video's WEBVTT captions, or `null` when it has none. */
  get_transcript?: boolean | null;
  /** Two-letter country code for the proxy, such as `US`, `GB` or `PH`. TikTok answers as it does to a viewer in that country; it does not filter results to that country. */
  region?: string | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
  /** A TikTok video or photo post URL: `https://www.tiktok.com/@<handle>/video/<id>`, `/photo/<id>`, or a `https://vm.tiktok.com/<code>/` share link. */
  url: string;
}

export type GetVideoParamsCacheMaxAge = "1d" | "3d" | "7d" | "14d" | "30d";

export type GetVideoResponse = TikTokVideoResponse | TikTokTrimmedVideoResponse;

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";

export interface SearchHashtagParams {
  /** The `cursor` from the previous page. Omit it for the first page. */
  cursor?: number | null;
  /** The hashtag, with or without a leading #. */
  hashtag: string;
  /** Two-letter country code for the proxy, such as `US`, `GB` or `PH`. TikTok answers as it does to a viewer in that country; it does not filter results to that country. */
  region?: string | null;
  /** Set to `true` for the trimmed answer Scrape Creators returns: fewer keys per item. */
  trim?: boolean | null;
}

export type SearchHashtagResponse = TikTokHashtagSearchResponse | TikTokTrimmedHashtagSearchResponse;

export interface TikTokAppAwemeAddedSoundMusicInfo {
  album: string;
  allow_offline_music_to_detail_page?: boolean;
  artists: string | null;
  author: string;
  author_deleted: boolean;
  author_position: string | null;
  avatar_medium?: TikTokAppAwemeAddedSoundMusicInfoAvatarMedium;
  avatar_thumb?: TikTokAppAwemeAddedSoundMusicInfoAvatarThumb;
  binded_challenge_id: number | string;
  collect_stat: number | string;
  cover_large: TikTokAppAwemeAddedSoundMusicInfoCoverLarge;
  cover_medium: TikTokAppAwemeAddedSoundMusicInfoCoverMedium;
  cover_thumb: TikTokAppAwemeAddedSoundMusicInfoCoverThumb;
  duration: number | string;
  external_song_info: TikTokAppAwemeAddedSoundMusicInfoExternalSongInfo[];
  extra: string;
  id: number | string;
  id_str: string;
  is_author_artist: boolean;
  is_commerce_music: boolean;
  is_original: boolean;
  is_pgc: boolean;
  lyric_short_position: string | null;
  matched_pgc_sound?: TikTokAppAwemeAddedSoundMusicInfoMatchedPgcSound;
  mid: string;
  multi_bit_rate_play_info: string | null;
  mute_share: boolean;
  offline_desc: string;
  owner_handle: string;
  owner_id?: string;
  owner_nickname: string;
  play_url: TikTokAppAwemeAddedSoundMusicInfoPlayUrl;
  position: string | null;
  prevent_download: boolean;
  preview_end_time: number | string;
  preview_start_time: number | string;
  recommend_status: number | string;
  search_highlight: string | null;
  sec_uid?: string;
  source_platform: number | string;
  status: number | string;
  strong_beat_url?: TikTokAppAwemeAddedSoundMusicInfoStrongBeatUrl;
  tag_list: string | null;
  tag_list_v2: string | null;
  title: string;
  tt_to_dsp_song_infos: string | null;
  uncert_artists: string | null;
  user_count: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoAvatarMedium {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoAvatarThumb {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoCoverLarge {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoCoverMedium {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoCoverThumb {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoExternalSongInfo {
  external_song_key: string;
  h5_url: string;
  partner_name: string;
  partner_song_id: string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoMatchedPgcSound {
  artist_infos: string | null;
  author?: string;
  mixed_author?: string;
  mixed_title?: string;
  title?: string;
  uncert_artists: string | null;
}

export interface TikTokAppAwemeAddedSoundMusicInfoPlayUrl {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_key?: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAddedSoundMusicInfoStrongBeatUrl {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAigcInfo {
  aigc_label_type: number | string;
}

export interface TikTokAppAwemeAnchors {
  actions: TikTokAppAwemeAnchorsActions[];
  anchor_strong: string | null;
  component_key: string;
  description: string;
  extra: string;
  general_type?: number | string;
  icon: TikTokAppAwemeAnchorsIcon;
  id: string;
  keyword: string;
  log_extra: string;
  schema: string;
  thumbnail: TikTokAppAwemeAnchorsThumbnail;
  type: number | string;
}

export interface TikTokAppAwemeAnchorsActions {
  action_type: number | string;
  icon: TikTokAppAwemeAnchorsActionsIcon;
  schema: string;
}

export interface TikTokAppAwemeAnchorsActionsIcon {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAnchorsIcon {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAnchorsThumbnail {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAnimatedImageInfo {
  effect: number | string;
  type: number | string;
}

export interface TikTokAppAwemeAuthor {
  account_labels?: string | null;
  ad_cover_url?: string | null;
  advance_feature_item_order?: string | null;
  advanced_feature_info?: string | null;
  authority_status?: number | string;
  avatar_168x168?: TikTokAppAwemeAuthorAvatar168x168;
  avatar_300x300?: TikTokAppAwemeAuthorAvatar300x300;
  avatar_medium: TikTokAppAwemeAuthorAvatarMedium;
  avatar_thumb: TikTokAppAwemeAuthorAvatarThumb;
  bold_fields?: string | null;
  can_message_follow_status_list?: string | null;
  can_set_geofencing?: string | null;
  cha_list?: string | null;
  comment_filter_status?: number | string;
  comment_setting?: number | string;
  commerce_user_level?: number | string;
  cover_url?: string[];
  custom_verify?: string;
  download_setting?: number | string;
  duet_setting?: number | string;
  enterprise_verify_reason?: string;
  events?: string | null;
  follow_status?: number | string;
  follower_status?: number | string;
  followers_detail?: string | null;
  geofencing?: string | null;
  homepage_bottom_toast?: string | null;
  is_ad_fake?: boolean;
  is_block?: boolean;
  is_discipline_member?: boolean;
  is_star?: boolean;
  item_list?: string | null;
  language?: string;
  matched_friend?: TikTokAppAwemeAuthorMatchedFriend;
  mutual_relation_avatars?: string | null;
  need_points?: string | null;
  nickname: string;
  platform_sync_info?: string | null;
  prevent_download?: boolean;
  qa_status?: number | string;
  region?: string;
  relative_users?: string | null;
  room_id?: number | string;
  search_highlight?: string | null;
  sec_uid?: string;
  secret?: number | string;
  share_info?: TikTokAppAwemeAuthorShareInfo;
  shield_edit_field_info?: string | null;
  short_id?: string;
  signature?: string;
  social_info?: string;
  type_label?: string[];
  uid: string;
  unique_id: string;
  user_profile_guide?: string | null;
  user_tags?: string | null;
  verification_type?: number | string;
  verify_info?: string;
  video_icon?: TikTokAppAwemeAuthorVideoIcon;
  white_cover_url?: string | null;
  with_commerce_entry?: boolean;
}

export interface TikTokAppAwemeAuthorAvatar168x168 {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAuthorAvatar300x300 {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAuthorAvatarMedium {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAuthorAvatarThumb {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAuthorMatchedFriend {
  repost_items: string | null;
  video_items: string | null;
}

export interface TikTokAppAwemeAuthorShareInfo {
  now_invitation_card_image_urls: string | null;
  share_desc: string;
  share_desc_info: string;
  share_qrcode_url: TikTokAppAwemeAuthorShareInfoShareQrcodeUrl;
  share_title: string;
  share_title_myself: string;
  share_title_other: string;
  share_url: string;
}

export interface TikTokAppAwemeAuthorShareInfoShareQrcodeUrl {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAuthorVideoIcon {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeAwemeAcl {
  download_general: TikTokAppAwemeAwemeAclDownloadGeneral;
  download_mask_panel: TikTokAppAwemeAwemeAclDownloadMaskPanel;
  platform_list: string | null;
  press_action_list: string | null;
  share_action_list: string | null;
  share_general: TikTokAppAwemeAwemeAclShareGeneral;
  share_list_status: number | string;
}

export interface TikTokAppAwemeAwemeAclDownloadGeneral {
  code: number | string;
  extra?: string;
  mute: boolean;
  show_type: number | string;
  transcode: number | string;
}

export interface TikTokAppAwemeAwemeAclDownloadMaskPanel {
  code: number | string;
  extra?: string;
  mute: boolean;
  show_type: number | string;
  transcode: number | string;
}

export interface TikTokAppAwemeAwemeAclShareGeneral {
  code: number | string;
  extra?: string;
  mute: boolean;
  show_type: number | string;
  toast_msg?: string;
  transcode: number | string;
}

export interface TikTokAppAwemeBanners {
  key: TikTokAppAwemeBannersKey;
}

export interface TikTokAppAwemeBannersKey {
  component_key: string;
}

export interface TikTokAppAwemeChaList {
  author: TikTokAppAwemeChaListAuthor;
  banner_list: string | null;
  cha_attrs: string | null;
  cha_name: string;
  cid: string;
  collect_stat: number | string;
  connect_music: string[];
  desc: string;
  is_challenge: number | string;
  is_commerce: boolean;
  is_pgcshow: boolean;
  schema: string;
  search_highlight: string | null;
  share_info: TikTokAppAwemeChaListShareInfo;
  show_items: string | null;
  sub_type: number | string;
  type: number | string;
  user_count: number | string;
  view_count: number | string;
}

export interface TikTokAppAwemeChaListAuthor {
  account_labels: string | null;
  ad_cover_url: string | null;
  advance_feature_item_order: string | null;
  advanced_feature_info: string | null;
  bold_fields: string | null;
  can_message_follow_status_list: string | null;
  can_set_geofencing: string | null;
  cha_list: string | null;
  cover_url: string | null;
  events: string | null;
  followers_detail: string | null;
  geofencing: string | null;
  homepage_bottom_toast: string | null;
  item_list: string | null;
  mutual_relation_avatars: string | null;
  need_points: string | null;
  platform_sync_info: string | null;
  relative_users: string | null;
  search_highlight: string | null;
  shield_edit_field_info: string | null;
  type_label: string | null;
  user_profile_guide: string | null;
  user_tags: string | null;
  white_cover_url: string | null;
}

export interface TikTokAppAwemeChaListShareInfo {
  bool_persist: number | string;
  now_invitation_card_image_urls: string | null;
  share_desc: string;
  share_desc_info: string;
  share_quote: string;
  share_signature_desc: string;
  share_signature_url: string;
  share_title: string;
  share_title_myself: string;
  share_title_other: string;
  share_url: string;
}

export interface TikTokAppAwemeCommentConfig {
  comment_panel_show_tab_config: string | null;
  emoji_recommend_list: TikTokAppAwemeCommentConfigEmojiRecommendList[];
  long_press_recommend_list: string | null;
  quick_comment_emoji_recommend_list: string | null;
}

export interface TikTokAppAwemeCommentConfigEmojiRecommendList {
  emoji: string;
  emoji_id: string;
  emoji_id_score: number | string;
  score: number | string;
}

export interface TikTokAppAwemeCommerceInfo {
  adv_promotable: boolean;
  branded_content_type: number | string;
  is_diversion_ad: number | string;
}

export interface TikTokAppAwemeContentDescExtra {
  end: number | string;
  hashtag_id?: string;
  hashtag_name?: string;
  is_commerce?: boolean;
  line_idx: number | string;
  sec_uid?: string;
  start: number | string;
  type: number | string;
  user_id?: string;
}

export interface TikTokAppAwemeImagePostInfo {
  image_post_cover: TikTokAppAwemeImagePostInfoImagePostCover;
  images: TikTokAppAwemeImagePostInfoImages[];
  post_extra: string;
  title: string;
}

export interface TikTokAppAwemeImagePostInfoImagePostCover {
  bitrate_images: string | null;
  display_image: TikTokAppAwemeImagePostInfoImagePostCoverDisplayImage;
  owner_watermark_image: TikTokAppAwemeImagePostInfoImagePostCoverOwnerWatermarkImage;
  thumbnail: TikTokAppAwemeImagePostInfoImagePostCoverThumbnail;
  user_watermark_image: TikTokAppAwemeImagePostInfoImagePostCoverUserWatermarkImage;
}

export interface TikTokAppAwemeImagePostInfoImagePostCoverDisplayImage {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagePostCoverOwnerWatermarkImage {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagePostCoverThumbnail {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagePostCoverUserWatermarkImage {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImages {
  bitrate_images: string | null;
  display_image: TikTokAppAwemeImagePostInfoImagesDisplayImage;
  owner_watermark_image: TikTokAppAwemeImagePostInfoImagesOwnerWatermarkImage;
  thumbnail: TikTokAppAwemeImagePostInfoImagesThumbnail;
  user_watermark_image: TikTokAppAwemeImagePostInfoImagesUserWatermarkImage;
}

export interface TikTokAppAwemeImagePostInfoImagesDisplayImage {
  data_size: number | string;
  height: number | string;
  preview?: TikTokAppAwemeImagePostInfoImagesDisplayImagePreview;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagesDisplayImagePreview {
  data: string;
  preview_type: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagesOwnerWatermarkImage {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagesThumbnail {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeImagePostInfoImagesUserWatermarkImage {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeInteractPermission {
  allow_adding_to_story: number | string;
  allow_create_sticker: TikTokAppAwemeInteractPermissionAllowCreateSticker;
  duet: number | string;
  duet_privacy_setting: number | string;
  stitch: number | string;
  stitch_privacy_setting: number | string;
  upvote: number | string;
}

export interface TikTokAppAwemeInteractPermissionAllowCreateSticker {
  status: number | string;
}

export interface TikTokAppAwemeInteractionStickers {
  attr: string;
  index: number | string;
  text_info?: string;
  text_sticker_info?: TikTokAppAwemeInteractionStickersTextStickerInfo;
  track_info: string;
  type: number | string;
}

export interface TikTokAppAwemeInteractionStickersTextStickerInfo {
  alignment: number | string;
  bg_color: string;
  source_height: number | string;
  source_width: number | string;
  text_color: string;
  text_language: string;
  text_size: number | string;
}

export interface TikTokAppAwemeLabelTop {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeLogInfo {
  order: string;
}

export interface TikTokAppAwemeMusic {
  album: string;
  allow_offline_music_to_detail_page?: boolean;
  artists: string | null;
  author: string;
  author_deleted: boolean;
  author_position: string | null;
  avatar_large?: TikTokAppAwemeMusicAvatarLarge;
  avatar_medium?: TikTokAppAwemeMusicAvatarMedium;
  avatar_thumb?: TikTokAppAwemeMusicAvatarThumb;
  binded_challenge_id: number | string;
  collect_stat: number | string;
  cover_hd?: TikTokAppAwemeMusicCoverHd;
  cover_large: TikTokAppAwemeMusicCoverLarge;
  cover_medium: TikTokAppAwemeMusicCoverMedium;
  cover_thumb: TikTokAppAwemeMusicCoverThumb;
  duration: number | string;
  end_time?: number | string;
  external_song_info: TikTokAppAwemeMusicExternalSongInfo[];
  extra: string;
  id: number | string;
  id_str: string;
  is_author_artist: boolean;
  is_commerce_music: boolean;
  is_del_video?: boolean;
  is_original: boolean;
  is_pgc: boolean;
  is_restricted?: boolean;
  is_video_self_see?: boolean;
  lyric_short_position: string | null;
  matched_pgc_sound?: TikTokAppAwemeMusicMatchedPgcSound;
  mid: string;
  multi_bit_rate_play_info: string | null;
  mute_share: boolean;
  offline_desc: string;
  owner_handle: string;
  owner_id?: string;
  owner_nickname: string;
  play_url: TikTokAppAwemeMusicPlayUrl;
  position: string | null;
  prevent_download: boolean;
  prevent_item_download_status?: number | string;
  preview_end_time: number | string;
  preview_start_time: number | string;
  recommend_status: number | string;
  redirect?: boolean;
  schema_url?: string;
  search_highlight: string | null;
  sec_uid?: string;
  source_platform: number | string;
  start_time?: number | string;
  status: number | string;
  strong_beat_url?: TikTokAppAwemeMusicStrongBeatUrl;
  tag_list: string | null;
  tag_list_v2: string | null;
  title: string;
  tt_to_dsp_song_infos: string | null;
  uncert_artists: string | null;
  user_count: number | string;
}

export interface TikTokAppAwemeMusicAvatarLarge {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicAvatarMedium {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicAvatarThumb {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicCoverHd {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicCoverLarge {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicCoverMedium {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicCoverThumb {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicExternalSongInfo {
  external_song_key: string;
  h5_url: string;
  partner_name: string;
  partner_song_id: string;
}

export interface TikTokAppAwemeMusicMatchedPgcSound {
  artist_infos: string | null;
  author?: string;
  mixed_author?: string;
  mixed_title?: string;
  title?: string;
  uncert_artists: string | null;
}

export interface TikTokAppAwemeMusicPlayUrl {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_key?: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeMusicStrongBeatUrl {
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeOriginalClientText {
  markup_text: string;
  text_extra: TikTokAppAwemeOriginalClientTextTextExtra[] | null;
}

export interface TikTokAppAwemeOriginalClientTextTextExtra {
  hashtag_id?: string;
  hashtag_name?: string;
  is_commerce?: boolean;
  sec_uid?: string;
  tag_id: string;
  type: number | string;
  user_id?: string;
}

export interface TikTokAppAwemePlaylistInfo {
  index: number | string;
  item_total: number | string;
  mix_id: string;
  name: string;
}

export interface TikTokAppAwemePoiData {
  address_info: TikTokAppAwemePoiDataAddressInfo;
  collect_info: string;
  comment_anchor?: TikTokAppAwemePoiDataCommentAnchor;
  info_source: string;
  poi_id: string;
  poi_mapkit_collect: boolean;
  poi_name: string;
  poi_review_config?: TikTokAppAwemePoiDataPoiReviewConfig;
  poi_type: string;
  video_anchor?: TikTokAppAwemePoiDataVideoAnchor;
  video_count: number | string;
}

export interface TikTokAppAwemePoiDataAddressInfo {
  city_code: string;
  city_name: string;
  lat: string;
  lng: string;
  region_code: string;
}

export interface TikTokAppAwemePoiDataCommentAnchor {
  has_sub_arrow: boolean;
  hide_list: string | null;
  sub_tag_exp_time: number | string;
  sub_tag_exp_type: number | string;
  sub_tags: TikTokAppAwemePoiDataCommentAnchorSubTags[];
  track_info: string;
}

export interface TikTokAppAwemePoiDataCommentAnchorSubTags {
  name: string;
  priority: number | string;
  type: number | string;
}

export interface TikTokAppAwemePoiDataPoiReviewConfig {
  show_review_tab: boolean;
}

export interface TikTokAppAwemePoiDataVideoAnchor {
  has_sub_arrow: boolean;
  hide_list: string | null;
  sub_tag_exp_time: number | string;
  sub_tag_exp_type: number | string;
  sub_tags: TikTokAppAwemePoiDataVideoAnchorSubTags[];
  suffix: string;
  track_info: string;
}

export interface TikTokAppAwemePoiDataVideoAnchorSubTags {
  name: string;
  priority: number | string;
  type: number | string;
}

export interface TikTokAppAwemeRiskInfos {
  content: string;
  risk_sink: boolean;
  type: number | string;
  vote: boolean;
  warn: boolean;
}

export interface TikTokAppAwemeShareInfo {
  bool_persist: number | string;
  button_display_stratege_source?: string;
  now_invitation_card_image_urls: string | null;
  share_button_display_mode?: number | string;
  share_desc: string;
  share_desc_info: string;
  share_link_desc: string;
  share_quote: string;
  share_signature_desc: string;
  share_signature_url: string;
  share_title: string;
  share_title_myself: string;
  share_title_other: string;
  share_url: string;
  share_weibo_desc?: string;
  whatsapp_desc?: string;
}

export interface TikTokAppAwemeSmartSearchInfo {
  ask_tako_intent_type: number | string;
  find_similar_intent_type: number | string;
  related_videos_intent_type: number | string;
  title_smart_search_panel_type: number | string;
}

export interface TikTokAppAwemeStandardComponentInfo {
  banner_enabled?: boolean;
}

export interface TikTokAppAwemeStatistics {
  aweme_id: string;
  collect_count: number | string;
  comment_count: number | string;
  digg_count: number | string;
  download_count: number | string;
  forward_count: number | string;
  lose_comment_count: number | string;
  lose_count: number | string;
  play_count: number | string;
  repost_count: number | string;
  share_count: number | string;
  whatsapp_share_count: number | string;
}

export interface TikTokAppAwemeStatus {
  allow_comment: boolean;
  allow_share: boolean;
  aweme_id: string;
  download_status: number | string;
  in_reviewing: boolean;
  is_delete: boolean;
  is_prohibited: boolean;
  private_status: number | string;
  reviewed: number | string;
  self_see: boolean;
}

export interface TikTokAppAwemeStickerDetail {
  attributions: string | null;
  children: string | null;
  id: string;
  linked_anchors: string | null;
  name: string;
  owner_id: string;
  sec_uid: string;
  tags: string | null;
}

export interface TikTokAppAwemeSuggestWords {
  suggest_words: TikTokAppAwemeSuggestWordsSuggestWords[];
}

export interface TikTokAppAwemeSuggestWordsSuggestWords {
  hint_text: string;
  qrec_virtual_enable: string;
  scene: string;
  words: TikTokAppAwemeSuggestWordsSuggestWordsWords[];
}

export interface TikTokAppAwemeSuggestWordsSuggestWordsWords {
  word: string;
  word_id: string;
}

export interface TikTokAppAwemeTakoBubbleInfo {
  tako_bubble_enable: boolean;
}

export interface TikTokAppAwemeTextExtra {
  end: number | string;
  hashtag_id?: string;
  hashtag_name?: string;
  is_commerce?: boolean;
  line_idx: number | string;
  sec_uid?: string;
  start: number | string;
  type: number | string;
  user_id?: string;
}

export interface TikTokAppAwemeTtecSuggestWords {
  ttec_suggest_words: string | null;
}

export interface TikTokAppAwemeVideo {
  CoverTsp?: number | string;
  big_thumbs?: string | null;
  bit_rate: TikTokAppAwemeVideoBitRate[];
  bit_rate_audio?: TikTokAppAwemeVideoBitRateAudio[] | null;
  cdn_url_expired?: number | string;
  cla_info?: TikTokAppAwemeVideoClaInfo;
  cover: TikTokAppAwemeVideoCover;
  cover_is_custom?: boolean;
  download_addr?: TikTokAppAwemeVideoDownloadAddr;
  duration: number | string;
  dynamic_cover: TikTokAppAwemeVideoDynamicCover;
  fake_landscape_video_info?: TikTokAppAwemeVideoFakeLandscapeVideoInfo;
  has_watermark: boolean;
  height?: number | string;
  is_bytevc1?: number | string;
  meta?: string;
  misc_download_addrs?: string;
  need_set_token?: boolean;
  origin_cover: TikTokAppAwemeVideoOriginCover;
  pillar_box_video_info?: TikTokAppAwemeVideoPillarBoxVideoInfo;
  play_addr: TikTokAppAwemeVideoPlayAddr;
  play_addr_bytevc1?: TikTokAppAwemeVideoPlayAddrBytevc1;
  play_addr_h264?: TikTokAppAwemeVideoPlayAddrH264;
  ratio?: string;
  source_HDR_type?: number | string;
  tags?: string | null;
  width?: number | string;
}

export interface TikTokAppAwemeVideoBitRate {
  HDR_bit: string;
  HDR_type: string;
  bit_rate: number | string;
  dub_infos: string | null;
  gear_name: string;
  is_bytevc1: number | string;
  is_h265?: number | string;
  play_addr: TikTokAppAwemeVideoBitRatePlayAddr;
  quality_type: number | string;
}

export interface TikTokAppAwemeVideoBitRateAudio {
  audio_meta: TikTokAppAwemeVideoBitRateAudioAudioMeta;
  audio_quality: number | string;
}

export interface TikTokAppAwemeVideoBitRateAudioAudioMeta {
  bitrate: number | string;
  codec_type: string;
  encoded_type: string;
  file_hash: string;
  file_id: string;
  format: string;
  fps: number | string;
  logo_type: string;
  media_type: string;
  quality: string;
  quality_desc: string;
  size: number | string;
  sub_info: string;
  url_list: TikTokAppAwemeVideoBitRateAudioAudioMetaUrlList;
}

export interface TikTokAppAwemeVideoBitRateAudioAudioMetaUrlList {
  backup_url: string;
  fallback_url: string;
  main_url: string;
}

export interface TikTokAppAwemeVideoBitRatePlayAddr {
  data_size: number | string;
  file_hash: string;
  height: number | string;
  uri: string;
  url_key: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoClaInfo {
  caption_infos: TikTokAppAwemeVideoClaInfoCaptionInfos[] | null;
  captions_type: number | string;
  creator_edited_caption_id: number | string;
  enable_auto_caption: number | string;
  has_original_audio: number | string;
  hide_original_caption: boolean;
  no_caption_reason: number | string;
  no_caption_reason_v2: number | string;
  original_language_info?: TikTokAppAwemeVideoClaInfoOriginalLanguageInfo;
  vertical_positions: string | null;
}

export interface TikTokAppAwemeVideoClaInfoCaptionInfos {
  caption_format: string;
  caption_length: number | string;
  cla_subtitle_id: number | string;
  complaint_id: number | string;
  expire: number | string;
  is_auto_generated: boolean;
  is_original_caption: boolean;
  lang: string;
  language_code: string;
  language_id: number | string;
  sub_id: number | string;
  sub_version: string;
  url: string;
  url_list: string[];
}

export interface TikTokAppAwemeVideoClaInfoOriginalLanguageInfo {
  can_translate_realtime: boolean;
  can_translate_realtime_skip_translation_lang_check: boolean;
  is_burnin_caption: boolean;
  lang: string;
  language_code: string;
  language_id: number | string;
  original_caption_type: number | string;
}

export interface TikTokAppAwemeVideoControl {
  allow_download: boolean;
  allow_duet: boolean;
  allow_dynamic_wallpaper: boolean;
  allow_music: boolean;
  allow_react: boolean;
  allow_stitch: boolean;
  draft_progress_bar: number | string;
  prevent_download_type: number | string;
  share_type: number | string;
  show_progress_bar: number | string;
  timer_status: number | string;
}

export interface TikTokAppAwemeVideoCover {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoDownloadAddr {
  data_size?: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoDynamicCover {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoFakeLandscapeVideoInfo {
  bottom: number | string;
  fake_landscape_video_type: number | string;
  left: number | string;
  right: number | string;
  top: number | string;
}

export interface TikTokAppAwemeVideoOriginCover {
  data_size: number | string;
  height: number | string;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoPillarBoxVideoInfo {
  bottom: number | string;
  left: number | string;
  right: number | string;
  top: number | string;
  version: string;
}

export interface TikTokAppAwemeVideoPlayAddr {
  data_size?: number | string;
  file_hash?: string;
  height: number | string;
  uri: string;
  url_key: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoPlayAddrBytevc1 {
  data_size: number | string;
  file_hash: string;
  height: number | string;
  uri: string;
  url_key: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVideoPlayAddrH264 {
  data_size: number | string;
  file_hash: string;
  height: number | string;
  uri: string;
  url_key: string;
  url_list: string[];
  url_prefix: string | null;
  width: number | string;
}

export interface TikTokAppAwemeVisualSearchInfo {
  api_control_info?: string;
  disable_ecom_content_type?: number | string;
  ecom_nocart_entrance_enable_type?: number | string;
  enable_pre_upload_image_type: number | string;
  fallback_vtag_enable: boolean;
  fallback_vtag_enable_type: number | string;
  fallback_vtag_info?: TikTokAppAwemeVisualSearchInfoFallbackVtagInfo;
  intent?: number | string;
  long_press_entrance_enable: boolean;
  long_press_entrance_enable_type: number | string;
  screenshot_entrance_enable: number | string;
  visual_search_intent_level: number | string;
  visual_search_record?: TikTokAppAwemeVisualSearchInfoVisualSearchRecord;
  vtag_display_limit?: number | string;
  vtag_enable: boolean;
  vtag_enable_type: number | string;
  vtag_info?: TikTokAppAwemeVisualSearchInfoVtagInfo[];
}

export interface TikTokAppAwemeVisualSearchInfoFallbackVtagInfo {
  fallback_vtag_action_type?: number | string;
  fallback_vtag_name?: string;
  fallback_vtag_type?: number | string;
  tag_type?: string;
}

export interface TikTokAppAwemeVisualSearchInfoVisualSearchRecord {
  intent_v1_category: number | string;
  item_extra_flags: string;
}

export interface TikTokAppAwemeVisualSearchInfoVtagInfo {
  bbox: TikTokAppAwemeVisualSearchInfoVtagInfoBbox;
  dynamic_frame_info_list?: TikTokAppAwemeVisualSearchInfoVtagInfoDynamicFrameInfoList[];
  end: number | string;
  start: number | string;
  tag_coord: TikTokAppAwemeVisualSearchInfoVtagInfoTagCoord;
  tag_name: string;
  tag_position_type: string;
  tag_subtype: string;
  tag_type: string;
  tag_uid: string;
  unified_tag_id: string;
}

export interface TikTokAppAwemeVisualSearchInfoVtagInfoBbox {
  xmax: number | string;
  xmin: number | string;
  ymax: number | string;
  ymin: number | string;
}

export interface TikTokAppAwemeVisualSearchInfoVtagInfoDynamicFrameInfoList {
  bbox: TikTokAppAwemeVisualSearchInfoVtagInfoDynamicFrameInfoListBbox;
  frame_time: number | string;
}

export interface TikTokAppAwemeVisualSearchInfoVtagInfoDynamicFrameInfoListBbox {
  xmax: number | string;
  xmin: number | string;
  ymax: number | string;
  ymin: number | string;
}

export interface TikTokAppAwemeVisualSearchInfoVtagInfoTagCoord {
  x: number | string;
  y: number | string;
}

export interface TikTokAweme {
  author: TikTokUser;
  author_user_id: number | string;
  aweme_id: string;
  cha_list: TikTokChallengeTag[];
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  desc_language?: string;
  group_id: string;
  image_post_info?: TikTokImagePostInfo;
  is_ad: boolean;
  music: TikTokAwemeMusic;
  statistics: TikTokAwemeStatistics;
  text_extra: TikTokTextExtra[];
  url: string;
  video: TikTokAwemeVideo;
}

export interface TikTokAwemeMusic {
  album: string;
  author?: string;
  cover_large: TikTokUrlImage;
  cover_medium: TikTokUrlImage;
  cover_thumb: TikTokUrlImage;
  duration?: number | string;
  id: number | string;
  id_str: string;
  is_commerce_music?: boolean;
  is_original: boolean;
  mid: string;
  play_url: TikTokUrlImage;
  title: string;
}

export interface TikTokAwemeStatistics {
  aweme_id: string;
  collect_count: number | string;
  comment_count: number | string;
  digg_count: number | string;
  play_count: number | string;
  repost_count?: number | string;
  share_count: number | string;
}

export interface TikTokAwemeVideo {
  bit_rate: TikTokBitRate[];
  cla_info?: TikTokClaInfo;
  cover: TikTokUrlImage;
  download_addr?: TikTokUrlImage;
  duration: number | string;
  dynamic_cover?: TikTokUrlImage;
  height: number | string;
  is_bytevc1: number | string;
  origin_cover: TikTokUrlImage;
  play_addr?: TikTokPlayAddr;
  play_addr_bytevc1?: TikTokPlayAddr;
  play_addr_h264?: TikTokPlayAddr;
  ratio: string;
  width: number | string;
}

export interface TikTokBitRate {
  bit_rate: number | string;
  fps?: number | string;
  gear_name: string;
  is_bytevc1: number | string;
  play_addr: TikTokPlayAddr;
  quality_type: number | string;
  video_extra?: string;
}

export interface TikTokCaptionInfo {
  caption_format: string;
  cla_subtitle_id: number | string;
  expire: number | string;
  is_auto_generated: boolean;
  is_original_caption: boolean;
  lang: string;
  language_code: string;
  language_id: number | string;
  sub_id: number | string;
  subtitle_type: number | string;
  translation_type: number | string;
  url: string;
  url_list: string[];
  variant: string;
}

export interface TikTokChallengeTag {
  cha_name: string;
  cid: string;
  desc: string;
}

export interface TikTokClaInfo {
  caption_infos: TikTokCaptionInfo[];
  captions_type?: number | string;
  enable_auto_caption: number | string;
  has_original_audio: number | string;
  no_caption_reason?: number | string;
  original_language_info?: TikTokOriginalLanguageInfo;
}

export interface TikTokCollectionVideosResponse {
  collection_id: string;
  credits_charged: number | string;
  credits_remaining: number | string;
  has_more: boolean;
  max_cursor: string;
  status_code: number | string;
  status_msg: string;
  success: boolean;
  videos: TikTokWebItem[];
}

export interface TikTokComment {
  allow_download_photo?: boolean;
  author_pin?: boolean;
  aweme_id: string;
  cid: string;
  collect_stat: number | string;
  comment_language: string;
  comment_post_item_ids: string | null;
  create_time: number | string;
  digg_count: number | string;
  fold_status: number | string;
  image_list: string | null;
  is_author_digged: boolean;
  is_comment_translatable: boolean;
  is_high_purchase_intent: boolean;
  label_list: string | null;
  no_show: boolean;
  reply_comment: string | null;
  reply_comment_total?: number | string;
  reply_id: string;
  reply_to_nickname?: string;
  reply_to_reply_id: string;
  reply_to_userid?: string;
  reply_to_username?: string;
  seeking_help_model_type: number | string;
  share_info: TikTokCommentShareInfo;
  sort_extra_score?: TikTokCommentSortExtraScore;
  sort_tags?: string;
  status: number | string;
  stick_position: number | string;
  text: string;
  text_extra: TikTokCommentTextExtra[];
  text_to_image_item_ids: string | null;
  thread_has_more: boolean;
  thread_id: number | string;
  trans_btn_style: number | string;
  translated_text_extra: string | null;
  user: TikTokCommentUser;
  user_buried: boolean;
  user_digged: number | string;
}

export interface TikTokCommentPageExtra {
  api_debug_info: string | null;
  fatal_item_ids: string | null;
  now: number | string;
}

export interface TikTokCommentPageLogPb {
  impr_id: string;
}

export interface TikTokCommentRepliesResponse {
  comments: TikTokComment[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  extra: TikTokCommentReplyPageExtra;
  has_more: number | string;
  log_pb: TikTokCommentReplyPageLogPb;
  status_code: number | string;
  status_msg: string;
  success: boolean;
  total: number | string;
}

export interface TikTokCommentReplyPageExtra {
  fatal_item_ids: string[];
  logid: string;
  now: number | string;
}

export interface TikTokCommentReplyPageLogPb {
  impr_id: string;
}

export interface TikTokCommentShareInfo {
  acl: TikTokCommentShareInfoAcl;
  desc: string;
  title: string;
  url: string;
}

export interface TikTokCommentShareInfoAcl {
  add_to_story_code: number | string;
  code: number | string;
  extra: string;
}

export interface TikTokCommentSortExtraScore {
  reply_score: number | string;
  show_more_score: number | string;
}

export interface TikTokCommentTextExtra {
  emoji_id: string;
  end: number | string;
  group_id: number | string;
  group_name: string;
  group_scene: string;
  hashtag_id: string;
  hashtag_name: string;
  product_id: number | string;
  product_schema: string;
  product_title: string;
  sec_uid: string;
  start: number | string;
  type: number | string;
  user_id: string;
}

export interface TikTokCommentUser {
  account_labels: string | null;
  ad_cover_url: string | null;
  advance_feature_item_order: string | null;
  advanced_feature_info: string | null;
  avatar_thumb: TikTokCommentUserAvatarThumb;
  bold_fields: string | null;
  can_message_follow_status_list: string | null;
  can_set_geofencing: string | null;
  cha_list: string | null;
  cover_url: string | null;
  custom_verify: string;
  enterprise_verify_reason: string;
  events: string | null;
  followers_detail: string | null;
  geofencing: string | null;
  homepage_bottom_toast: string | null;
  item_list: string | null;
  mutual_relation_avatars: string | null;
  need_points: string | null;
  nickname: string;
  platform_sync_info: string | null;
  predicted_age_group?: string;
  relative_users: string | null;
  search_highlight: string | null;
  sec_uid: string;
  shield_edit_field_info: string | null;
  type_label: string | null;
  uid: string;
  unique_id: string;
  user_profile_guide: string | null;
  user_tags: string | null;
  white_cover_url: string | null;
}

export interface TikTokCommentUserAvatarThumb {
  uri: string;
  url_list: string[];
  url_prefix: string | null;
}

export interface TikTokCommentsResponse {
  alias_comment_deleted: boolean;
  comments: TikTokComment[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  extra: TikTokCommentPageExtra;
  has_filtered_comments: number | string;
  has_more: number | string;
  log_pb: TikTokCommentPageLogPb;
  reply_style: number | string;
  status_code: number | string;
  status_msg: string;
  success: boolean;
  top_gifts: string | null;
  total: number | string;
}

export interface TikTokFollowersResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  followers: TikTokUser[];
  has_more: boolean;
  min_time: number | string;
  status_code: number | string;
  success: boolean;
  total: number | string;
}

export interface TikTokFollowingResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  followings: TikTokUser[];
  has_more: boolean;
  min_time: number | string;
  status_code: number | string;
  success: boolean;
  total: number | string;
}

export interface TikTokHashtagSearchResponse {
  aweme_list: TikTokAweme[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  has_more: number | string;
  status_code: number | string;
  success: boolean;
}

export interface TikTokImagePostImage {
  display_image: TikTokSizedImage;
}

export interface TikTokImagePostInfo {
  images: TikTokImagePostImage[];
  title: string;
}

export interface TikTokOriginalLanguageInfo {
  lang: string;
  language_code: string;
  language_id: number | string;
}

export interface TikTokPlayAddr {
  data_size: number | string;
  file_cs: string;
  file_hash: string;
  height: number | string;
  uri: string;
  url_key: string;
  url_list: string[];
  width: number | string;
}

export interface TikTokProfileResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  itemList: string[];
  stats: TikTokUserInfoStats;
  statsV2: TikTokUserInfoStatsV2;
  success: boolean;
  user: TikTokUserInfoUser;
}

export interface TikTokProfileVideosResponse {
  aweme_list: TikTokAweme[];
  credits_charged: number | string;
  credits_remaining: number | string;
  has_more: number | string;
  max_cursor: number | string;
  status_code: number | string;
  success: boolean;
}

export interface TikTokSearchSuggestion {
  language: string;
  position: number | string;
  score: number | string;
  text: string;
}

export interface TikTokSearchSuggestionsResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  success: boolean;
  suggestions: TikTokSearchSuggestion[];
}

export interface TikTokSizedImage {
  height: number | string;
  uri: string;
  url_list: string[];
  width: number | string;
}

export interface TikTokSongMusicInfo {
  album: string;
  author: string;
  cover_large: TikTokUrlImage;
  cover_medium: TikTokUrlImage;
  cover_thumb: TikTokUrlImage;
  duration: number | string;
  id: number | string;
  id_str: string;
  is_commerce_music?: boolean;
  is_original: boolean;
  mid: string;
  play_url: TikTokUrlImage;
  title: string;
  user_count: number | string;
}

export interface TikTokSongResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  music_info: TikTokSongMusicInfo;
  success: boolean;
}

export interface TikTokSongVideosResponse {
  aweme_list: TikTokAweme[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  has_more: number | string;
  status_code: number | string;
  success: boolean;
}

export interface TikTokTextExtra {
  end: number | string;
  hashtag_id?: string;
  hashtag_name: string;
  is_commerce: boolean;
  sec_uid?: string;
  start: number | string;
  sub_type: number | string;
  type: number | string;
  user_id?: string;
}

export interface TikTokTranscriptResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  id: string;
  success: boolean;
  transcript: string;
  url: string;
}

export interface TikTokTrendingAuthor {
  avatar_medium: TikTokAppAwemeAuthorAvatarMedium;
  avatar_thumb: TikTokAppAwemeAuthorAvatarThumb;
  nickname: string;
  uid: string;
  unique_id: string;
}

export interface TikTokTrendingFeedResponse {
  aweme_list: TikTokTrendingItem[];
  credits_charged: number | string;
  credits_remaining: number | string;
  success: boolean;
}

export interface TikTokTrendingItem {
  anchors: TikTokAppAwemeAnchors[] | null;
  author: TikTokTrendingAuthor;
  author_user_id: number | string;
  aweme_id: string;
  commerce_info: TikTokAppAwemeCommerceInfo;
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  is_ad: boolean;
  item_comment_settings: number | string;
  music: TikTokAppAwemeMusic;
  poi_data?: TikTokAppAwemePoiData;
  region: string;
  share_info: TikTokAppAwemeShareInfo;
  statistics: TikTokAppAwemeStatistics;
  url: string;
  video: TikTokTrendingVideo;
}

export interface TikTokTrendingVideo {
  bit_rate: TikTokAppAwemeVideoBitRate[];
  cover: TikTokAppAwemeVideoCover;
  download_addr?: TikTokAppAwemeVideoDownloadAddr;
  duration: number | string;
  dynamic_cover: TikTokAppAwemeVideoDynamicCover;
  has_watermark: boolean;
  origin_cover: TikTokAppAwemeVideoOriginCover;
  play_addr: TikTokAppAwemeVideoPlayAddr;
}

export interface TikTokTrimmedAweme {
  author: TikTokUser;
  aweme_id: string;
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  desc_language?: string;
  is_ad: boolean;
  statistics: TikTokAwemeStatistics;
  url: string;
  video: TikTokAwemeVideo;
}

export interface TikTokTrimmedComment {
  aweme_id: string;
  comment_language?: string;
  create_time: number | string;
  digg_count: number | string;
  reply_comment_total?: number | string;
  text: string;
  user: TikTokCommentUser;
}

export interface TikTokTrimmedCommentsResponse {
  comments: TikTokTrimmedComment[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  end_of_pagination: boolean;
  has_more: number | string;
  success: boolean;
  total: number | string;
}

export interface TikTokTrimmedFollowersResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  followers: TikTokTrimmedRelationUser[];
  min_time: number | string;
  success: boolean;
  total: number | string;
}

export interface TikTokTrimmedFollowingResponse {
  credits_charged: number | string;
  credits_remaining: number | string;
  followings: TikTokTrimmedRelationUser[];
  min_time: number | string;
  success: boolean;
  total: number | string;
}

export interface TikTokTrimmedHashtagSearchResponse {
  aweme_list: TikTokTrimmedAweme[];
  credits_charged: number | string;
  credits_remaining: number | string;
  cursor: number | string;
  success: boolean;
}

export interface TikTokTrimmedProfileVideosResponse {
  aweme_list: TikTokTrimmedAweme[];
  credits_charged: number | string;
  credits_remaining: number | string;
  has_more: number | string;
  max_cursor: number | string;
  success: boolean;
}

export interface TikTokTrimmedRelationUser {
  avatar_medium: TikTokUrlImage;
  follower_count?: number | string;
  following_count?: number | string;
  nickname: string;
  sec_uid: string;
  signature: string;
  uid: string;
  unique_id: string;
}

export interface TikTokTrimmedTrendingFeedResponse {
  aweme_list: TikTokTrimmedTrendingItem[];
  credits_charged: number | string;
  credits_remaining: number | string;
  success: boolean;
}

export interface TikTokTrimmedTrendingItem {
  author: TikTokTrendingAuthor;
  aweme_id: string;
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  is_ad: boolean;
  region: string;
  statistics: TikTokAppAwemeStatistics;
  url: string;
  video: TikTokTrendingVideo;
}

export interface TikTokTrimmedVideoAweme {
  author: TikTokAppAwemeAuthor;
  aweme_id: string;
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  is_ad: boolean;
  region: string;
  statistics: TikTokAppAwemeStatistics;
  url: string;
  video: TikTokAppAwemeVideo;
}

export interface TikTokTrimmedVideoResponse {
  aweme_detail: TikTokTrimmedVideoAweme;
  credits_charged: number | string;
  credits_remaining: number | string;
  success: boolean;
  transcript?: string | null;
}

export interface TikTokUrlImage {
  uri: string;
  url_list: string[];
}

export interface TikTokUser {
  avatar_larger: TikTokUrlImage;
  avatar_medium: TikTokUrlImage;
  avatar_thumb: TikTokUrlImage;
  aweme_count?: number | string;
  comment_setting?: number | string;
  download_setting: number | string;
  duet_setting?: number | string;
  favoriting_count?: number | string;
  follower_count?: number | string;
  following_count?: number | string;
  nickname: string;
  sec_uid: string;
  secret: number | string;
  signature: string;
  stitch_setting?: number | string;
  total_favorited?: number | string;
  uid: string;
  unique_id: string;
  verification_type: number | string;
}

export interface TikTokUserInfoStats {
  diggCount: number | string;
  followerCount: number | string;
  followingCount: number | string;
  friendCount: number | string;
  heart: number | string;
  heartCount: number | string;
  videoCount: number | string;
}

export interface TikTokUserInfoStatsV2 {
  diggCount: string;
  followerCount: string;
  followingCount: string;
  friendCount: string;
  heart: string;
  heartCount: string;
  videoCount: string;
}

export interface TikTokUserInfoUser {
  UserStoryStatus: number | string;
  avatarLarger: string;
  avatarMedium: string;
  avatarThumb: string;
  bioLink?: TikTokUserInfoUserBioLink;
  canExpPlaylist: boolean;
  commentSetting?: number | string;
  commerceUserInfo: TikTokUserInfoUserCommerceUserInfo;
  createTime: number | string;
  downloadSetting: number | string;
  duetSetting?: number | string;
  eventList?: string[];
  followingVisibility: number | string;
  ftc: boolean;
  id: string;
  isADVirtual: boolean;
  isEmbedBanned: boolean;
  isOrganization: number | string;
  language: string;
  nickNameModifyTime: number | string;
  nickname: string;
  nowInvitationCardUrl: string;
  openFavorite: boolean;
  privateAccount: boolean;
  profileEmbedPermission: number | string;
  profileTab: TikTokUserInfoUserProfileTab;
  recommendReason: string;
  relation: number | string;
  roomId: string;
  secUid: string;
  secret: boolean;
  shortDramaCreator: Record<string, string>;
  shortId: string;
  signature: string;
  stitchSetting?: number | string;
  suggestAccountBind: boolean;
  ttSeller: boolean;
  uniqueId: string;
  uniqueIdModifyTime: number | string;
  verified: boolean;
}

export interface TikTokUserInfoUserBioLink {
  link: string;
  risk: number | string;
}

export interface TikTokUserInfoUserCommerceUserInfo {
  category?: string;
  categoryButton?: boolean;
  commerceUser: boolean;
  downLoadLink?: TikTokUserInfoUserCommerceUserInfoDownLoadLink;
}

export interface TikTokUserInfoUserCommerceUserInfoDownLoadLink {
  android: string;
  ios: string;
}

export interface TikTokUserInfoUserProfileTab {
  showMusicTab: boolean;
  showPlayListTab: boolean;
  showQuestionTab: boolean;
}

export interface TikTokVideoAweme {
  add_yours_recommendation?: Record<string, string>;
  added_sound_music_info?: TikTokAppAwemeAddedSoundMusicInfo;
  aigc_info?: TikTokAppAwemeAigcInfo;
  anchors: TikTokAppAwemeAnchors[] | null;
  animated_image_info?: TikTokAppAwemeAnimatedImageInfo;
  author: TikTokAppAwemeAuthor;
  author_user_id: number | string;
  aweme_acl?: TikTokAppAwemeAwemeAcl;
  aweme_id: string;
  aweme_type?: number | string;
  banners?: TikTokAppAwemeBanners[] | null;
  batch_index?: number | string;
  behind_the_song_music_ids?: string | null;
  behind_the_song_video_music_ids?: string | null;
  bodydance_score?: number | string;
  bottom_products?: string | null;
  branded_content_accounts?: string | null;
  cha_list?: TikTokAppAwemeChaList[] | null;
  challenge_position?: string | null;
  cmt_swt?: boolean;
  collect_stat?: number | string;
  comment_config?: TikTokAppAwemeCommentConfig;
  comment_topbar_info?: string | null;
  commerce_config_data?: string | null;
  commerce_info: TikTokAppAwemeCommerceInfo;
  content_desc?: string;
  content_desc_extra?: TikTokAppAwemeContentDescExtra[];
  content_original_type?: number | string;
  content_size_type?: number | string;
  content_type?: string;
  cover_labels?: string | null;
  create_time: number | string;
  create_time_utc: string;
  desc: string;
  desc_language?: string;
  disable_search_trending_bar?: boolean;
  distance?: string;
  distribute_type?: number | string;
  ecosystem_perception_enhancement?: string | null;
  follow_up_first_item_id?: string;
  follow_up_item_id_groups?: string;
  follow_up_publish_from_id?: number | string;
  geofencing?: string | null;
  geofencing_regions?: string | null;
  green_screen_materials?: string | null;
  group_id?: string;
  has_danmaku?: boolean;
  has_vs_entry?: boolean;
  hybrid_label?: string | null;
  image_infos?: string | null;
  image_post_info?: TikTokAppAwemeImagePostInfo;
  interact_permission?: TikTokAppAwemeInteractPermission;
  interaction_stickers?: TikTokAppAwemeInteractionStickers[] | null;
  is_ad?: boolean;
  is_ads?: boolean;
  is_description_translatable?: boolean;
  is_hash_tag?: number | string;
  is_pgcshow?: boolean;
  is_relieve?: boolean;
  is_text_sticker_translatable?: boolean;
  is_top?: number | string;
  is_vr?: boolean;
  item_comment_settings: number | string;
  item_distribute_source?: string;
  item_duet?: number | string;
  item_react?: number | string;
  item_source_category?: number | string;
  label_top?: TikTokAppAwemeLabelTop;
  label_top_text?: string | null;
  log_info?: TikTokAppAwemeLogInfo;
  long_video?: string | null;
  main_arch_common?: string;
  mask_infos?: string[];
  misc_info?: string;
  muf_comment_info_v2?: string | null;
  music: TikTokAppAwemeMusic;
  music_begin_time_in_ms?: number | string;
  music_end_time_in_ms?: number | string;
  music_selected_from?: string;
  music_title_style?: number | string;
  music_volume?: string;
  need_vs_entry?: boolean;
  nickname_position?: string | null;
  operator_boost_info?: string | null;
  origin_comment_ids?: string | null;
  origin_volume?: string;
  original_client_text?: TikTokAppAwemeOriginalClientText;
  picked_users?: string | null;
  playlist_blocked?: boolean;
  playlist_info?: TikTokAppAwemePlaylistInfo;
  poi_data?: TikTokAppAwemePoiData;
  position?: string | null;
  prevent_download?: boolean;
  products_info?: string | null;
  question_list?: string | null;
  rate?: number | string;
  reference_tts_voice_ids?: string | null;
  reference_voice_filter_ids?: string | null;
  region: string;
  right_products?: string | null;
  risk_infos?: TikTokAppAwemeRiskInfos;
  search_highlight?: string | null;
  share_info: TikTokAppAwemeShareInfo;
  share_url?: string;
  shoot_tab_name?: string;
  smart_search_info?: TikTokAppAwemeSmartSearchInfo;
  sort_label?: string;
  sound_exemption?: number | string;
  standard_component_info?: TikTokAppAwemeStandardComponentInfo;
  statistics: TikTokAppAwemeStatistics;
  status?: TikTokAppAwemeStatus;
  sticker_detail?: TikTokAppAwemeStickerDetail;
  stickers?: string;
  suggest_words?: TikTokAppAwemeSuggestWords;
  support_danmaku?: boolean;
  survey_info?: string | null;
  tako_bubble_info?: TikTokAppAwemeTakoBubbleInfo;
  text_extra?: TikTokAppAwemeTextExtra[];
  text_sticker_major_lang?: string;
  ttec_suggest_words?: TikTokAppAwemeTtecSuggestWords;
  tts_voice_ids?: string[] | null;
  uniqid_position?: string | null;
  url: string;
  user_digged?: number | string;
  video: TikTokAppAwemeVideo;
  video_control?: TikTokAppAwemeVideoControl;
  video_labels?: string[];
  video_text?: string[];
  visual_search_info?: TikTokAppAwemeVisualSearchInfo;
  voice_filter_ids?: string | null;
  with_promotional_music?: boolean;
  with_survey?: boolean;
}

export interface TikTokVideoResponse {
  aweme_detail: TikTokVideoAweme;
  credits_charged: number | string;
  credits_remaining: number | string;
  success: boolean;
  transcript?: string | null;
}

export interface TikTokWebItem {
  AIGCDescription: string;
  AnchorTypes?: (number | string)[];
  BAInfo?: string;
  CategoryType: number | string;
  IsHDBitrate: boolean;
  ShowAIGC: boolean;
  adAuthorization?: boolean;
  adLabelVersion?: number | string;
  aigcLabelType?: number | string;
  anchors?: TikTokWebItemAnchors[];
  author: TikTokWebItemAuthor;
  authorStats: TikTokWebItemAuthorStats;
  authorStatsV2: TikTokWebItemAuthorStatsV2;
  backendSourceEventTracking: string;
  brandOrganicType?: number | string;
  challenges?: TikTokWebItemChallenges[];
  collected: boolean;
  contents?: TikTokWebItemContents[];
  createTime: number | string;
  creatorAIComment?: TikTokWebItemCreatorAIComment;
  desc: string;
  digged: boolean;
  diversificationId?: number | string;
  duetDisplay: number | string;
  duetEnabled?: boolean;
  effectStickers?: TikTokWebItemEffectStickers[];
  enterMdpPV?: number | string;
  forFriend: boolean;
  id: string;
  imagePost?: TikTokWebItemImagePost;
  isAd: boolean;
  isECVideo?: number | string;
  isPinnedItem?: boolean;
  isProhibited: boolean;
  isReviewing: boolean;
  itemCommentStatus: number | string;
  itemMute?: boolean;
  item_control: TikTokWebItemItemControl;
  maskType?: number | string;
  moderationAigcLabelType?: number | string;
  music: TikTokWebItemMusic;
  officalItem: boolean;
  originalItem: boolean;
  penaltyContext?: TikTokWebItemPenaltyContext;
  playlistId?: string;
  poi?: TikTokWebItemPoi;
  privateItem: boolean;
  secret: boolean;
  shareEnabled: boolean;
  stats: TikTokWebItemStats;
  statsV2: TikTokWebItemStatsV2;
  stickersOnItem?: TikTokWebItemStickersOnItem[];
  stitchDisplay: number | string;
  stitchEnabled?: boolean;
  textExtra?: TikTokWebItemTextExtra[];
  textLanguage: string;
  textTranslatable: boolean;
  titleLanguage?: string;
  titleTranslatable?: boolean;
  video: TikTokWebItemVideo;
  videoSuggestWordsList?: TikTokWebItemVideoSuggestWordsList;
  warnInfo?: TikTokWebItemWarnInfo[];
}

export interface TikTokWebItemAnchors {
  description?: string;
  extraInfo?: TikTokWebItemAnchorsExtraInfo;
  icon?: TikTokWebItemAnchorsIcon;
  id: string;
  keyword: string;
  logExtra?: string;
  schema?: string;
  thumbnail?: TikTokWebItemAnchorsThumbnail;
  type: number | string;
}

export interface TikTokWebItemAnchorsExtraInfo {
  subtype: string;
}

export interface TikTokWebItemAnchorsIcon {
  urlList: string[];
}

export interface TikTokWebItemAnchorsThumbnail {
  height: number | string;
  urlList: string[];
  width: number | string;
}

export interface TikTokWebItemAuthor {
  UserStoryStatus?: number | string;
  avatarLarger: string;
  avatarMedium: string;
  avatarThumb: string;
  commentSetting: number | string;
  downloadSetting: number | string;
  duetSetting: number | string;
  ftc: boolean;
  id: string;
  isADVirtual: boolean;
  isEmbedBanned: boolean;
  nickname: string;
  openFavorite: boolean;
  privateAccount: boolean;
  relation: number | string;
  roomId?: string;
  secUid: string;
  secret: boolean;
  shortDramaCreator: Record<string, string>;
  signature: string;
  stitchSetting: number | string;
  uniqueId: string;
  verified: boolean;
}

export interface TikTokWebItemAuthorStats {
  diggCount: number | string;
  followerCount: number | string;
  followingCount: number | string;
  friendCount: number | string;
  heart: number | string;
  heartCount: number | string;
  videoCount: number | string;
}

export interface TikTokWebItemAuthorStatsV2 {
  diggCount: string;
  followerCount: string;
  followingCount: string;
  friendCount: string;
  heart: string;
  heartCount: string;
  videoCount: string;
}

export interface TikTokWebItemChallenges {
  coverLarger: string;
  coverMedium: string;
  coverThumb: string;
  desc: string;
  id: string;
  isCommerce?: boolean;
  profileLarger: string;
  profileMedium: string;
  profileThumb: string;
  title: string;
}

export interface TikTokWebItemContents {
  desc: string;
  textExtra?: TikTokWebItemContentsTextExtra[];
}

export interface TikTokWebItemContentsTextExtra {
  awemeId: string;
  end: number | string;
  hashtagName: string;
  isCommerce: boolean;
  secUid?: string;
  start: number | string;
  subType: number | string;
  type: number | string;
  userId?: string;
  userUniqueId?: string;
}

export interface TikTokWebItemCreatorAIComment {
  eligibleVideo: boolean;
  hasAITopic: boolean;
  notEligibleReason: number | string;
}

export interface TikTokWebItemEffectStickers {
  ID: string;
  name: string;
  stickerStats: TikTokWebItemEffectStickersStickerStats;
}

export interface TikTokWebItemEffectStickersStickerStats {
  useCount: number | string;
}

export interface TikTokWebItemImagePost {
  cover: TikTokWebItemImagePostCover;
  images: TikTokWebItemImagePostImages[];
  shareCover: TikTokWebItemImagePostShareCover;
  title: string;
}

export interface TikTokWebItemImagePostCover {
  imageHeight: number | string;
  imageURL: TikTokWebItemImagePostCoverImageURL;
  imageWidth: number | string;
}

export interface TikTokWebItemImagePostCoverImageURL {
  urlList: string[];
}

export interface TikTokWebItemImagePostImages {
  imageHeight: number | string;
  imageURL: TikTokWebItemImagePostImagesImageURL;
  imageWidth: number | string;
}

export interface TikTokWebItemImagePostImagesImageURL {
  urlList: string[];
}

export interface TikTokWebItemImagePostShareCover {
  imageHeight: number | string;
  imageURL: TikTokWebItemImagePostShareCoverImageURL;
  imageWidth: number | string;
}

export interface TikTokWebItemImagePostShareCoverImageURL {
  urlList: string[];
}

export interface TikTokWebItemItemControl {
  can_comment?: boolean;
  can_creator_redirect?: boolean;
  can_music_redirect?: boolean;
  can_repost: boolean;
  can_share?: boolean;
}

export interface TikTokWebItemMusic {
  album?: string;
  authorName?: string;
  coverLarge: string;
  coverMedium: string;
  coverThumb: string;
  duration?: number | string;
  id: string;
  isCopyrighted: boolean;
  is_commerce_music?: boolean;
  is_unlimited_music?: boolean;
  original: boolean;
  playUrl?: string;
  private?: boolean;
  shoot_duration?: number | string;
  title: string;
  tt2dsp?: TikTokWebItemMusicTt2dsp;
}

export interface TikTokWebItemMusicTt2dsp {
  tt_to_dsp_song_infos?: TikTokWebItemMusicTt2dspTtToDspSongInfos[];
}

export interface TikTokWebItemMusicTt2dspTtToDspSongInfos {
  meta_song_id: string;
  platform: number | string;
  song_id: string;
  token?: TikTokWebItemMusicTt2dspTtToDspSongInfosToken;
}

export interface TikTokWebItemMusicTt2dspTtToDspSongInfosToken {
  apple_music_token: TikTokWebItemMusicTt2dspTtToDspSongInfosTokenAppleMusicToken;
}

export interface TikTokWebItemMusicTt2dspTtToDspSongInfosTokenAppleMusicToken {
  developer_token: string;
}

export interface TikTokWebItemPenaltyContext {
  arb_content_safety_status?: number | string;
  display_penalty_type: number | string;
  display_policy: number | string;
  display_ui_type: number | string;
  ec_global_verdict?: number | string;
  reviewed: number | string;
  status: number | string;
  tns_status: number | string;
  user_canceled?: number | string;
  video_status: number | string;
}

export interface TikTokWebItemPoi {
  address: string;
  category: string;
  city: string;
  cityCode: string;
  country: string;
  countryCode: string;
  fatherPoiId: string;
  fatherPoiName: string;
  id: string;
  name: string;
  province: string;
  ttTypeCode: string;
  ttTypeCodeL1: string;
  ttTypeNameMedium: string;
  ttTypeNameSuper: string;
  ttTypeNameTiny: string;
  type: number | string;
  typeCode: string;
}

export interface TikTokWebItemStats {
  collectCount: number | string;
  commentCount: number | string;
  diggCount: number | string;
  playCount: number | string;
  shareCount: number | string;
}

export interface TikTokWebItemStatsV2 {
  collectCount: string;
  commentCount: string;
  diggCount: string;
  playCount: string;
  repostCount: string;
  shareCount: string;
}

export interface TikTokWebItemStickersOnItem {
  stickerText: string[];
  stickerType: number | string;
}

export interface TikTokWebItemTextExtra {
  awemeId: string;
  end: number | string;
  hashtagName: string;
  isCommerce: boolean;
  secUid?: string;
  start: number | string;
  subType: number | string;
  type: number | string;
  userId?: string;
  userUniqueId?: string;
}

export interface TikTokWebItemVideo {
  PlayAddrStruct?: TikTokWebItemVideoPlayAddrStruct;
  VQScore?: string;
  bitrate?: number | string;
  bitrateInfo?: TikTokWebItemVideoBitrateInfo[];
  claInfo?: TikTokWebItemVideoClaInfo;
  codecType?: string;
  cover: string;
  definition?: string;
  downloadAddr?: string;
  duration: number | string;
  dynamicCover?: string;
  encodeUserTag?: string;
  encodedType?: string;
  format?: string;
  height: number | string;
  id: string;
  originCover: string;
  playAddr?: string;
  ratio: string;
  size?: number | string;
  subtitleInfos?: TikTokWebItemVideoSubtitleInfos[];
  videoID?: string;
  videoQuality?: string;
  volumeInfo: TikTokWebItemVideoVolumeInfo;
  width: number | string;
  zoomCover?: TikTokWebItemVideoZoomCover;
}

export interface TikTokWebItemVideoBitrateInfo {
  Bitrate: number | string;
  BitrateFPS: number | string;
  CodecType: string;
  Format: string;
  GearName: string;
  MVMAF: string;
  PlayAddr: TikTokWebItemVideoBitrateInfoPlayAddr;
  QualityType: number | string;
  VideoExtra: string;
}

export interface TikTokWebItemVideoBitrateInfoPlayAddr {
  DataSize: number | string;
  FileCs: string;
  FileHash: string;
  Height: number | string;
  Uri: string;
  UrlKey: string;
  UrlList: string[];
  Width: number | string;
}

export interface TikTokWebItemVideoClaInfo {
  captionInfos?: TikTokWebItemVideoClaInfoCaptionInfos[];
  captionsType?: number | string;
  enableAutoCaption: boolean;
  hasOriginalAudio: boolean;
  noCaptionReason?: number | string;
  originalLanguageInfo?: TikTokWebItemVideoClaInfoOriginalLanguageInfo;
}

export interface TikTokWebItemVideoClaInfoCaptionInfos {
  captionFormat: string;
  claSubtitleID: string;
  expire: string;
  isAutoGen: boolean;
  isOriginalCaption: boolean;
  language: string;
  languageCode: string;
  languageID: string;
  subID: string;
  subtitleType: string;
  translationType: string;
  url: string;
  urlList: string[];
  variant: string;
}

export interface TikTokWebItemVideoClaInfoOriginalLanguageInfo {
  canTranslateRealTimeNoCheck: boolean;
  language: string;
  languageCode: string;
  languageID: string;
}

export interface TikTokWebItemVideoPlayAddrStruct {
  DataSize: number | string;
  FileCs: string;
  FileHash: string;
  Height: number | string;
  Uri: string;
  UrlKey: string;
  UrlList: string[];
  Width: number | string;
}

export interface TikTokWebItemVideoSubtitleInfos {
  Format: string;
  LanguageCodeName: string;
  LanguageID: string;
  Size: number | string;
  Source: string;
  Url: string;
  UrlExpire: number | string;
  Version: string;
}

export interface TikTokWebItemVideoSuggestWordsList {
  video_suggest_words_struct: TikTokWebItemVideoSuggestWordsListVideoSuggestWordsStruct[];
}

export interface TikTokWebItemVideoSuggestWordsListVideoSuggestWordsStruct {
  hint_text: string;
  scene: string;
  words: TikTokWebItemVideoSuggestWordsListVideoSuggestWordsStructWords[];
}

export interface TikTokWebItemVideoSuggestWordsListVideoSuggestWordsStructWords {
  word: string;
  word_id: string;
}

export interface TikTokWebItemVideoVolumeInfo {
  Loudness?: number | string;
  Peak?: number | string;
}

export interface TikTokWebItemVideoZoomCover {
  "240": string;
  "480": string;
  "720": string;
  "960": string;
}

export interface TikTokWebItemWarnInfo {
  key: string;
  lang: string;
  text: string;
  type: number | string;
}
