// Generated by generate-client from spec/openapi.json. Do not edit.

import type { BaseClient } from '../../base.js';
import type { CandlesticksParams, CandlesticksResponse, DexesParams, DexesResponse, GlobalStatsResponse, LatestPoolsParams, LatestPoolsResponse, NetworkLatestPoolsParams, NetworkLatestPoolsResponse, NetworkPoolScreenerRequest, NetworkPoolsParams, NetworkPoolsResponse, NetworkRankingsParams, NetworkRankingsResponse, NetworksParams, NetworksResponse, PoolParams, PoolRelatedPoolsParams, PoolRelatedPoolsResponse, PoolResponse, PoolScreenerRequest, PoolSenderSwapsParams, PoolSenderSwapsResponse, PoolSwapsParams, PoolSwapsResponse, PoolTokenInfoSnapshotsParams, PoolTokenInfoSnapshotsResponse, PoolsResponse, RevivalRadarPoolsResponse, SearchParams, SearchResponse, SearchTrendsResponse, TagNetworkPoolsParams, TagNetworkPoolsResponse, TagPoolsParams, TagPoolsResponse, TagsParams, TagsResponse, TokenDeveloperPastTokensParams, TokenDeveloperPastTokensResponse, TokenHistoricalHoldersParams, TokenHistoricalHoldersResponse, TokenTopHoldersParams, TokenTopHoldersResponse, TokenTopTradersParams, TokenTopTradersResponse, TrendingLinksResponse, TrendingThemesParams, TrendingThemesResponse, TrendsParams, TrendsResponse, WalletTokenParams, WalletTokenResponse } from './types.js';

export class GeckoterminalClient {
  constructor(private readonly base: BaseClient) {}

  /** OHLCV bars for a pair, at the requested resolution and denomination. Costs 2 credits. */
  async candlesticks(params: CandlesticksParams): Promise<CandlesticksResponse> {
    const { pool_id, pair_id, ...query } = params;
    return this.base.get<CandlesticksResponse>(`/api/v1/gecko-terminal/candlesticks/${encodeURIComponent(pool_id)}/${encodeURIComponent(pair_id)}`, query);
  }

  /** Indexed DEXes with their per-DEX volume and transaction metrics. Costs 2 credits. */
  async dexes(params: DexesParams): Promise<DexesResponse> {
    return this.base.get<DexesResponse>('/api/v1/gecko-terminal/dexes', { ...params });
  }

  /** Aggregate DEX market stats: total 24h volume, pool and network counts, and the fear-and-greed index. Costs 2 credits. */
  async globalStats(): Promise<GlobalStatsResponse> {
    return this.base.get<GlobalStatsResponse>('/api/v1/gecko-terminal/global-stats');
  }

  /** Every chain GeckoTerminal indexes, with its identifier, image and native currency. Costs 2 credits. */
  async networks(params: NetworksParams): Promise<NetworksResponse> {
    return this.base.get<NetworksResponse>('/api/v1/gecko-terminal/networks', { ...params });
  }

  /** Chain leaderboard: each network with its 24h volume, transaction count and pool count. Costs 2 credits. */
  async networkRankings(params: NetworkRankingsParams): Promise<NetworkRankingsResponse> {
    return this.base.get<NetworkRankingsResponse>('/api/v1/gecko-terminal/networks/rankings', { ...params });
  }

  /** Newly created pools on one chain, newest first. Costs 2 credits. */
  async networkLatestPools(params: NetworkLatestPoolsParams): Promise<NetworkLatestPoolsResponse> {
    const { network, ...query } = params;
    return this.base.get<NetworkLatestPoolsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/latest`, query);
  }

  /** Screen pools on one chain, optionally narrowed to a single DEX. Costs 2 credits. */
  async networkPools(params: NetworkPoolsParams, body: NetworkPoolScreenerRequest): Promise<NetworkPoolsResponse> {
    const { network } = params;
    return this.base.post<NetworkPoolsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/search`, body);
  }

  /** Full pool detail: price, reserves, GT score, security metrics, tokens, DEX and developer. Costs 2 credits. */
  async pool(params: PoolParams): Promise<PoolResponse> {
    const { network, address, ...query } = params;
    return this.base.get<PoolResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/${encodeURIComponent(address)}`, query);
  }

  /** Other pools trading the same base token, with their liquidity and 24h volume. Costs 2 credits. */
  async poolRelatedPools(params: PoolRelatedPoolsParams): Promise<PoolRelatedPoolsResponse> {
    const { network, address } = params;
    return this.base.get<PoolRelatedPoolsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/${encodeURIComponent(address)}/related-pools`);
  }

  /** Swaps in a pool over a time window, grouped by sender wallet. Costs 2 credits. */
  async poolSenderSwaps(params: PoolSenderSwapsParams): Promise<PoolSenderSwapsResponse> {
    const { network, address, ...query } = params;
    return this.base.get<PoolSenderSwapsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/${encodeURIComponent(address)}/sender-swaps`, query);
  }

  /** Individual swaps in a pool. Requires a cursor: pass a unix timestamp to start from. Costs 2 credits. */
  async poolSwaps(params: PoolSwapsParams): Promise<PoolSwapsResponse> {
    const { network, address, ...query } = params;
    return this.base.get<PoolSwapsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/${encodeURIComponent(address)}/swaps`, query);
  }

  /** Descriptions, socials and metadata for both tokens in a pool, as last snapshotted. Costs 2 credits. */
  async poolTokenInfoSnapshots(params: PoolTokenInfoSnapshotsParams): Promise<PoolTokenInfoSnapshotsResponse> {
    const { network, address } = params;
    return this.base.get<PoolTokenInfoSnapshotsResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/pools/${encodeURIComponent(address)}/token-info-snapshots`);
  }

  /** Holder count over time, as a series of snapshots. Costs 2 credits. */
  async tokenHistoricalHolders(params: TokenHistoricalHoldersParams): Promise<TokenHistoricalHoldersResponse> {
    const { network, token_address, ...query } = params;
    return this.base.get<TokenHistoricalHoldersResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/tokens/${encodeURIComponent(token_address)}/historical-holders`, query);
  }

  /** Largest holders of a token, with each holder's balance and share of supply. Costs 2 credits. */
  async tokenTopHolders(params: TokenTopHoldersParams): Promise<TokenTopHoldersResponse> {
    const { network, token_address } = params;
    return this.base.get<TokenTopHoldersResponse>(`/api/v1/gecko-terminal/networks/${encodeURIComponent(network)}/tokens/${encodeURIComponent(token_address)}/top-holders`);
  }

  /** Newly created pools across every chain, newest first. Costs 2 credits. */
  async latestPools(params: LatestPoolsParams): Promise<LatestPoolsResponse> {
    return this.base.get<LatestPoolsResponse>('/api/v1/gecko-terminal/pools/latest', { ...params });
  }

  /** Revival Radar: older pools whose trading activity has re-accelerated. Costs 2 credits. */
  async revivalRadarPools(): Promise<RevivalRadarPoolsResponse> {
    return this.base.get<RevivalRadarPoolsResponse>('/api/v1/gecko-terminal/pools/revival-radar');
  }

  /** Screen pools across every chain by liquidity, volume, age, holders, taxes and trade counts. Costs 2 credits. */
  async pools(body: PoolScreenerRequest): Promise<PoolsResponse> {
    return this.base.post<PoolsResponse>('/api/v1/gecko-terminal/pools/search', body);
  }

  /** Search tokens, pools, pairs, categories, chains and DEXes by name, symbol or address. Costs 2 credits. */
  async search(params: SearchParams): Promise<SearchResponse> {
    return this.base.get<SearchResponse>('/api/v1/gecko-terminal/search', { ...params });
  }

  /** What other users are searching for right now, as shown in the empty search box. Costs 2 credits. */
  async searchTrends(): Promise<SearchTrendsResponse> {
    return this.base.get<SearchTrendsResponse>('/api/v1/gecko-terminal/search-trends');
  }

  /** Token categories (meme, defi, ai-agents, launchpads) with each category's top tokens. Costs 2 credits. */
  async tags(params: TagsParams): Promise<TagsResponse> {
    return this.base.get<TagsResponse>('/api/v1/gecko-terminal/tags', { ...params });
  }

  /** Pools belonging to one category, restricted to a single chain. Costs 2 credits. */
  async tagNetworkPools(params: TagNetworkPoolsParams): Promise<TagNetworkPoolsResponse> {
    const { tag, network, ...query } = params;
    return this.base.get<TagNetworkPoolsResponse>(`/api/v1/gecko-terminal/tags/${encodeURIComponent(tag)}/networks/${encodeURIComponent(network)}/pools`, query);
  }

  /** Pools belonging to one category, across every chain. Costs 2 credits. */
  async tagPools(params: TagPoolsParams): Promise<TagPoolsResponse> {
    const { tag, ...query } = params;
    return this.base.get<TagPoolsResponse>(`/api/v1/gecko-terminal/tags/${encodeURIComponent(tag)}/pools`, query);
  }

  /** Other tokens launched by the same developer, with each one's market cap and top pool. Costs 2 credits. */
  async tokenDeveloperPastTokens(params: TokenDeveloperPastTokensParams): Promise<TokenDeveloperPastTokensResponse> {
    const { developer_detail_id } = params;
    return this.base.get<TokenDeveloperPastTokensResponse>(`/api/v1/gecko-terminal/token-developers/${encodeURIComponent(developer_detail_id)}/past-tokens`);
  }

  /** Most profitable wallets in a token, with realised and unrealised PnL, buys, sells and balance. Costs 2 credits. */
  async tokenTopTraders(params: TokenTopTradersParams): Promise<TokenTopTradersResponse> {
    const { token_id } = params;
    return this.base.get<TokenTopTradersResponse>(`/api/v1/gecko-terminal/tokens/${encodeURIComponent(token_id)}/top-traders`);
  }

  /** One wallet's position in one token: buys, sells, balance and PnL. Costs 2 credits. */
  async walletToken(params: WalletTokenParams): Promise<WalletTokenResponse> {
    const { token_id, wallet_address } = params;
    return this.base.get<WalletTokenResponse>(`/api/v1/gecko-terminal/tokens/${encodeURIComponent(token_id)}/wallets/${encodeURIComponent(wallet_address)}`);
  }

  /** The curated shortcuts GeckoTerminal pins above its trending table. Costs 2 credits. */
  async trendingLinks(): Promise<TrendingLinksResponse> {
    return this.base.get<TrendingLinksResponse>('/api/v1/gecko-terminal/trending-links');
  }

  /** Narratives currently trending, each with the pools driving it. Costs 2 credits. */
  async trendingThemes(params: TrendingThemesParams): Promise<TrendingThemesResponse> {
    return this.base.get<TrendingThemesResponse>('/api/v1/gecko-terminal/trending-themes', { ...params });
  }

  /** Trending tokens: the top gainers, newest pools and hottest pairs powering the home page. Costs 2 credits. */
  async trends(params: TrendsParams): Promise<TrendsResponse> {
    return this.base.get<TrendsResponse>('/api/v1/gecko-terminal/trends', { ...params });
  }
}
