// Generated by generate-client from spec/openapi.json. Do not edit.

import type { BaseClient } from '../../base.js';
import type { GetCommunityParams, GetTweetParams, GetUserProfileByIdParams, GetUserProfileParams, TwitterCommunityResponse, TwitterProfileResponse, TwitterTweetDetailResponse } from './types.js';

export class TwitterClient {
  constructor(private readonly base: BaseClient) {}

  /** An X (Twitter) Community as x.com shows it to logged-out visitors: id, name, description, member count, created time, join policy, topic, banner, rules and creator, plus the 20 community posts x.com ranks by likes. This is a fixed window: x.com offers no latest feed and no further pages logged-out. Costs 2 credits. */
  async getCommunity(params: GetCommunityParams): Promise<TwitterCommunityResponse> {
    const { community_id } = params;
    return this.base.get<TwitterCommunityResponse>(`/api/v1/twitter/communities/${encodeURIComponent(community_id)}`);
  }

  /** One X (Twitter) post as x.com shows it to logged-out visitors: full text (long posts included), every t.co link in it mapped to its expanded URL in `urls` (the media link maps to the media page; the text itself keeps the t.co links), created time, likes, replies, reposts, quotes, bookmarks, views when X shows them, media with video variants and bitrates, the article an article post links to, and the quoted post. `parent_tweets` holds the posts above a reply that x.com shows logged-out, oldest first; in samples that is only the post it replies to, so follow `in_reply_to_tweet_id` to walk further up. `replies` holds the top replies x.com shows logged-out (0 to 4 in samples, not every reply); x.com offers no further reply pages logged-out. Each `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there, so use the profile route for those. Costs 1 credit. */
  async getTweet(params: GetTweetParams): Promise<TwitterTweetDetailResponse> {
    const { tweet_id } = params;
    return this.base.get<TwitterTweetDetailResponse>(`/api/v1/twitter/tweets/${encodeURIComponent(tweet_id)}`);
  }

  /** An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its numeric user id. Costs 1 credit. */
  async getUserProfileById(params: GetUserProfileByIdParams): Promise<TwitterProfileResponse> {
    const { user_id } = params;
    return this.base.get<TwitterProfileResponse>(`/api/v1/twitter/users/by-id/${encodeURIComponent(user_id)}`);
  }

  /** An X (Twitter) account's public profile as x.com shows it to logged-out visitors: id, handle, name, bio with its links and mentions, bio link, location, avatar, banner, join date, follower, following and post counts, blue check and protected flag. It also carries the pinned post and the newest original posts x.com shows logged-out (4 or 5 in samples), from the same page fetch. This is a fixed window: x.com offers no further pages logged-out, so there is no cursor. A protected account returns its profile with no posts. Each post's `author` holds only the fields x.com embeds with posts: bio, join date, bio link, location and banner can be null there even when the profile has them. Looks the account up by its handle. Costs 1 credit. */
  async getUserProfile(params: GetUserProfileParams): Promise<TwitterProfileResponse> {
    const { screen_name } = params;
    return this.base.get<TwitterProfileResponse>(`/api/v1/twitter/users/${encodeURIComponent(screen_name)}`);
  }
}
