// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
  upgrade_url?: string | null;
}

export interface GetCommunityParams {
  /** Numeric X Community id, the digits after /i/communities/ in a community URL. */
  community_id: string;
}

export interface GetTweetParams {
  /** Numeric post (tweet) id, the digits after /status/ in a post URL. */
  tweet_id: string;
}

export interface GetUserProfileByIdParams {
  /** Numeric X user id (the account's rest_id). */
  user_id: string;
}

export interface GetUserProfileParams {
  /** X handle without the @: 1 to 15 letters, digits or underscores. x.com's own page names (explore, home, search, ...) are rejected. */
  screen_name: string;
}

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";

export interface TwitterArticle {
  cover_image_url: string | null;
  id: string;
  plain_text: string | null;
  preview_text: string | null;
  title: string;
}

export interface TwitterCommunity {
  banner_url: string | null;
  created_at: string;
  creator: TwitterCommunityCreator | null;
  description: string | null;
  id: string;
  is_nsfw: boolean;
  join_policy: string | null;
  member_count: number;
  name: string;
  rules: TwitterCommunityRule[];
  topic: string | null;
  url: string;
}

export interface TwitterCommunityCreator {
  id: string;
  is_blue_verified: boolean;
  name: string | null;
  screen_name: string;
}

export interface TwitterCommunityResponse {
  community: TwitterCommunity;
  tweets: TwitterTweet[];
}

export interface TwitterCommunityRule {
  description: string | null;
  name: string;
}

export interface TwitterMedia {
  duration_ms: number | null;
  expanded_url: string | null;
  height: number | null;
  id: string | null;
  media_url: string;
  type: string;
  variants: TwitterVideoVariant[];
  width: number | null;
}

export interface TwitterMention {
  id: string | null;
  screen_name: string;
}

export interface TwitterProfileResponse {
  pinned_tweet: TwitterTweet | null;
  tweets: TwitterTweet[];
  user: TwitterUser;
}

export interface TwitterTweet {
  article: TwitterArticle | null;
  author: TwitterUser;
  bookmark_count: number | null;
  cashtags: string[];
  created_at: string;
  hashtags: string[];
  id: string;
  in_reply_to_screen_name: string | null;
  in_reply_to_tweet_id: string | null;
  lang: string | null;
  like_count: number;
  media: TwitterMedia[];
  mentions: TwitterMention[];
  quote_count: number;
  quoted_tweet: TwitterTweet | null;
  reply_count: number;
  retweet_count: number;
  text: string;
  url: string;
  urls: TwitterUrlEntity[];
  view_count: number | null;
}

export interface TwitterTweetDetailResponse {
  parent_tweets: TwitterTweet[];
  replies: TwitterTweet[];
  tweet: TwitterTweet;
}

export interface TwitterUrlEntity {
  display_url: string | null;
  expanded_url: string;
  url: string;
}

export interface TwitterUser {
  avatar_url: string | null;
  banner_url: string | null;
  bio_url: string | null;
  created_at: string | null;
  description: string | null;
  description_mentions: TwitterMention[];
  description_urls: TwitterUrlEntity[];
  followers_count: number | null;
  following_count: number | null;
  id: string;
  is_blue_verified: boolean;
  is_protected: boolean;
  location: string | null;
  name: string | null;
  profile_url: string;
  screen_name: string;
  tweet_count: number | null;
  verified_type: string | null;
}

export interface TwitterVideoVariant {
  bitrate: number | null;
  content_type: string;
  url: string;
}
