// Generated by generate-client from spec/openapi.json. Do not edit.

import { TaplineClient } from '../src/index.js';
import { run as runAirbnb } from './smoke-airbnb.js';
import { run as runYoutube } from './smoke-youtube.js';
import { run as runGmgn } from './smoke-gmgn.js';

const client = new TaplineClient();
let failures = 0;
failures += await runAirbnb(client);
failures += await runYoutube(client);
failures += await runGmgn(client);
if (failures > 0) {
  console.error(`\n${failures} smoke check(s) failed`);
  process.exit(1);
}
console.log('\nall smoke checks passed');
