// Generated by generate-client from spec/openapi.json. Do not edit.

import { TaplineClient } from '../src/index.js';
import { run as runAirbnb } from './smoke-airbnb.js';
import { run as runYoutube } from './smoke-youtube.js';
import { run as runGmgn } from './smoke-gmgn.js';
import { run as runGeckoterminal } from './smoke-geckoterminal.js';
import { run as runPonsfamily } from './smoke-ponsfamily.js';
import { run as runGoplus } from './smoke-goplus.js';
import { run as runTwitter } from './smoke-twitter.js';
import { run as runPinterest } from './smoke-pinterest.js';
import { run as runPumpfun } from './smoke-pumpfun.js';
import { run as runTiktok } from './smoke-tiktok.js';

const RUNNERS: Record<string, (client: TaplineClient) => Promise<number>> = {
  'airbnb': runAirbnb,
  'youtube': runYoutube,
  'gmgn': runGmgn,
  'geckoterminal': runGeckoterminal,
  'ponsfamily': runPonsfamily,
  'goplus': runGoplus,
  'twitter': runTwitter,
  'pinterest': runPinterest,
  'pumpfun': runPumpfun,
  'tiktok': runTiktok,
};

const services = process.argv.slice(2);
const unknown = services.filter((service) => !Object.hasOwn(RUNNERS, service));
if (services.length === 0 || unknown.length > 0) {
  if (unknown.length > 0) console.error(`unknown service(s): ${unknown.join(', ')}`);
  console.error(`usage: npm run smoke -- <service> [<service> ...]; services: ${Object.keys(RUNNERS).join(', ')}`);
  process.exit(2);
}

const client = new TaplineClient();
let failures = 0;
for (const service of services) failures += await RUNNERS[service]!(client);
if (failures > 0) {
  console.error(`\n${failures} smoke check(s) failed`);
  process.exit(1);
}
console.log('\nall smoke checks passed');
