// Generated by generate-client from spec/openapi.json. Do not edit.

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Ajv2020 } from 'ajv/dist/2020.js';

import type { TaplineClient } from '../src/index.js';
import type { CreatorHoldingsRequest, GetDeveloperTradesParams, GetFeeSharingParams, GetForumCommunityParams, GetForumHoldingParams, GetForumPostCommentsParams, GetForumPostParams, GetMarketAthParams, GetMarketBurnedParams, GetMarketChartParams, GetMarketHoldersParams, GetMarketOrderDepthParams, GetMarketParams, GetMarketTipParams, GetMarketTradesParams, GetPortfolioChartParams, GetProfileParams, GetTokenImagesParams, GetTokenParams, GetV2CreatorFeesParams, GetV2DistributorParams, GetV2MarketChartParams, GetV2MarketHoldersParams, GetV2MarketTradesParams, GetWalletIdentitiesParams, GetWalletPositionsParams, ListForumCommunitiesParams, ListForumPostsParams, ListLaunchesParams, ListLiveMarketsParams, SearchLaunchesParams } from '../src/services/ponsfamily/types.js';
import { TaplineError } from '../src/errors.js';
import { typeAt, unknownKeys } from './schema-walk.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(process.env.GENERATE_CLIENT_FIXTURES ?? join(HERE, '..', '..', 'fixtures'), 'ponsfamily');
const SCHEMAS = JSON.parse(readFileSync(join(HERE, '..', '..', 'spec', 'ponsfamily', 'schemas.json'), 'utf8'));

interface Input {
  params?: Record<string, unknown>;
  body?: unknown;
  expect?: { status: number; code: string | null };
}

interface Method {
  response: string;
  isArray: boolean;
  call: (client: TaplineClient, input: Input) => Promise<unknown>;
}

const METHODS: Record<string, Method> = {
  get_analytics: { response: 'GetAnalyticsResponse', isArray: false, call: (c) => c.ponsfamily.getAnalytics() },
  list_cto_migrations: { response: 'ListCtoMigrationsResponse', isArray: false, call: (c) => c.ponsfamily.listCtoMigrations() },
  get_eth_price: { response: 'GetEthPriceResponse', isArray: false, call: (c) => c.ponsfamily.getEthPrice() },
  list_forum_communities: { response: 'ListForumCommunitiesResponse', isArray: false, call: (c, i) => c.ponsfamily.listForumCommunities(i.params as unknown as ListForumCommunitiesParams) },
  get_forum_community: { response: 'GetForumCommunityResponse', isArray: false, call: (c, i) => c.ponsfamily.getForumCommunity(i.params as unknown as GetForumCommunityParams) },
  get_forum_holding: { response: 'GetForumHoldingResponse', isArray: false, call: (c, i) => c.ponsfamily.getForumHolding(i.params as unknown as GetForumHoldingParams) },
  get_forum_market: { response: 'GetForumMarketResponse', isArray: false, call: (c) => c.ponsfamily.getForumMarket() },
  list_forum_posts: { response: 'ListForumPostsResponse', isArray: false, call: (c, i) => c.ponsfamily.listForumPosts(i.params as unknown as ListForumPostsParams) },
  get_forum_post: { response: 'GetForumPostResponse', isArray: false, call: (c, i) => c.ponsfamily.getForumPost(i.params as unknown as GetForumPostParams) },
  get_forum_post_comments: { response: 'GetForumPostCommentsResponse', isArray: false, call: (c, i) => c.ponsfamily.getForumPostComments(i.params as unknown as GetForumPostCommentsParams) },
  list_launches: { response: 'ListLaunchesResponse', isArray: false, call: (c, i) => c.ponsfamily.listLaunches(i.params as unknown as ListLaunchesParams) },
  list_graduated_catalog: { response: 'Launch', isArray: true, call: (c) => c.ponsfamily.listGraduatedCatalog() },
  list_graduations: { response: 'Graduation', isArray: true, call: (c) => c.ponsfamily.listGraduations() },
  list_live_markets: { response: 'LiveMarket', isArray: true, call: (c, i) => c.ponsfamily.listLiveMarkets(i.params as unknown as ListLiveMarketsParams) },
  search_launches: { response: 'SearchLaunchesResponse', isArray: false, call: (c, i) => c.ponsfamily.searchLaunches(i.params as unknown as SearchLaunchesParams) },
  get_market: { response: 'GetMarketResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarket(i.params as unknown as GetMarketParams) },
  get_market_ath: { response: 'GetMarketAthResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketAth(i.params as unknown as GetMarketAthParams) },
  get_market_burned: { response: 'GetMarketBurnedResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketBurned(i.params as unknown as GetMarketBurnedParams) },
  get_market_chart: { response: 'GetMarketChartResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketChart(i.params as unknown as GetMarketChartParams) },
  get_developer_trades: { response: 'GetDeveloperTradesResponse', isArray: false, call: (c, i) => c.ponsfamily.getDeveloperTrades(i.params as unknown as GetDeveloperTradesParams) },
  get_market_holders: { response: 'GetMarketHoldersResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketHolders(i.params as unknown as GetMarketHoldersParams) },
  get_market_order_depth: { response: 'GetMarketOrderDepthResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketOrderDepth(i.params as unknown as GetMarketOrderDepthParams) },
  get_market_tip: { response: 'GetMarketTipResponse', isArray: false, call: (c, i) => c.ponsfamily.getMarketTip(i.params as unknown as GetMarketTipParams) },
  get_market_trades: { response: 'MarketTrade', isArray: true, call: (c, i) => c.ponsfamily.getMarketTrades(i.params as unknown as GetMarketTradesParams) },
  get_creator_holdings: { response: 'GetCreatorHoldingsResponse', isArray: false, call: (c, i) => c.ponsfamily.getCreatorHoldings(i.body as CreatorHoldingsRequest) },
  get_fee_sharing: { response: 'GetFeeSharingResponse', isArray: false, call: (c, i) => c.ponsfamily.getFeeSharing(i.params as unknown as GetFeeSharingParams) },
  get_token_images: { response: 'GetTokenImagesResponse', isArray: false, call: (c, i) => c.ponsfamily.getTokenImages(i.params as unknown as GetTokenImagesParams) },
  get_token: { response: 'GetTokenResponse', isArray: false, call: (c, i) => c.ponsfamily.getToken(i.params as unknown as GetTokenParams) },
  get_v2_market_chart: { response: 'GetV2MarketChartResponse', isArray: false, call: (c, i) => c.ponsfamily.getV2MarketChart(i.params as unknown as GetV2MarketChartParams) },
  get_v2_creator_fees: { response: 'GetV2CreatorFeesResponse', isArray: false, call: (c, i) => c.ponsfamily.getV2CreatorFees(i.params as unknown as GetV2CreatorFeesParams) },
  get_v2_distributor: { response: 'GetV2DistributorResponse', isArray: false, call: (c, i) => c.ponsfamily.getV2Distributor(i.params as unknown as GetV2DistributorParams) },
  get_v2_market_holders: { response: 'GetV2MarketHoldersResponse', isArray: false, call: (c, i) => c.ponsfamily.getV2MarketHolders(i.params as unknown as GetV2MarketHoldersParams) },
  get_v2_market_trades: { response: 'GetV2MarketTradesResponse', isArray: false, call: (c, i) => c.ponsfamily.getV2MarketTrades(i.params as unknown as GetV2MarketTradesParams) },
  get_wallet_identities: { response: 'GetWalletIdentitiesResponse', isArray: false, call: (c, i) => c.ponsfamily.getWalletIdentities(i.params as unknown as GetWalletIdentitiesParams) },
  get_portfolio_chart: { response: 'GetPortfolioChartResponse', isArray: false, call: (c, i) => c.ponsfamily.getPortfolioChart(i.params as unknown as GetPortfolioChartParams) },
  get_wallet_positions: { response: 'GetWalletPositionsResponse', isArray: false, call: (c, i) => c.ponsfamily.getWalletPositions(i.params as unknown as GetWalletPositionsParams) },
  get_profile: { response: 'GetProfileResponse', isArray: false, call: (c, i) => c.ponsfamily.getProfile(i.params as unknown as GetProfileParams) },
};

const ajv = new Ajv2020({ strict: false, allErrors: true });
ajv.addSchema(SCHEMAS, 'service');

function validator(name: string, isArray: boolean) {
  const ref = { $ref: `service#/$defs/${name}` };
  return ajv.compile(isArray ? { type: 'array', items: ref } : ref);
}

function describe(e: unknown): string {
  if (e instanceof TaplineError) return `HTTP ${e.status} ${e.code}: ${e.message} (request_id=${e.requestId})`;
  return e instanceof Error ? `${e.name}: ${e.message}` : String(e);
}

function stems(): string[] {
  if (!existsSync(FIXTURES)) return [];
  return readdirSync(FIXTURES)
    .filter((f) => f.endsWith('.request.json'))
    .map((f) => f.slice(0, -'.request.json'.length))
    .sort();
}

export async function run(client: TaplineClient): Promise<number> {
  let failures = 0;
  const seen = stems();
  for (const name of Object.keys(METHODS)) {
    if (!seen.includes(`${name}.default`)) {
      console.error(`[FAIL] ponsfamily.${name}.default: no captured request in ${FIXTURES}; run capture.py`);
      failures += 1;
    }
  }
  for (const stem of seen) {
    const name = stem.split('.', 1)[0]!;
    const method = METHODS[name];
    if (!method) continue;
    const input = JSON.parse(readFileSync(join(FIXTURES, `${stem}.request.json`), 'utf8')) as Input;
    const negative = stem.includes('.neg.');
    try {
      const result = await method.call(client, input);
      if (negative) {
        console.error(`[FAIL] ponsfamily.${stem}: expected HTTP ${input.expect?.status}, got a 200`);
        failures += 1;
        continue;
      }
      const validate = validator(method.response, method.isArray);
      if (!validate(result)) {
        const rootSchema = method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` };
        const problems = [...new Set((validate.errors ?? []).map((e) => {
          const segments = e.instancePath.split('/').slice(1);
          const ownerSegments = e.keyword === 'required' ? segments : segments.slice(0, -1);
          const ownerPath = ownerSegments.map((p) => (/^\d+$/.test(p) ? `[${p}]` : `.${p}`)).join('');
          const leaf = segments[segments.length - 1] ?? '';
          const owner = typeAt(SCHEMAS.$defs, rootSchema, result, ownerPath) ?? method.response;
          const prop = e.keyword === 'required' ? String((e.params as { missingProperty?: string }).missingProperty) : leaf;
          return `${owner}.${prop}: ${e.keyword} ${e.message}`;
        }))].slice(0, 20);
        console.error(`[FAIL] ponsfamily.${stem}: body does not match ${method.response}: ${problems.join('; ')}`);
        failures += 1;
        continue;
      }
      const drift = unknownKeys(SCHEMAS.$defs, method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` }, result, method.response);
      console.log(`[PASS] ponsfamily.${stem}${drift.length ? ` (${drift.length} undocumented key(s), e.g. ${drift[0]})` : ''}`);
    } catch (e) {
      if (negative && e instanceof TaplineError) {
        const expected = input.expect!;
        const body = { code: e.code, message: e.message, request_id: e.requestId, domain: e.domain, details: e.details };
        const validate = validator('ErrorResponse', false);
        const problems: string[] = [];
        if (e.status !== expected.status) problems.push(`expected HTTP ${expected.status}, got ${e.status}`);
        if (expected.code && e.code !== expected.code) problems.push(`expected code ${expected.code}, got ${e.code}`);
        if (!validate(body)) problems.push(`error body does not match ErrorResponse: ${(validate.errors ?? []).map((x) => x.message).join('; ')}`);
        if (problems.length > 0) {
          console.error(`[FAIL] ponsfamily.${stem}: ${problems.join('; ')}`);
          failures += 1;
        } else {
          console.log(`[PASS] ponsfamily.${stem}: ${e.status} ${e.code}`);
        }
        continue;
      }
      console.error(`[FAIL] ponsfamily.${stem}: ${describe(e)} input=${JSON.stringify(input)}`);
      failures += 1;
    }
  }
  return failures;
}
