// Generated by generate-client from spec/openapi.json. Do not edit.

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Ajv2020 } from 'ajv/dist/2020.js';

import type { TaplineClient } from '../src/index.js';
import type { GetCalendarRequest, GetDetailsRequest, GetPriceRequest, GetReviewsRequest, SearchLocationsParams, SearchRequest } from '../src/services/airbnb/types.js';
import { TaplineError } from '../src/errors.js';
import { typeAt, unknownKeys } from './schema-walk.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(process.env.GENERATE_CLIENT_FIXTURES ?? join(HERE, '..', '..', 'fixtures'), 'airbnb');
const SCHEMAS = JSON.parse(readFileSync(join(HERE, '..', '..', 'spec', 'airbnb', 'schemas.json'), 'utf8'));

interface Input {
  params?: Record<string, unknown>;
  body?: unknown;
  expect?: { status: number; code: string | null };
}

interface Method {
  response: string;
  isArray: boolean;
  call: (client: TaplineClient, input: Input) => Promise<unknown>;
}

const METHODS: Record<string, Method> = {
  get_calendar: { response: 'ParsedCalendarResponse', isArray: false, call: (c, i) => c.airbnb.getCalendar(i.body as GetCalendarRequest) },
  get_details: { response: 'ParsedDetailsResponse', isArray: false, call: (c, i) => c.airbnb.getDetails(i.body as GetDetailsRequest) },
  search_locations: { response: 'ParsedAutocompleteResponse', isArray: false, call: (c, i) => c.airbnb.searchLocations(i.params as unknown as SearchLocationsParams) },
  get_price: { response: 'ParsedPriceResponse', isArray: false, call: (c, i) => c.airbnb.getPrice(i.body as GetPriceRequest) },
  get_reviews: { response: 'ParsedReviewsResponse', isArray: false, call: (c, i) => c.airbnb.getReviews(i.body as GetReviewsRequest) },
  search: { response: 'ParsedSearchResponse', isArray: false, call: (c, i) => c.airbnb.search(i.body as SearchRequest) },
};

const ajv = new Ajv2020({ strict: false, allErrors: true });
ajv.addSchema(SCHEMAS, 'service');

function validator(name: string, isArray: boolean) {
  const ref = { $ref: `service#/$defs/${name}` };
  return ajv.compile(isArray ? { type: 'array', items: ref } : ref);
}

function describe(e: unknown): string {
  if (e instanceof TaplineError) return `HTTP ${e.status} ${e.code}: ${e.message} (request_id=${e.requestId})`;
  return e instanceof Error ? `${e.name}: ${e.message}` : String(e);
}

function stems(): string[] {
  if (!existsSync(FIXTURES)) return [];
  return readdirSync(FIXTURES)
    .filter((f) => f.endsWith('.request.json'))
    .map((f) => f.slice(0, -'.request.json'.length))
    .sort();
}

export async function run(client: TaplineClient): Promise<number> {
  let failures = 0;
  const seen = stems();
  for (const name of Object.keys(METHODS)) {
    if (!seen.includes(`${name}.default`)) {
      console.error(`[FAIL] airbnb.${name}.default: no captured request in ${FIXTURES}; run capture.py`);
      failures += 1;
    }
  }
  for (const stem of seen) {
    const name = stem.split('.', 1)[0]!;
    const method = METHODS[name];
    if (!method) continue;
    const input = JSON.parse(readFileSync(join(FIXTURES, `${stem}.request.json`), 'utf8')) as Input;
    const negative = stem.includes('.neg.');
    try {
      const result = await method.call(client, input);
      if (negative) {
        console.error(`[FAIL] airbnb.${stem}: expected HTTP ${input.expect?.status}, got a 200`);
        failures += 1;
        continue;
      }
      const validate = validator(method.response, method.isArray);
      if (!validate(result)) {
        const rootSchema = method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` };
        const problems = [...new Set((validate.errors ?? []).map((e) => {
          const segments = e.instancePath.split('/').slice(1);
          const ownerSegments = e.keyword === 'required' ? segments : segments.slice(0, -1);
          const ownerPath = ownerSegments.map((p) => (/^\d+$/.test(p) ? `[${p}]` : `.${p}`)).join('');
          const leaf = segments[segments.length - 1] ?? '';
          const owner = typeAt(SCHEMAS.$defs, rootSchema, result, ownerPath) ?? method.response;
          const prop = e.keyword === 'required' ? String((e.params as { missingProperty?: string }).missingProperty) : leaf;
          return `${owner}.${prop}: ${e.keyword} ${e.message}`;
        }))].slice(0, 20);
        console.error(`[FAIL] airbnb.${stem}: body does not match ${method.response}: ${problems.join('; ')}`);
        failures += 1;
        continue;
      }
      const drift = unknownKeys(SCHEMAS.$defs, method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` }, result, method.response);
      console.log(`[PASS] airbnb.${stem}${drift.length ? ` (${drift.length} undocumented key(s), e.g. ${drift[0]})` : ''}`);
    } catch (e) {
      if (negative && e instanceof TaplineError) {
        const expected = input.expect!;
        const body = { code: e.code, message: e.message, request_id: e.requestId, domain: e.domain, details: e.details };
        const validate = validator('ErrorResponse', false);
        const problems: string[] = [];
        if (e.status !== expected.status) problems.push(`expected HTTP ${expected.status}, got ${e.status}`);
        if (expected.code && e.code !== expected.code) problems.push(`expected code ${expected.code}, got ${e.code}`);
        if (!validate(body)) problems.push(`error body does not match ErrorResponse: ${(validate.errors ?? []).map((x) => x.message).join('; ')}`);
        if (problems.length > 0) {
          console.error(`[FAIL] airbnb.${stem}: ${problems.join('; ')}`);
          failures += 1;
        } else {
          console.log(`[PASS] airbnb.${stem}: ${e.status} ${e.code}`);
        }
        continue;
      }
      console.error(`[FAIL] airbnb.${stem}: ${describe(e)} input=${JSON.stringify(input)}`);
      failures += 1;
    }
  }
  return failures;
}
