// Generated by generate-client from spec/openapi.json. Do not edit.

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Ajv2020 } from 'ajv/dist/2020.js';

import type { TaplineClient } from '../src/index.js';
import type { ActivityRankInfoParams, AddressListRequest, AggedTokenTradesParams, AggedTokenTransfersParams, BluechipRankParams, DevCreatedTokensParams, DexTradesPollingParams, HolderStatParams, HoldersParams, LaunchpadTaxPolicyParams, LiquidityParams, LivePreviewParams, McapCandlesParams, MultiTokenFullInfoParams, MultiTokenInfoParams, MultiWindowTokenInfoParams, NativeTransferParams, NewPairsParams, PoolFeeInfoParams, RecommendSlippageParams, SearchParams, SecurityParams, SimilarCoinExtremesParams, SimilarCoinsParams, SmartMoneyWalletInfoParams, SocialsParams, StatsParams, SwapRankingsParams, SymbolListRequest, TokenAiNarrativeParams, TokenBundlerStatParams, TokenCandlesParams, TokenCommunityMessagesParams, TokenDevInfoParams, TokenFeeDistributionParams, TokenFeeInfoParams, TokenHolderExtraInfoParams, TokenInfoBriefParams, TokenLiquidityStatsParams, TokenLiquidityTrendParams, TokenLogoHistoryParams, TokenPricesParams, TokenSignalsParams, TokenSignalsRequest, TokenTradesV2Params, TokenTrendsParams, TopBuyersParams, TopCallersParams, TraderStatParams, TradersParams, TradesParams, TrendingTokensRequest, WalletActivityParams, WalletChainBalancesParams, WalletCommonStatParams, WalletPnlParams, WalletRankingsParams, WalletStatParams, WalletTagsStatParams, WebsiteInfoParams } from '../src/services/gmgn/types.js';
import { TaplineError } from '../src/errors.js';
import { typeAt, unknownKeys } from './schema-walk.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(process.env.GENERATE_CLIENT_FIXTURES ?? join(HERE, '..', '..', 'fixtures'), 'gmgn');
const SCHEMAS = JSON.parse(readFileSync(join(HERE, '..', '..', 'spec', 'gmgn', 'schemas.json'), 'utf8'));

interface Input {
  params?: Record<string, unknown>;
  body?: unknown;
  expect?: { status: number; code: string | null };
}

interface Method {
  response: string;
  isArray: boolean;
  call: (client: TaplineClient, input: Input) => Promise<unknown>;
}

const METHODS: Record<string, Method> = {
  gas_price_list: { response: 'GetGasPriceListResponse', isArray: false, call: (c) => c.gmgn.gasPriceList() },
  hot_searches: { response: 'GetHotSearchesResponse', isArray: false, call: (c, i) => c.gmgn.hotSearches(i.body as TrendingTokensRequest) },
  live_twitch_kol: { response: 'GetLiveTwitchKolResponse', isArray: false, call: (c) => c.gmgn.liveTwitchKol() },
  major_coin_prices: { response: 'GetMajorCoinPricesResponse', isArray: false, call: (c, i) => c.gmgn.majorCoinPrices(i.body as SymbolListRequest) },
  trending_tokens: { response: 'GetTrendingTokensResponse', isArray: false, call: (c, i) => c.gmgn.trendingTokens(i.body as TrendingTokensRequest) },
  activity_rank_info: { response: 'GetActivityRankInfoResponse', isArray: false, call: (c, i) => c.gmgn.activityRankInfo(i.params as unknown as ActivityRankInfoParams) },
  agged_token_transfers: { response: 'GetAggedTokenTransfersResponse', isArray: false, call: (c, i) => c.gmgn.aggedTokenTransfers(i.params as unknown as AggedTokenTransfersParams) },
  bluechip_rank: { response: 'GetBluechipRankResponse', isArray: false, call: (c, i) => c.gmgn.bluechipRank(i.params as unknown as BluechipRankParams) },
  dev_created_tokens: { response: 'GetDevCreatedTokensResponse', isArray: false, call: (c, i) => c.gmgn.devCreatedTokens(i.params as unknown as DevCreatedTokensParams) },
  dex_trades_polling: { response: 'GetDexTradesPollingResponse', isArray: false, call: (c, i) => c.gmgn.dexTradesPolling(i.params as unknown as DexTradesPollingParams) },
  launchpad_tax_policy: { response: 'GetLaunchpadTaxPolicyResponse', isArray: false, call: (c, i) => c.gmgn.launchpadTaxPolicy(i.params as unknown as LaunchpadTaxPolicyParams) },
  multi_token_full_info: { response: 'GetMultiTokenFullInfoResponse', isArray: false, call: (c, i) => c.gmgn.multiTokenFullInfo(i.params as unknown as MultiTokenFullInfoParams, i.body as AddressListRequest) },
  multi_token_info: { response: 'GetMultiTokenInfoResponse', isArray: false, call: (c, i) => c.gmgn.multiTokenInfo(i.params as unknown as MultiTokenInfoParams, i.body as AddressListRequest) },
  multi_window_token_info: { response: 'GetMultiWindowTokenInfoResponse', isArray: false, call: (c, i) => c.gmgn.multiWindowTokenInfo(i.params as unknown as MultiWindowTokenInfoParams, i.body as AddressListRequest) },
  native_transfer: { response: 'GetNativeTransferResponse', isArray: false, call: (c, i) => c.gmgn.nativeTransfer(i.params as unknown as NativeTransferParams) },
  new_pairs: { response: 'GetNewPairsResponse', isArray: false, call: (c, i) => c.gmgn.newPairs(i.params as unknown as NewPairsParams) },
  search: { response: 'SearchTokensResponse', isArray: false, call: (c, i) => c.gmgn.search(i.params as unknown as SearchParams) },
  similar_coin_extremes: { response: 'GetSimilarCoinExtremesResponse', isArray: false, call: (c, i) => c.gmgn.similarCoinExtremes(i.params as unknown as SimilarCoinExtremesParams) },
  similar_coins: { response: 'GetSimilarCoinsResponse', isArray: false, call: (c, i) => c.gmgn.similarCoins(i.params as unknown as SimilarCoinsParams) },
  smart_money_wallet_info: { response: 'GetSmartMoneyWalletInfoResponse', isArray: false, call: (c, i) => c.gmgn.smartMoneyWalletInfo(i.params as unknown as SmartMoneyWalletInfoParams) },
  swap_rankings: { response: 'GetSwapRankingsResponse', isArray: false, call: (c, i) => c.gmgn.swapRankings(i.params as unknown as SwapRankingsParams) },
  token_info_brief: { response: 'GetTokenInfoBriefResponse', isArray: false, call: (c, i) => c.gmgn.tokenInfoBrief(i.params as unknown as TokenInfoBriefParams, i.body as AddressListRequest) },
  token_prices: { response: 'GetTokenPricesResponse', isArray: false, call: (c, i) => c.gmgn.tokenPrices(i.params as unknown as TokenPricesParams, i.body as AddressListRequest) },
  token_signals: { response: 'GetTokenSignalsResponse', isArray: false, call: (c, i) => c.gmgn.tokenSignals(i.params as unknown as TokenSignalsParams, i.body as TokenSignalsRequest) },
  agged_token_trades: { response: 'GetAggedTokenTradesResponse', isArray: false, call: (c, i) => c.gmgn.aggedTokenTrades(i.params as unknown as AggedTokenTradesParams) },
  token_ai_narrative: { response: 'GetTokenAiNarrativeResponse', isArray: false, call: (c, i) => c.gmgn.tokenAiNarrative(i.params as unknown as TokenAiNarrativeParams) },
  token_bundler_stat: { response: 'GetTokenBundlerStatResponse', isArray: false, call: (c, i) => c.gmgn.tokenBundlerStat(i.params as unknown as TokenBundlerStatParams) },
  token_candles: { response: 'GetTokenCandlesResponse', isArray: false, call: (c, i) => c.gmgn.tokenCandles(i.params as unknown as TokenCandlesParams) },
  token_community_messages: { response: 'GetTokenCommunityMessagesResponse', isArray: false, call: (c, i) => c.gmgn.tokenCommunityMessages(i.params as unknown as TokenCommunityMessagesParams) },
  token_dev_info: { response: 'GetTokenDevInfoResponse', isArray: false, call: (c, i) => c.gmgn.tokenDevInfo(i.params as unknown as TokenDevInfoParams) },
  token_fee_distribution: { response: 'GetTokenFeeDistributionResponse', isArray: false, call: (c, i) => c.gmgn.tokenFeeDistribution(i.params as unknown as TokenFeeDistributionParams) },
  token_fee_info: { response: 'GetTokenFeeInfoResponse', isArray: false, call: (c, i) => c.gmgn.tokenFeeInfo(i.params as unknown as TokenFeeInfoParams) },
  token_holder_extra_info: { response: 'GetTokenHolderExtraInfoResponse', isArray: false, call: (c, i) => c.gmgn.tokenHolderExtraInfo(i.params as unknown as TokenHolderExtraInfoParams) },
  holder_stat: { response: 'GetTokenHolderStatResponse', isArray: false, call: (c, i) => c.gmgn.holderStat(i.params as unknown as HolderStatParams) },
  holders: { response: 'GetTokenHoldersResponse', isArray: false, call: (c, i) => c.gmgn.holders(i.params as unknown as HoldersParams) },
  liquidity: { response: 'GetTokenLiquidityResponse', isArray: false, call: (c, i) => c.gmgn.liquidity(i.params as unknown as LiquidityParams) },
  token_liquidity_stats: { response: 'GetTokenLiquidityStatsResponse', isArray: false, call: (c, i) => c.gmgn.tokenLiquidityStats(i.params as unknown as TokenLiquidityStatsParams) },
  token_liquidity_trend: { response: 'GetTokenLiquidityTrendResponse', isArray: false, call: (c, i) => c.gmgn.tokenLiquidityTrend(i.params as unknown as TokenLiquidityTrendParams) },
  live_preview: { response: 'GetLiveTokenPreviewResponse', isArray: false, call: (c, i) => c.gmgn.livePreview(i.params as unknown as LivePreviewParams) },
  token_logo_history: { response: 'GetTokenLogoHistoryResponse', isArray: false, call: (c, i) => c.gmgn.tokenLogoHistory(i.params as unknown as TokenLogoHistoryParams) },
  mcap_candles: { response: 'GetTokenMcapCandlesResponse', isArray: false, call: (c, i) => c.gmgn.mcapCandles(i.params as unknown as McapCandlesParams) },
  pool_fee_info: { response: 'GetTokenPoolFeeInfoResponse', isArray: false, call: (c, i) => c.gmgn.poolFeeInfo(i.params as unknown as PoolFeeInfoParams) },
  recommend_slippage: { response: 'GetRecommendSlippageResponse', isArray: false, call: (c, i) => c.gmgn.recommendSlippage(i.params as unknown as RecommendSlippageParams) },
  security: { response: 'GetTokenSecurityResponse', isArray: false, call: (c, i) => c.gmgn.security(i.params as unknown as SecurityParams) },
  socials: { response: 'GetTokenSocialsResponse', isArray: false, call: (c, i) => c.gmgn.socials(i.params as unknown as SocialsParams) },
  stats: { response: 'GetTokenStatsResponse', isArray: false, call: (c, i) => c.gmgn.stats(i.params as unknown as StatsParams) },
  top_buyers: { response: 'GetTopBuyersResponse', isArray: false, call: (c, i) => c.gmgn.topBuyers(i.params as unknown as TopBuyersParams) },
  trader_stat: { response: 'GetTokenTraderStatResponse', isArray: false, call: (c, i) => c.gmgn.traderStat(i.params as unknown as TraderStatParams) },
  traders: { response: 'GetTokenTradersResponse', isArray: false, call: (c, i) => c.gmgn.traders(i.params as unknown as TradersParams) },
  trades: { response: 'GetTokenTradesResponse', isArray: false, call: (c, i) => c.gmgn.trades(i.params as unknown as TradesParams) },
  token_trades_v2: { response: 'GetTokenTradesV2Response', isArray: false, call: (c, i) => c.gmgn.tokenTradesV2(i.params as unknown as TokenTradesV2Params) },
  token_trends: { response: 'GetTokenTrendsResponse', isArray: false, call: (c, i) => c.gmgn.tokenTrends(i.params as unknown as TokenTrendsParams) },
  wallet_tags_stat: { response: 'GetTokenWalletTagsStatResponse', isArray: false, call: (c, i) => c.gmgn.walletTagsStat(i.params as unknown as WalletTagsStatParams) },
  website_info: { response: 'GetWebsiteInfoResponse', isArray: false, call: (c, i) => c.gmgn.websiteInfo(i.params as unknown as WebsiteInfoParams) },
  top_callers: { response: 'GetTopCallersResponse', isArray: false, call: (c, i) => c.gmgn.topCallers(i.params as unknown as TopCallersParams) },
  wallet_activity: { response: 'GetWalletActivityResponse', isArray: false, call: (c, i) => c.gmgn.walletActivity(i.params as unknown as WalletActivityParams) },
  wallet_chain_balances: { response: 'GetWalletChainBalancesResponse', isArray: false, call: (c, i) => c.gmgn.walletChainBalances(i.params as unknown as WalletChainBalancesParams) },
  wallet_common_stat: { response: 'GetWalletCommonStatResponse', isArray: false, call: (c, i) => c.gmgn.walletCommonStat(i.params as unknown as WalletCommonStatParams) },
  wallet_pnl: { response: 'GetSmartMoneyWalletResponse', isArray: false, call: (c, i) => c.gmgn.walletPnl(i.params as unknown as WalletPnlParams) },
  wallet_rankings: { response: 'GetWalletRankingsResponse', isArray: false, call: (c, i) => c.gmgn.walletRankings(i.params as unknown as WalletRankingsParams) },
  wallet_stat: { response: 'GetWalletStatResponse', isArray: false, call: (c, i) => c.gmgn.walletStat(i.params as unknown as WalletStatParams) },
};

const ajv = new Ajv2020({ strict: false, allErrors: true });
ajv.addSchema(SCHEMAS, 'service');

function validator(name: string, isArray: boolean) {
  const ref = { $ref: `service#/$defs/${name}` };
  return ajv.compile(isArray ? { type: 'array', items: ref } : ref);
}

function describe(e: unknown): string {
  if (e instanceof TaplineError) return `HTTP ${e.status} ${e.code}: ${e.message} (request_id=${e.requestId})`;
  return e instanceof Error ? `${e.name}: ${e.message}` : String(e);
}

function stems(): string[] {
  if (!existsSync(FIXTURES)) return [];
  return readdirSync(FIXTURES)
    .filter((f) => f.endsWith('.request.json'))
    .map((f) => f.slice(0, -'.request.json'.length))
    .sort();
}

export async function run(client: TaplineClient): Promise<number> {
  let failures = 0;
  const seen = stems();
  for (const name of Object.keys(METHODS)) {
    if (!seen.includes(`${name}.default`)) {
      console.error(`[FAIL] gmgn.${name}.default: no captured request in ${FIXTURES}; run capture.py`);
      failures += 1;
    }
  }
  for (const stem of seen) {
    const name = stem.split('.', 1)[0]!;
    const method = METHODS[name];
    if (!method) continue;
    const input = JSON.parse(readFileSync(join(FIXTURES, `${stem}.request.json`), 'utf8')) as Input;
    const negative = stem.includes('.neg.');
    try {
      const result = await method.call(client, input);
      if (negative) {
        console.error(`[FAIL] gmgn.${stem}: expected HTTP ${input.expect?.status}, got a 200`);
        failures += 1;
        continue;
      }
      const validate = validator(method.response, method.isArray);
      if (!validate(result)) {
        const rootSchema = method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` };
        const problems = [...new Set((validate.errors ?? []).map((e) => {
          const segments = e.instancePath.split('/').slice(1);
          const ownerSegments = e.keyword === 'required' ? segments : segments.slice(0, -1);
          const ownerPath = ownerSegments.map((p) => (/^\d+$/.test(p) ? `[${p}]` : `.${p}`)).join('');
          const leaf = segments[segments.length - 1] ?? '';
          const owner = typeAt(SCHEMAS.$defs, rootSchema, result, ownerPath) ?? method.response;
          const prop = e.keyword === 'required' ? String((e.params as { missingProperty?: string }).missingProperty) : leaf;
          return `${owner}.${prop}: ${e.keyword} ${e.message}`;
        }))].slice(0, 20);
        console.error(`[FAIL] gmgn.${stem}: body does not match ${method.response}: ${problems.join('; ')}`);
        failures += 1;
        continue;
      }
      const drift = unknownKeys(SCHEMAS.$defs, method.isArray ? { type: 'array', items: { $ref: `#/$defs/${method.response}` } } : { $ref: `#/$defs/${method.response}` }, result, method.response);
      console.log(`[PASS] gmgn.${stem}${drift.length ? ` (${drift.length} undocumented key(s), e.g. ${drift[0]})` : ''}`);
    } catch (e) {
      if (negative && e instanceof TaplineError) {
        const expected = input.expect!;
        const body = { code: e.code, message: e.message, request_id: e.requestId, domain: e.domain, details: e.details };
        const validate = validator('ErrorResponse', false);
        const problems: string[] = [];
        if (e.status !== expected.status) problems.push(`expected HTTP ${expected.status}, got ${e.status}`);
        if (expected.code && e.code !== expected.code) problems.push(`expected code ${expected.code}, got ${e.code}`);
        if (!validate(body)) problems.push(`error body does not match ErrorResponse: ${(validate.errors ?? []).map((x) => x.message).join('; ')}`);
        if (problems.length > 0) {
          console.error(`[FAIL] gmgn.${stem}: ${problems.join('; ')}`);
          failures += 1;
        } else {
          console.log(`[PASS] gmgn.${stem}: ${e.status} ${e.code}`);
        }
        continue;
      }
      console.error(`[FAIL] gmgn.${stem}: ${describe(e)} input=${JSON.stringify(input)}`);
      failures += 1;
    }
  }
  return failures;
}
