// Generated by generate-client from spec/openapi.json. Do not edit.

export interface ErrorDetail {
  ctx?: Record<string, unknown> | null;
  input?: unknown | null;
  loc?: (string | number)[] | null;
  msg?: string | null;
  type?: string | null;
}

export interface ErrorResponse {
  code: PublicError;
  details?: ErrorDetail[] | null;
  domain?: string | null;
  message: string;
  request_id: string;
  upgrade_url?: string | null;
}

export interface GetBoardParams {
  /** The `cursor` from the previous page. Omit it, or send it empty, for the first page. */
  cursor?: string | null;
  /** Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body. */
  trim?: boolean | null;
  /** A Pinterest board URL: `https://www.pinterest.com/<username>/<board>/` on any Pinterest domain, or the relative `/<username>/<board>/` that `/user/boards` returns as `url`. */
  url: string;
}

export interface GetPinParams {
  /** Accepted for Scrape Creators compatibility. It has no effect: every request fetches a live answer and is charged. */
  cache_max_age?: "1d" | "3d" | "7d" | "14d" | "30d" | null;
  /** Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body. */
  trim?: boolean | null;
  /** A Pinterest pin URL: `https://www.pinterest.com/pin/<id>/` on any Pinterest domain, the long form with a title (`/pin/<title>--<id>/`), or a `https://pin.it/<code>` share link. */
  url: string;
}

export interface GetUserBoardsParams {
  /** The `cursor` from the previous page. Omit it, or send it empty, for the first page. */
  cursor?: string | null;
  /** The Pinterest username, with or without a leading @. */
  handle: string;
  /** Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body. */
  trim?: boolean | null;
}

export interface PinterestAggregatedStats {
  done?: number;
  saves?: number;
}

export interface PinterestAudio {
  artist_name?: string;
  audio_url?: string;
  description?: string;
  duration?: number;
  id?: string;
  node_id?: string;
  provider_recording_id?: string;
  royalty_free?: boolean;
  thumbnail_image_url?: string;
  title?: string;
  type?: string;
}

export interface PinterestBlockImage {
  dominant_color?: string;
  images?: Record<string, PinterestSearchStoryObjectImage>;
}

export interface PinterestBoardCoverImages {
  "236x"?: PinterestBoardCoverImages236x;
}

export interface PinterestBoardCoverImages236x {
  url?: string;
  width?: number;
}

export interface PinterestBoardFeedPin {
  access?: unknown[];
  aggregated_pin_data?: PinterestBoardFeedPinAggregatedPinData;
  alt_text?: string | null;
  attribution?: unknown | null;
  auto_alt_text?: string | null;
  board?: PinterestBoardFeedPinBoard;
  call_to_action_text?: unknown | null;
  campaign_id?: unknown | null;
  carousel_data?: unknown | null;
  category?: string;
  collection_pin?: unknown | null;
  creator_analytics?: unknown | null;
  description?: string;
  digital_media_source_type?: number | null;
  domain?: string;
  dominant_color?: string;
  done_by_me?: boolean;
  embed?: unknown | null;
  favorite_user_count?: number;
  favorited_by_me?: boolean;
  grid_affiliate_disclosure?: unknown | null;
  grid_attribution?: PinterestBoardFeedPinGridAttribution | null;
  grid_title?: string;
  has_been_boost_promoted?: boolean;
  id?: string;
  image_crop?: PinterestSearchStoryObjectImageCrop;
  image_signature?: string;
  images?: Record<string, PinterestBoardFeedPinImage>;
  insertion_id?: unknown | null;
  is_downstream_promotion?: boolean;
  is_eligible_for_pdp?: boolean;
  is_eligible_for_pre_loved_goods_label?: boolean;
  is_eligible_for_related_products?: boolean;
  is_go_linkless?: boolean;
  is_oos_product?: boolean;
  is_promoted?: boolean;
  is_quick_promotable?: boolean;
  is_quick_promotable_by_pinner?: boolean;
  is_repin?: boolean;
  is_stale_product?: boolean;
  is_video?: boolean;
  link?: string | null;
  link_domain?: PinterestLinkDomain | null;
  link_utm_applicable_and_replaced?: number;
  native_creator?: PinterestNativeCreator | null;
  node_id?: string;
  pinner?: PinterestBoardFeedPinPinner;
  product_metadata?: PinterestProductMetadata | null;
  product_pin_data?: unknown | null;
  promoted_is_lead_ad?: boolean;
  promoted_is_removable?: boolean;
  promoted_lead_form?: unknown | null;
  promoter?: unknown | null;
  reaction_counts?: Record<string, number>;
  repin_count?: number;
  rich_summary?: PinterestBoardFeedPinRichSummary | null;
  seo_alt_text?: string;
  seo_url?: string;
  shopping_flags?: number[];
  should_open_in_stream?: boolean;
  sponsorship?: unknown | null;
  story_pin_data?: PinterestBoardFeedPinStoryPinData | null;
  story_pin_data_id?: string | null;
  title?: string;
  tracking_params?: string;
  type?: string;
  unauth_on_page_description?: string;
  unified_user_note?: string | null;
  utm_link?: string | null;
  video_status?: unknown | null;
  video_status_message?: unknown | null;
  videos?: unknown | null;
}

export interface PinterestBoardFeedPinAggregatedPinData {
  aggregated_stats?: PinterestAggregatedStats;
  creator_analytics?: unknown | null;
  did_it_data?: PinterestDidItData;
  id?: string;
  is_shop_the_look?: boolean;
  node_id?: string;
}

export interface PinterestBoardFeedPinBoard {
  collaborated_by_me?: boolean;
  followed_by_me?: boolean;
  id?: string;
  is_collaborative?: boolean;
  layout?: string;
  name?: string;
  node_id?: string;
  owner?: PinterestBoardFeedPinPinner;
  privacy?: string;
  type?: string;
  url?: string;
}

export interface PinterestBoardFeedPinGridAttribution {
  full_name?: string;
  id?: string;
  image_medium_url?: string | null;
  image_small_url?: string | null;
  is_primary_website_verified?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestVerifiedIdentity;
}

export interface PinterestBoardFeedPinImage {
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestBoardFeedPinPinner {
  full_name?: string;
  id?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_primary_website_verified?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestSearchStoryDynamicInsertionOption;
}

export interface PinterestBoardFeedPinRichSummary {
  actions?: unknown[];
  aggregate_rating?: PinterestBoardFeedPinRichSummaryAggregateRating;
  apple_touch_icon_images?: unknown | null;
  apple_touch_icon_link?: unknown | null;
  display_description?: string;
  display_name?: string;
  favicon_images?: PinterestFaviconImages;
  favicon_link?: string;
  id?: string;
  is_hard_404?: boolean;
  is_soft_404?: boolean;
  products?: PinterestBoardFeedPinRichSummaryProduct[];
  site_name?: string | null;
  type?: string;
  type_name?: string;
  url?: string;
}

export interface PinterestBoardFeedPinRichSummaryAggregateRating {
  id?: string;
  name?: unknown | null;
  rating_count?: number;
  rating_distribution?: unknown[];
  rating_value?: string;
  review_count?: number;
  type?: string;
}

export interface PinterestBoardFeedPinRichSummaryProduct {
  additional_images?: unknown | null;
  additional_images_per_spec?: unknown | null;
  has_multi_images?: boolean;
  id?: string;
  item_id?: string;
  item_set_id?: string;
  label_info?: PinterestSearchStoryDynamicInsertionOption;
  name?: string;
  offer_summary?: PinterestBoardFeedPinRichSummaryProductOfferSummary;
  offers?: PinterestBoardFeedPinRichSummaryProductOffer[];
  price_history_summary?: PinterestSearchStoryDynamicInsertionOption;
  purchase_url?: unknown | null;
  shipping_info?: PinterestShippingInfo;
  type?: string;
  variant_set?: unknown | null;
  videos?: unknown[];
}

export interface PinterestBoardFeedPinRichSummaryProductOffer {
  availability?: number;
  condition?: number;
  id?: string;
  in_stock?: boolean;
  min_ad_price?: unknown | null;
  name?: unknown | null;
  price_currency?: string;
  price_value?: number;
  type?: string;
}

export interface PinterestBoardFeedPinRichSummaryProductOfferSummary {
  availability?: number;
  condition?: number;
  currency?: string;
  in_stock?: boolean;
  price?: string;
  price_val?: number;
}

export interface PinterestBoardFeedPinStoryPinData {
  has_affiliate_products?: boolean;
  has_product_pins?: boolean;
  id?: string;
  is_deleted?: boolean;
  metadata?: PinterestBoardFeedPinStoryPinDataMetadata;
  node_id?: string;
  page_count?: number;
  pages?: PinterestBoardFeedPinStoryPinDataPage[];
  static_page_count?: number;
  total_video_duration?: number;
  type?: string;
}

export interface PinterestBoardFeedPinStoryPinDataMetadata {
  basics?: PinterestBoardFeedPinStoryPinDataMetadataBasic | null;
  canvas_aspect_ratio?: number;
  compatible_version?: string;
  diy_data?: unknown | null;
  is_compatible?: boolean;
  is_editable?: boolean;
  is_promotable?: boolean;
  pin_image_signature?: string;
  pin_title?: string;
  recipe_data?: unknown | null;
  root_pin_id?: string;
  root_user_id?: string;
  showreel_data?: unknown | null;
  template_type?: unknown | null;
  version?: string;
}

export interface PinterestBoardFeedPinStoryPinDataMetadataBasic {
  key_value_blocks?: unknown[];
  list_blocks?: unknown[];
}

export interface PinterestBoardFeedPinStoryPinDataPage {
  blocks?: PinterestBoardFeedPinStoryPinDataPageBlock[];
}

export interface PinterestBoardFeedPinStoryPinDataPageBlock {
  block_style?: PinterestBoardFeedPinStoryPinDataPageBlockBlockStyle;
  block_type?: number;
  image?: PinterestBlockImage;
  image_signature?: string;
  type?: string;
}

export interface PinterestBoardFeedPinStoryPinDataPageBlockBlockStyle {
  corner_radius?: number;
  height?: number;
  rotation?: number;
  width?: number;
  x_coord?: number;
  y_coord?: number;
}

export interface PinterestBoardFeedStorySubtitle {
  args?: unknown[];
  args_reformatted?: unknown[];
  format?: string;
  text?: unknown | null;
}

export interface PinterestBoardImage474x {
  dominant_color?: string;
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestBoardImages {
  "236x"?: PinterestBoardImage474x[];
}

export interface PinterestBoardResponse {
  cursor: string | null;
  pins: PinterestBoardFeedPin[];
}

export interface PinterestBoardVase {
  link?: string;
  text?: string;
  type?: string;
}

export interface PinterestCollaboratingUser {
  follower_count?: number;
  full_name?: string;
  id?: string;
  image_large_url?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_ads_only_profile?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestSearchStoryDynamicInsertionOption;
}

export interface PinterestCollectionPin {
  item_data?: PinterestItemData[];
}

export interface PinterestDidItData {
  details_count?: number;
  images_count?: number;
  rating?: number;
  recommend_scores?: PinterestRecommendScore[];
  recommended_count?: number;
  responses_count?: number;
  tags?: unknown[];
  type?: string;
  user_count?: number;
  videos_count?: number;
}

export interface PinterestFaviconImages {
  orig?: string;
}

export interface PinterestGenAITopic {
  interest_id?: number;
  interest_id_str?: string;
  name?: string;
}

export interface PinterestItemData {
  active?: boolean;
  dominant_color?: string;
  image_signature?: string;
  images?: Record<string, PinterestSearchStoryObjectImage>;
  is_editable?: boolean;
  item_id?: string;
  link?: string;
  pin_id?: string;
  price_currency?: string;
  price_value?: number;
  rich_metadata?: PinterestRichMetadata;
  rich_summary?: PinterestItemDataRichSummary;
  showcase_features_count?: number;
  source?: number;
  title?: string;
  type?: string;
}

export interface PinterestItemDataRichSummary {
  actions?: unknown[];
  aggregate_rating?: PinterestRichMetadataAggregateRating;
  display_name?: string;
  id?: string;
  products?: PinterestItemDataRichSummaryProduct[];
  site_name?: string;
  type?: string;
  type_name?: string;
}

export interface PinterestItemDataRichSummaryProduct {
  id?: string;
  item_id?: string;
  item_set_id?: string;
  name?: string;
  offer_summary?: PinterestRichMetadataProductOfferSummary;
  offers?: PinterestObjectRichSummaryProductOffer[];
  type?: string;
  videos?: unknown[];
}

export interface PinterestLinkDomain {
  id?: string;
}

export interface PinterestLinkUserWebsite {
  node_id?: string;
  official_user?: PinterestPromoter;
}

export interface PinterestMusicAttribution {
  artist?: string;
  is_embedded?: boolean;
  provider_recording_id?: string;
  thumbnail_image_url?: string;
  title?: string;
}

export interface PinterestNativeCreator {
  full_name?: string;
  id?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_primary_website_verified?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestVerifiedIdentity;
}

export interface PinterestObjectRichSummaryProduct {
  id?: string;
  item_id?: string;
  item_set_id?: string;
  name?: string;
  offer_summary?: PinterestObjectRichSummaryProductOfferSummary;
  offers?: PinterestObjectRichSummaryProductOffer[];
  type?: string;
  videos?: unknown[];
}

export interface PinterestObjectRichSummaryProductOffer {
  availability?: number;
  condition?: number;
  id?: string;
  in_stock?: boolean;
  price_currency?: string;
  price_value?: number;
  type?: string;
}

export interface PinterestObjectRichSummaryProductOfferSummary {
  availability?: number;
  condition?: number;
  currency?: string;
  in_stock?: boolean;
  percentage_off?: string;
  percentage_off_raw?: number;
  price?: string;
  price_val?: number;
  standard_price?: string;
}

export interface PinterestPinAggregatedPinData {
  aggregatedStats?: PinterestPinAggregatedStats;
  commentCount?: number;
  didItData?: PinterestPinDidItData;
  entityId?: string;
  id?: string;
  isShopTheLook?: boolean;
}

export interface PinterestPinAggregatedStats {
  saves?: number;
}

export interface PinterestPinAnnotationsWithLinksArray {
  name?: string;
  url?: string;
}

export interface PinterestPinBlockStyle {
  height?: number;
  width?: number;
  xCoord?: number;
  yCoord?: number;
}

export interface PinterestPinBoard {
  boardOrderModifiedAt?: string;
  collaboratedByMe?: boolean;
  collaboratorPermissions?: unknown | null;
  coverImageSpec_216x146?: PinterestPinImageSpec;
  coverImageSpec_236x?: PinterestPinImageSpec;
  coverImageSpec_400x300?: PinterestPinImageSpec;
  entityId?: string;
  followedByMe?: boolean;
  id?: string;
  imageCoverHdUrl?: string;
  imageCoverUrl?: string;
  imageThumbnailUrl?: string;
  isCollaborative?: boolean;
  layout?: string;
  name?: string;
  owner?: PinterestPinOwner;
  pinCount?: number;
  privacy?: string;
  sectionCount?: number;
  url?: string;
}

export interface PinterestPinCategorizedIngredient {
  __typename?: string;
  category?: string;
  ingredients?: PinterestPinIngredient[];
}

export interface PinterestPinCloseupAttribution {
  entityId?: string;
  firstName?: string;
  fullName?: string;
  id?: string;
  username?: string;
}

export interface PinterestPinCloseupDataStoryPinDataPageStyle {
  backgroundColor?: string;
}

export interface PinterestPinCloseupUnifiedAttribution {
  __typename?: string;
  adsOnlyProfileSite?: unknown | null;
  entityId?: string;
  followedByMe?: boolean;
  followerCount?: number;
  fullName?: string;
  id?: string;
  imageMediumUrl?: string;
  isAdsOnlyProfile?: boolean;
  isVerifiedMerchant?: boolean;
  username?: string;
  verifiedIdentity?: PinterestPinCloseupUnifiedAttributionVerifiedIdentity;
}

export interface PinterestPinCloseupUnifiedAttributionVerifiedIdentity {
  verified?: boolean | null;
}

export interface PinterestPinCook {
  h?: unknown | null;
  m?: number;
}

export interface PinterestPinCookTimes {
  cook?: PinterestPinCook | null;
  prep?: PinterestPinCook | null;
  total?: unknown | null;
}

export interface PinterestPinDetailsDataRichMetadataRecipe {
  __typename?: string;
  aggregateRating?: PinterestPinRecipeAggregateRating;
  categorizedIngredients?: PinterestPinCategorizedIngredient[];
  cookTimes?: PinterestPinCookTimes;
  diets?: unknown[];
  displayCookTime?: number;
  fromAggregatedData?: boolean;
  name?: string;
  servingsSummary?: PinterestPinServingsSummary;
}

export interface PinterestPinDetailsDataStoryPinDataPageBlockVideoDataV2VideoList720P {
  v720P?: PinterestPinVideoVariant;
}

export interface PinterestPinDidItData {
  imagesCount?: number;
}

export interface PinterestPinGenAITopic {
  interestIdStr?: string;
  name?: string;
}

export interface PinterestPinGridAttribution {
  entityId?: string;
  fullName?: string;
  id?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  isVerifiedMerchant?: boolean;
  username?: string;
  verifiedIdentity?: PinterestPinCloseupUnifiedAttributionVerifiedIdentity;
}

export interface PinterestPinImageSpec {
  url?: string;
}

export interface PinterestPinImageSpecOrig {
  url?: string;
}

export interface PinterestPinImages {
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestPinImages236X {
  dominantColor?: unknown | null;
  height?: number;
  type?: unknown | null;
  url?: string;
  width?: number;
}

export interface PinterestPinImagesOrig {
  __typename?: string;
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestPinIngredient {
  amt?: string;
  name?: string;
}

export interface PinterestPinJoin {
  visual_annotation?: string[];
}

export interface PinterestPinLinkDomain {
  id?: string;
  name?: string;
  officialUser?: PinterestPinLinkDomainOfficialUser | null;
}

export interface PinterestPinLinkDomainOfficialUser {
  __typename?: string;
  blockedByMe?: boolean;
  entityId?: string;
  explicitlyFollowedByMe?: boolean;
  firstName?: string;
  followerCount?: number;
  fullName?: string;
  id?: string;
  imageLargeUrl?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  isVerifiedMerchant?: boolean;
  username?: string;
  verifiedIdentity?: PinterestPinCloseupUnifiedAttributionVerifiedIdentity;
}

export interface PinterestPinMetadata {
  basics?: unknown | null;
  pinTitle?: string;
  templateType?: unknown | null;
}

export interface PinterestPinNativeCreator {
  __typename?: string;
  blockedByMe?: boolean;
  entityId?: string;
  explicitlyFollowedByMe?: boolean;
  firstName?: string;
  followerCount?: number;
  fullName?: string;
  id?: string;
  imageLargeUrl?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  isDirectToSiteAllowed?: boolean;
  isPrimaryWebsiteVerified?: boolean;
  isVerifiedMerchant?: boolean;
  profileUrl?: string;
  username?: string;
  verifiedIdentity?: PinterestPinCloseupUnifiedAttributionVerifiedIdentity;
  websiteUrl?: string | null;
}

export interface PinterestPinOriginPinner {
  blockedByMe?: boolean;
  entityId?: string;
  explicitlyFollowedByMe?: boolean;
  followerCount?: number;
  fullName?: string;
  id?: string;
  imageLargeUrl?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  isVerifiedMerchant?: boolean;
  username?: string;
  verifiedIdentity?: PinterestPinCloseupUnifiedAttributionVerifiedIdentity;
}

export interface PinterestPinOwner {
  entityId?: string;
  id?: string;
}

export interface PinterestPinPinJoin {
  annotationsWithLinksArray?: PinterestPinAnnotationsWithLinksArray[];
  canonicalPin?: PinterestPinOwner | null;
  interlinkEntries?: unknown | null;
  seoBreadcrumbs?: PinterestPinSeoBreadcrumb[];
  seoCanonicalDomain?: string;
  seoCanonicalUrl?: string | null;
  seoRelatedInterests?: PinterestPinAnnotationsWithLinksArray[] | null;
  shoppingKlpUrls?: unknown | null;
  visualAnnotation?: string[];
}

export interface PinterestPinPinner {
  __typename?: string;
  blockedByMe?: boolean;
  connectionType?: string;
  domainUrl?: string | null;
  domainVerified?: boolean;
  entityId?: string;
  explicitlyFollowedByMe?: boolean;
  followerCount?: number;
  fullName?: string;
  id?: string;
  imageLargeUrl?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  isVerifiedMerchant?: boolean;
  username?: string;
  verifiedIdentity?: PinterestPinnerVerifiedIdentity;
}

export interface PinterestPinPromoter {
  __typename?: string;
  entityId?: string;
  fullName?: string;
  id?: string;
  imageMediumUrl?: string;
  imageSmallUrl?: string;
  username?: string;
}

export interface PinterestPinReactionCountsData {
  reactionCount?: number;
  reactionType?: number;
}

export interface PinterestPinRecipeAggregateRating {
  __typename?: string;
  bestRating?: unknown | null;
  ratingCount?: number | null;
  ratingValue?: string;
  reviewCount?: number;
}

export interface PinterestPinResponse {
  __typename?: string;
  adData?: unknown | null;
  adMatchReason?: number;
  adTargetingAttribution?: unknown | null;
  adTargetingAttributionReasons?: unknown | null;
  advertiserId?: string | null;
  affiliateDisclosure?: string | null;
  affiliateLink?: unknown | null;
  aggregatedPinData?: PinterestPinAggregatedPinData;
  attribution?: unknown | null;
  board?: PinterestPinBoard;
  boostAdsData?: unknown | null;
  campaignId?: string | null;
  canDeleteDidItAndComments?: boolean;
  carouselData?: unknown | null;
  category?: string;
  closeupAttribution?: PinterestPinCloseupAttribution;
  closeupUnifiedAttribution?: PinterestPinCloseupUnifiedAttribution;
  closeupUnifiedDescription?: string;
  closeupUnifiedTitle?: string;
  collectionPin?: unknown | null;
  commentsDisabled?: boolean;
  createdAt?: string;
  creativeOverlayImages?: unknown | null;
  creatorClass?: unknown | null;
  description?: string;
  descriptionHtml?: string;
  descriptionLinks?: unknown[];
  digitalMediaSourceType?: number | null;
  domain?: string;
  dominantColor?: string;
  doneByMe?: boolean;
  embed?: unknown | null;
  entityId?: string;
  genAiTopics?: PinterestPinGenAITopic[] | null;
  gridAttribution?: PinterestPinGridAttribution | null;
  gridDescription?: string;
  gridTitle?: string;
  hasActiveBoostAds?: boolean;
  hasBeenBoostPromoted?: boolean;
  hasHiddenInnerPin?: boolean;
  id?: string;
  imageLargeUrl?: string;
  imageSignature?: string;
  imageSpec_136x136?: PinterestPinImageSpec;
  imageSpec_170x?: PinterestPinImageSpec;
  imageSpec_236x?: PinterestPinImageSpec;
  imageSpec_474x?: PinterestPinImageSpec;
  imageSpec_564x?: PinterestPinImageSpec;
  imageSpec_600x315?: PinterestPinImageSpec;
  imageSpec_60x60?: PinterestPinImageSpec;
  imageSpec_736x?: PinterestPinImageSpec;
  imageSpec_orig?: PinterestPinImageSpecOrig;
  images_136x136?: PinterestPinImages;
  images_170x?: PinterestPinImages;
  images_236x?: PinterestPinImages236X;
  images_474x?: PinterestPinImages;
  images_564x?: PinterestPinImages;
  images_600x315?: PinterestPinImageSpec;
  images_60x60?: PinterestPinImageSpec;
  images_736x?: PinterestPinImages;
  images_orig?: PinterestPinImagesOrig;
  interestItemIdStr?: unknown | null;
  isActiveAd?: boolean;
  isDownstreamPromotion?: boolean;
  isEligibleForAggregatedComments?: boolean;
  isEligibleForImageDownload?: boolean;
  isEligibleForPdp?: boolean;
  isEligibleForPromotedPartnership?: boolean;
  isGoLinkless?: boolean;
  isHidden?: boolean;
  isInstagramApi?: boolean;
  isOosProduct?: boolean;
  isPromoted?: boolean;
  isQuickPromotableByPinner?: boolean;
  isRepin?: boolean;
  isStaleProduct?: boolean;
  isThirdPartyAd?: boolean;
  isUnsafe?: boolean;
  isUnsafeForAd?: boolean;
  isUnsafeForComments?: boolean;
  isV1IdeaPin?: boolean | null;
  isVideo?: boolean;
  isViewedByOwnerOrEmployeeOrPartnerOfBusiness?: unknown | null;
  isViewerRestricted?: boolean;
  link?: string | null;
  linkDomain?: PinterestPinLinkDomain | null;
  linkId?: string | null;
  linkUserWebsite?: unknown | null;
  linkUtmApplicableAndReplaced?: number;
  mediaAttribution?: unknown | null;
  method?: string;
  mobileLink?: unknown | null;
  musicAttributions?: unknown[];
  nativeCreator?: PinterestPinNativeCreator | null;
  originPinner?: PinterestPinOriginPinner | null;
  pinAdditionalNote?: unknown | null;
  pinJoin?: PinterestPinPinJoin;
  pinPromotionId?: string | null;
  pinnabilityMultiScoresStringified?: unknown | null;
  pinnedToBoard?: unknown | null;
  pinner?: PinterestPinPinner;
  priceCurrency?: string;
  productPinData?: unknown | null;
  promotedIsLeadAd?: boolean;
  promotedIsPersonalized?: unknown | null;
  promotedIsRemovable?: boolean;
  promotedLeadForm?: unknown | null;
  promotedPartnershipAdvertiserName?: unknown | null;
  promotedPartnershipAttributionName?: unknown | null;
  promoter?: PinterestPinPromoter | null;
  reactionByMe?: number;
  reactionCountsData?: PinterestPinReactionCountsData[];
  recommendationReason?: unknown | null;
  repinCount?: number;
  richMetadata?: PinterestPinRichMetadata | null;
  richSummary?: PinterestPinRichSummary | null;
  section?: PinterestPinOwner | null;
  seeMoreUserFeedback?: unknown | null;
  seoAltText?: string;
  seoDescription?: string;
  seoNoindexReason?: string | null;
  seoTitle?: string;
  seoUrl?: string;
  shareCount?: number;
  shipsToUserCountry?: boolean;
  shoppingFlags?: number[];
  shouldMute?: boolean;
  shouldOpenInStream?: boolean;
  shuffle?: PinterestPinShuffle | null;
  shuffleAsset?: unknown | null;
  sourceInterest?: unknown | null;
  sponsorship?: unknown | null;
  storyPinData?: PinterestPinStoryPinData | null;
  storyPinDataId?: string | null;
  thirdPartyPinOwner?: unknown | null;
  title?: string;
  topInterest?: number;
  totalReactionCount?: number;
  trackedLink?: string | null;
  trackingParams?: string;
  translations?: unknown | null;
  unauthOnGridTitle?: string | null;
  unauthOnPageDescription?: string;
  unauthOnPageTitle?: string;
  userInterestCluster?: unknown | null;
  userMentionTags?: unknown | null;
  utmLink?: string | null;
  videoStatus?: unknown | null;
  videos?: PinterestPinVideos | null;
  visualObjects?: PinterestPinVisualObject[];
}

export interface PinterestPinRichMetadata {
  __typename?: string;
  aggregateRating?: PinterestPinRichMetadataAggregateRating | null;
  article?: PinterestPinRichMetadataArticle | null;
  description?: string;
  products?: unknown | null;
  recipe?: PinterestPinDetailsDataRichMetadataRecipe | null;
  siteName?: string;
  title?: string;
  tutorial?: unknown | null;
  url?: string;
}

export interface PinterestPinRichMetadataAggregateRating {
  bestRating?: unknown | null;
  ratingCount?: number | null;
  ratingValue?: string;
  reviewCount?: number;
}

export interface PinterestPinRichMetadataArticle {
  __typename?: string;
  datePublished?: string;
  name?: string;
}

export interface PinterestPinRichSummary {
  aggregateRating?: PinterestPinRichMetadataAggregateRating | null;
  displayName?: string;
  products?: unknown[];
  typeName?: string;
}

export interface PinterestPinSeoBreadcrumb {
  __typename?: string;
  name?: string;
  url?: string;
}

export interface PinterestPinServingsSummary {
  __typename?: string;
  serves?: string | null;
  summary?: string | null;
}

export interface PinterestPinShuffle {
  __typename?: string;
  entityId?: string;
  id?: string;
  isRemixable?: boolean;
}

export interface PinterestPinStoryPinData {
  __typename?: string;
  entityId?: string;
  hasAffiliateProducts?: boolean;
  id?: string;
  isDeleted?: boolean;
  metadata?: PinterestPinMetadata;
  pages?: PinterestPinStoryPinDataPage[];
  totalVideoDuration?: number;
}

export interface PinterestPinStoryPinDataPage {
  __typename?: string;
  ad?: unknown | null;
  blocks?: PinterestPinStoryPinDataPageBlock[];
  imageAdjustedSpec_orig?: unknown | null;
  images_originals?: unknown | null;
  layout?: number;
  musicAttributions?: unknown[];
  pageId?: string;
  shouldMute?: boolean;
  storyPageId?: string;
  style?: PinterestPinCloseupDataStoryPinDataPageStyle | null;
}

export interface PinterestPinStoryPinDataPageBlock {
  __typename?: string;
  blockStyle?: PinterestPinBlockStyle;
  blockType?: number;
  images_750x?: PinterestPinImages;
  images_orig?: unknown | null;
  text?: string;
  videoDataV2?: PinterestPinStoryPinDataPageBlockVideoDataV2;
}

export interface PinterestPinStoryPinDataPageBlockVideoDataV2 {
  seoViewCount?: string;
  v_hlsv4_video_list?: PinterestPinVHlsv4VideoList;
  videoList?: PinterestPinStoryPinDataPageBlockVideoDataV2VideoList;
  videoList720P?: PinterestPinDetailsDataStoryPinDataPageBlockVideoDataV2VideoList720P;
  videoListEXP3?: unknown | null;
  videoListEXP4?: unknown | null;
  videoListEXP5?: unknown | null;
  videoListEXP6?: unknown | null;
  videoListEXP7?: unknown | null;
  videoListForCaptions?: PinterestPinVideoListForCaptions;
  videoListMobile?: PinterestPinVideoList;
}

export interface PinterestPinStoryPinDataPageBlockVideoDataV2VideoList {
  vHLSV3MOBILE?: PinterestPinVideoVariant;
}

export interface PinterestPinTagsChip {
  dominant_color?: string;
  id?: string;
  image_signature?: string;
  images?: Record<string, PinterestPinTagsChipImage>;
  item_id?: string;
  link?: string;
  price_currency?: string;
  price_value?: number;
  title?: string;
}

export interface PinterestPinTagsChipImage {
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestPinVHlsv4VideoList {
  vHLSV4?: PinterestPinVideoVariant;
}

export interface PinterestPinVideoList {
  vHLSV3MOBILE?: PinterestPinVideoVariant;
}

export interface PinterestPinVideoListForCaption {
  captionsUrls?: Record<string, string> | null;
}

export interface PinterestPinVideoListForCaptions {
  v720P?: PinterestPinVideoVariant;
}

export interface PinterestPinVideoVariant {
  __typename?: string;
  captionsUrls?: Record<string, string> | null;
  duration?: number;
  height?: number;
  thumbnail?: string;
  url?: string;
  width?: number;
}

export interface PinterestPinVideos {
  duration?: number;
  entityId?: string;
  id?: string;
  seoViewCount?: string;
  signature?: string;
  videoList?: PinterestPinVideosVideoList;
  videoListForCaptions?: Record<string, PinterestPinVideoListForCaption>;
  videoUrls?: string[];
}

export interface PinterestPinVideosVideoList {
  __typename?: string;
  v720P?: PinterestPinVideoVariant;
  vHLSV3MOBILE?: PinterestPinVideoVariant;
  vHLSV4?: PinterestPinVideoVariant;
}

export interface PinterestPinVisualObject {
  h?: number;
  isStela?: unknown | null;
  w?: number;
  x?: number;
  y?: number;
}

export interface PinterestPinnerVerifiedIdentity {
  verified?: unknown | null;
}

export interface PinterestProductMetadata {
  id?: string;
  type?: string;
}

export interface PinterestPromoter {
  follower_count?: number;
  full_name?: string;
  id?: string;
  image_large_url?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_ads_only_profile?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestSearchStoryDynamicInsertionOption;
}

export interface PinterestRecommendScore {
  count?: number;
  score?: number;
}

export interface PinterestRichMetadata {
  aggregate_rating?: PinterestRichMetadataAggregateRating;
  amp_url?: string;
  amp_valid?: boolean;
  canonical_url?: string;
  description?: string;
  has_price_drop?: boolean;
  id?: string;
  link_status?: number;
  locale?: string;
  products?: PinterestRichMetadataProduct[];
  site_name?: string;
  title?: string;
  type?: string;
}

export interface PinterestRichMetadataAggregateRating {
  best_rating?: string;
  id?: string;
  rating_count?: number;
  rating_distribution?: unknown[];
  rating_value?: string;
  review_count?: number;
  type?: string;
}

export interface PinterestRichMetadataProduct {
  additional_images?: unknown[];
  id?: string;
  item_id?: string;
  item_set_id?: string;
  name?: string;
  offer_summary?: PinterestRichMetadataProductOfferSummary;
  offers?: PinterestObjectRichSummaryProductOffer[];
  type?: string;
  videos?: unknown[];
}

export interface PinterestRichMetadataProductOfferSummary {
  availability?: number;
  condition?: number;
  currency?: string;
  in_stock?: boolean;
  price?: string;
  price_val?: number;
  standard_price?: string;
}

export interface PinterestSearchPin {
  access?: unknown[];
  ad_match_reason?: number;
  advertiser_id?: string;
  aggregated_pin_data?: PinterestSearchResultAggregatedPinData;
  alt_text?: string;
  auto_alt_text?: string;
  board?: PinterestSearchResultBoard;
  campaign_id?: number;
  collection_pin?: PinterestCollectionPin;
  created_at?: string;
  description?: string;
  did_its?: unknown[];
  digital_media_source_type?: number;
  domain?: string;
  dominant_color?: string;
  gen_ai_topics?: PinterestGenAITopic[];
  grid_attribution?: PinterestSearchStoryObjectGridAttribution;
  grid_title?: string;
  id?: string;
  image_crop?: PinterestSearchResultImageCrop;
  image_signature?: string;
  images?: Record<string, PinterestSearchResultImage>;
  insertion_id?: string;
  is_downstream_promotion?: boolean;
  is_eligible_for_filters?: boolean;
  is_eligible_for_pdp?: boolean;
  is_eligible_for_pre_loved_goods_label?: boolean;
  is_eligible_for_related_products?: boolean;
  is_eligible_for_web_closeup?: boolean;
  is_go_linkless?: boolean;
  is_oos_product?: boolean;
  is_prefetch_enabled?: boolean;
  is_promoted?: boolean;
  is_stale_product?: boolean;
  link?: string;
  link_domain?: PinterestLinkDomain;
  link_user_website?: PinterestLinkUserWebsite;
  link_utm_applicable_and_replaced?: number;
  node_id?: string;
  pin_join?: PinterestPinJoin;
  pin_promotion_id?: number;
  pinner?: PinterestSearchResultPinner;
  product_metadata?: PinterestProductMetadata;
  promoted_is_lead_ad?: boolean;
  promoted_is_removable?: boolean;
  promoter?: PinterestPromoter;
  reaction_counts?: Record<string, number>;
  rich_summary?: PinterestSearchResultRichSummary;
  seo_alt_text?: string;
  shopping_flags?: number[];
  should_open_in_stream?: boolean;
  story_pin_data?: PinterestSearchResultStoryPinData;
  story_pin_data_id?: string;
  title?: string;
  tracking_params?: string;
  type?: string;
  url: string;
  utm_link?: string;
  videos?: PinterestVideos;
}

export interface PinterestSearchResponse {
  cursor: string | null;
  pins: PinterestSearchPin[];
}

export interface PinterestSearchResultAggregatedPinData {
  node_id?: string;
  pin_tags_chips?: PinterestPinTagsChip[];
}

export interface PinterestSearchResultBoard {
  board_order_modified_at?: string;
  collaborating_users?: PinterestCollaboratingUser[];
  collaborator_count?: number;
  cover_images?: PinterestBoardCoverImages;
  id?: string;
  image_cover_hd_url?: string;
  image_cover_url?: string;
  images?: PinterestBoardImages;
  is_collaborative?: boolean;
  name?: string;
  node_id?: string;
  owner?: PinterestSearchResultPinner;
  pin_count?: number;
  pin_thumbnail_urls?: string[];
  section_count?: number;
  type?: string;
  url?: string;
}

export interface PinterestSearchResultImage {
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestSearchResultImageCrop {
  max_y?: number;
  min_y?: number;
}

export interface PinterestSearchResultPinner {
  ads_only_profile_site?: string;
  follower_count?: number;
  full_name?: string;
  id?: string;
  image_large_url?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_ads_only_profile?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestVerifiedIdentity;
}

export interface PinterestSearchResultRichSummary {
  actions?: unknown[];
  aggregate_rating?: PinterestRichMetadataAggregateRating;
  display_cook_time?: number;
  display_name?: string;
  id?: string;
  is_hard_404?: boolean;
  products?: PinterestObjectRichSummaryProduct[];
  site_name?: string;
  type?: string;
  type_name?: string;
  url?: string;
}

export interface PinterestSearchResultStoryPinData {
  has_affiliate_products?: boolean;
  has_product_pins?: boolean;
  id?: string;
  metadata?: PinterestSearchResultStoryPinDataMetadata;
  node_id?: string;
  page_count?: number;
  pages?: PinterestSearchResultStoryPinDataPage[];
  static_page_count?: number;
  total_video_duration?: number;
  type?: string;
}

export interface PinterestSearchResultStoryPinDataMetadata {
  canvas_aspect_ratio?: number;
  compatible_version?: string;
  is_compatible?: boolean;
  is_editable?: boolean;
  is_promotable?: boolean;
  pin_image_signature?: string;
  pin_title?: string;
  root_pin_id?: string;
  root_user_id?: string;
  version?: string;
}

export interface PinterestSearchResultStoryPinDataPage {
  blocks?: PinterestSearchResultStoryPinDataPageBlock[];
  id?: string;
  image_signature?: string;
  image_signature_adjusted?: string;
  layout?: number;
  music_attributions?: PinterestMusicAttribution[];
  should_mute?: boolean;
  style?: PinterestSearchResultStoryPinDataPageStyle;
  type?: string;
  video_signature?: string;
}

export interface PinterestSearchResultStoryPinDataPageBlock {
  audio?: PinterestAudio;
  block_style?: PinterestSearchResultStoryPinDataPageBlockBlockStyle;
  block_type?: number;
  image_signature?: string;
  is_removed?: boolean;
  pin?: PinterestLinkDomain;
  pin_id?: string;
  provider_recording_id?: string;
  style_type?: number;
  text?: string;
  tracking_id?: string;
  type?: string;
  video?: PinterestSearchResultStoryPinDataPageBlockVideo;
}

export interface PinterestSearchResultStoryPinDataPageBlockBlockStyle {
  corner_radius?: number;
  height?: number;
  rotation?: number;
  width?: number;
  x_coord?: number;
  y_coord?: number;
}

export interface PinterestSearchResultStoryPinDataPageBlockVideo {
  id?: string;
  video_list?: Record<string, PinterestVideoVariant>;
}

export interface PinterestSearchResultStoryPinDataPageStyle {
  background_color?: string;
}

export interface PinterestSearchStoryDynamicInsertionOption {
}

export interface PinterestSearchStoryObjectGridAttribution {
  follower_count?: number;
  full_name?: string;
  id?: string;
  image_large_url?: string;
  image_medium_url?: string;
  image_small_url?: string;
  is_ads_only_profile?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  username?: string;
  verified_identity?: PinterestVerifiedIdentity;
}

export interface PinterestSearchStoryObjectImage {
  height?: number;
  url?: string;
  width?: number;
}

export interface PinterestSearchStoryObjectImageCrop {
  max_y?: number;
  min_y?: number;
}

export interface PinterestShippingInfo {
  free_shipping_price?: string;
  free_shipping_value?: number;
}

export interface PinterestUserBoard {
  access?: unknown[];
  action?: PinterestUserBoardAction;
  allow_homefeed_recommendations?: boolean;
  archived_by_me_at?: unknown | null;
  aux_fields?: PinterestSearchStoryDynamicInsertionOption;
  background_colour?: unknown | null;
  board_order_modified_at?: string;
  board_vase?: PinterestBoardVase[] | null;
  bookmarks_for_objects?: unknown | null;
  button_text?: unknown | null;
  closeup_id?: unknown | null;
  collaborated_by_me?: boolean;
  collaborating_users?: PinterestCollaboratingUser[];
  collaborator_count?: number;
  collaborator_requests_enabled?: boolean;
  container_type?: number;
  content_ids?: string[];
  copy?: PinterestSearchStoryDynamicInsertionOption;
  cover_images?: PinterestUserBoardCoverImage;
  cover_pin?: PinterestUserBoardCoverPin;
  created_at?: string;
  custom_properties?: PinterestSearchStoryDynamicInsertionOption;
  description?: string | null;
  display_options?: PinterestUserBoardDisplayOption;
  dynamic_insertion_options?: PinterestSearchStoryDynamicInsertionOption;
  event_date?: unknown | null;
  event_start_date?: unknown | null;
  expanded_viewport_objects?: unknown[];
  experience?: unknown | null;
  experience_extra_context?: PinterestSearchStoryDynamicInsertionOption;
  followed_by_me?: boolean;
  follower_count?: number;
  has_custom_cover?: boolean;
  id?: string;
  image_cover_hd_url?: string;
  image_cover_url?: string;
  images?: PinterestBoardImages;
  is_ads_only?: boolean;
  is_collaborative?: boolean;
  item_actions?: unknown[];
  mapped_display_options?: PinterestSearchStoryDynamicInsertionOption;
  name?: string;
  node_id?: string;
  objects?: PinterestUserBoardObject[];
  owner?: PinterestUserBoardOwner;
  pin_count?: number;
  place_saves_count?: number;
  privacy?: string;
  referring_source?: unknown | null;
  relationships?: PinterestSearchStoryDynamicInsertionOption;
  section_count?: number;
  seo_board_module?: unknown | null;
  shop_source?: unknown | null;
  should_show_board_collaborators?: boolean;
  should_show_more_ideas?: boolean;
  should_show_shop_feed?: boolean;
  slot?: number;
  story_type?: string;
  subtitle?: unknown | null;
  thematic_deal_module?: unknown | null;
  title?: PinterestBoardFeedStorySubtitle;
  tracking_params?: string;
  type?: string;
  url?: string;
  user?: unknown | null;
  viewer_collaborator_join_requested?: boolean;
}

export interface PinterestUserBoardAction {
  url?: string;
}

export interface PinterestUserBoardCoverImage {
  "200x150"?: PinterestSearchStoryObjectImage;
  "236x"?: PinterestUserBoardCoverImage236x;
}

export interface PinterestUserBoardCoverImage236x {
  height?: unknown | null;
  url?: string;
  width?: number;
}

export interface PinterestUserBoardCoverPin {
  crop?: number[];
  custom_cover?: boolean;
  image_signature?: string;
  image_size?: (number | null)[];
  image_url?: string;
  pin_id?: string;
  scale?: number;
  size?: number[];
  timestamp?: number;
}

export interface PinterestUserBoardDisplayOption {
  action_button_location?: unknown | null;
  ai_fwd_presentation_options?: PinterestSearchStoryDynamicInsertionOption;
  align_image_bottom?: boolean;
  allow_pin_height_trimming?: unknown | null;
  background_colors?: unknown | null;
  background_image_url?: unknown | null;
  board_display_options?: unknown | null;
  board_view_type?: unknown | null;
  carousel_fade_ends?: unknown | null;
  carousel_item_spacing?: unknown | null;
  container_grid_span?: unknown | null;
  content_display?: unknown | null;
  corner_radius?: unknown | null;
  cover_image_url?: unknown | null;
  display_view_state?: unknown | null;
  explore_article_display_options?: unknown | null;
  extra_spacing_after?: number;
  extra_spacing_before?: number;
  footer_display?: unknown | null;
  has_condensed_header?: boolean;
  header_display?: unknown | null;
  header_font?: unknown | null;
  header_hidden?: boolean;
  hide_education_in_stream?: unknown | null;
  hide_search_guides_when_visible?: boolean;
  hide_ui_in_stream?: unknown | null;
  horizontal_full_bleed?: boolean;
  ideas_card_hide_when_offscreen?: boolean;
  identifier_icon_name?: unknown | null;
  image_only?: unknown | null;
  item_column_span?: number;
  item_view_rep_style?: unknown | null;
  module_header_alignment?: unknown | null;
  num_columns_requested?: number;
  pin_display_options?: unknown | null;
  pin_image_ratio?: unknown | null;
  scale_up?: unknown | null;
  shopping_grid_display?: unknown | null;
  show_bottom_divider?: boolean;
  show_content_follow_buttons?: unknown | null;
  show_dismiss_button?: unknown | null;
  show_follow_buttons?: unknown | null;
  show_product_indicator_overlay?: unknown | null;
  show_separator?: boolean;
  show_simplified_pin?: boolean;
  show_top_divider?: boolean;
  spacer_size?: unknown | null;
  stacked_card_cover_shade_colors?: unknown | null;
  subtitle_text_color?: unknown | null;
  tiles_grid_layout?: unknown | null;
  title_text_color?: unknown | null;
  use_plain_text_display_mode?: boolean;
}

export interface PinterestUserBoardObject {
  closeup_unified_description?: string;
  image_medium_url?: string;
  node_id?: string;
}

export interface PinterestUserBoardOwner {
  ads_only_profile_site?: unknown | null;
  domain_verified?: boolean;
  explicitly_followed_by_me?: boolean;
  follower_count?: number;
  full_name?: string;
  id?: string;
  image_medium_url?: string;
  is_ads_only_profile?: boolean;
  is_default_image?: boolean;
  is_partner?: boolean;
  is_private_profile?: boolean;
  is_verified_merchant?: boolean;
  node_id?: string;
  type?: string;
  username?: string;
  verified_identity?: PinterestSearchStoryDynamicInsertionOption;
}

export interface PinterestUserBoardsResponse {
  boards: PinterestUserBoard[];
  cursor: string | null;
}

export interface PinterestVerifiedIdentity {
  name?: string;
  verified?: boolean;
}

export interface PinterestVideoVariant {
  best_captions_url?: string;
  block_id?: string;
  captions_urls?: Record<string, string>;
  duration?: number;
  height?: number;
  thumbnail?: string;
  url?: string;
  width?: number;
}

export interface PinterestVideos {
  id?: string;
  node_id?: string;
  video_list?: Record<string, PinterestVideoVariant>;
}

export type PublicError = "blocked" | "concurrency_exceeded" | "timeout" | "extraction_failed" | "upstream_blocked" | "upstream_unavailable" | "upstream_response_invalid" | "invalid_url_scheme" | "invalid_url_host" | "unauthenticated" | "forbidden" | "resource_forbidden" | "not_found" | "rate_limited" | "invalid_request" | "invalid_cursor" | "insufficient_credits" | "internal_error";

export interface SearchPinsParams {
  /** The `cursor` from the previous page. Omit it, or send it empty, for the first page. */
  cursor?: string | null;
  /** What to search Pinterest pins for. */
  query: string;
  /** Accepted for Scrape Creators compatibility. It has no effect: the answer is always the full body. */
  trim?: boolean | null;
}
