// Generated by generate-client from spec/openapi.json. Do not edit.

import { BaseClient } from './base.js';
import type { TaplineClientConfig } from './types.js';
import { AirbnbClient } from './services/airbnb/client.js';
import { YoutubeClient } from './services/youtube/client.js';
import { GmgnClient } from './services/gmgn/client.js';
import { GeckoterminalClient } from './services/geckoterminal/client.js';
import { PonsfamilyClient } from './services/ponsfamily/client.js';
import { GoplusClient } from './services/goplus/client.js';
import { TwitterClient } from './services/twitter/client.js';
import { PinterestClient } from './services/pinterest/client.js';
import { PumpfunClient } from './services/pumpfun/client.js';
import { TiktokClient } from './services/tiktok/client.js';

export class TaplineClient {
  readonly airbnb: AirbnbClient;
  readonly youtube: YoutubeClient;
  readonly gmgn: GmgnClient;
  readonly geckoterminal: GeckoterminalClient;
  readonly ponsfamily: PonsfamilyClient;
  readonly goplus: GoplusClient;
  readonly twitter: TwitterClient;
  readonly pinterest: PinterestClient;
  readonly pumpfun: PumpfunClient;
  readonly tiktok: TiktokClient;

  constructor(config: TaplineClientConfig = {}) {
    const base = new BaseClient(config);
    this.airbnb = new AirbnbClient(base);
    this.youtube = new YoutubeClient(base);
    this.gmgn = new GmgnClient(base);
    this.geckoterminal = new GeckoterminalClient(base);
    this.ponsfamily = new PonsfamilyClient(base);
    this.goplus = new GoplusClient(base);
    this.twitter = new TwitterClient(base);
    this.pinterest = new PinterestClient(base);
    this.pumpfun = new PumpfunClient(base);
    this.tiktok = new TiktokClient(base);
  }
}
