// Generated by generate-client from spec/openapi.json. Do not edit.

import { BaseClient } from './base.js';
import type { TaplineClientConfig } from './types.js';
import { AirbnbClient } from './services/airbnb/client.js';
import { YoutubeClient } from './services/youtube/client.js';
import { GmgnClient } from './services/gmgn/client.js';
import { GeckoterminalClient } from './services/geckoterminal/client.js';
import { GoplusClient } from './services/goplus/client.js';

export class TaplineClient {
  readonly airbnb: AirbnbClient;
  readonly youtube: YoutubeClient;
  readonly gmgn: GmgnClient;
  readonly geckoterminal: GeckoterminalClient;
  readonly goplus: GoplusClient;

  constructor(config: TaplineClientConfig = {}) {
    const base = new BaseClient(config);
    this.airbnb = new AirbnbClient(base);
    this.youtube = new YoutubeClient(base);
    this.gmgn = new GmgnClient(base);
    this.geckoterminal = new GeckoterminalClient(base);
    this.goplus = new GoplusClient(base);
  }
}
